### ISSUE TITLE
pg_wal directory grows indefinitely even though the archive succeeded (pgbackrest)

### ISSUE THREAD

**Issue by ajoyej** [CrunchyData/postgres-operator#1136]
With pgo V4.1.0 (postgresql version 11.5), we have the following issue:

`/pgdata/<cluster-name>/pg_wal` directory grows indefinitely with old/expired WAL files.
In the `.\archive_status` sub-folder, all these files are present with the `.done` extension (which should mean that archive was successful and therefore, the WAL file should be deleted).
In the backrest pod, the files are present --> means the archiving from _data_ to _Backrest_ pod was ok.

We also tried to run several full and diff backups in a raw to make sure the retention for both full and diff backups did not 'locked' the WAL files due to non expired backups (our retention for full and diff is set to 2). 
--> This does not have any effect on the `/pgdata/<cluster-name>/pg_wal` directory (as expected).

our Archive Configuration is as follow in `postgresql.conf`:

archive_command = 'pgbackrest archive-push %p'
archive_mode = on
archive_timeout = 1800

Any hints, more than welcome

**Comment by jkatz** [comment]
Hi @ajoyej,

In the `REL_4_1` line the default setting for `wal_keep_segments` is 400, which means 400 WAL files will be kept in the `pg_wal` directory (~6.4GB of WAL).

If you have more than 400 WAL files, check to see if you have set up any replication slots. You can determine this by:

```sql
SELECT * FROM pg_catalog.pg_replication_slots ;
```

If you have any slots set up, check to see if they are being consumed. If they are not being consumed, this can lead to WAL files not being cleared once they hit the 400 mark.

In in the release `v4.2.0`, we have set `keep_wal_segments` to `0`. This is due to relying solely on pgBackRest for WAL archive management, and leveraging `min_wal_size`/`max_wal_size` for local management.

**Comment by ajoyej** [comment]
Thanks for the answer!
We will set our default to 0 as well as we rely solely on pgBackrest.

José

**Comment by jkatz** [comment]
@ajoyej One thing to check: be sure that your replicas are set up to be able to accepted recovery from a pgBackRest archive.

The `wal_keep_segments` was set high to keep replicas in sync with streaming replication. We modified this whole approach on `master`/`v4.2` so this would not have to be the case, and i.e. , the replicas can catch up from the pgBackRest archives. However, I would recommend that you ensure you can achieve similar behavior on `v4.1` (I'm not sure off the top of my head unfortunately!) so that way you do not have a replica get out of sync and then need to be reinitializedd.

**Comment by ajoyej** [comment]
Hello,
thanks for the clarification.
How can I override the `wal_keep_segments` so it is taken by pgo at cluster instantiation?

Should I place a postgresql.conf file inside `\conf\postgres-operator` folder?
Is there an easier way?

Thanks
José

**Comment by ajoyej** [comment]
Hello,
thanks for the clarification.
How can I override the `wal_keep_segments` so it is taken by pgo at cluster instantiation?

Should I place a postgresql.conf file inside `\conf\postgres-operator` folder?
Is there an easier way?

Thanks
José

**Comment by jkatz** [comment]
Hi @ajoyej,

There are some examples for setting custom PostgreSQL configurations here:

- [https://access.crunchydata.com/documentation/postgres-operator/latest/gettingstarted/design/custom-config/#custom-postgres-configurations](https://access.crunchydata.com/documentation/postgres-operator/latest/gettingstarted/design/custom-config/#custom-postgres-configurations)
- [https://github.com/CrunchyData/postgres-operator/blob/master/examples/custom-config/create.sh](https://github.com/CrunchyData/postgres-operator/blob/master/examples/custom-config/create.sh)

For v4.1, you need to modify the `pgo-custom-pg-config` configmap with the updated `postgresql.conf` file.

Thanks!

**Comment by ajoyej** [comment]
Thanks!
