### ISSUE TITLE
Understanding Postgres Deployments

### ISSUE THREAD

**Issue by jacobzhang0110** [CrunchyData/postgres-operator#1190]
From document it seems there will be one primary K8S deployment and multiple replica K8S deployments. 
Also, scaling in/out is done by removing/adding a K8S deployment.
Does it imply in each K8S deployment there is only one pod?

**Comment by andrewlecuyer** [comment]
@jacobzhang0110 that is correct.  With the current operator architecture the primary, as well as all replicas, are each individual Kubernetes deployments comprised of a single pod.  Scaling therefore involves adding additional Kubernetes deployments (or removing them if scaling down), rather than scaling the individual Kubernetes deployments themselves.

**Comment by jkatz** [comment]
Hi @jacobzhang0110 This is also described in detail in our [architecture documentation](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/overview/), including how Deployments are used as well as the various mechanics of how the PostgreSQL clusters are managed. The architecture is used to enable heterogeneous deployments of PostgreSQL instances, e.g. if you want to have your replicas use different resource/storage class combinations vs. the primary.

You can read about performing scaling operations with the PostgreSQL Operator here: https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/common-tasks/#high-availability-scaling-up-down
