### ISSUE TITLE
Delete replicat error 

### ISSUE THREAD

**Issue by aurelien43** [CrunchyData/postgres-operator#1201]
Hello, 
During the test of postgres-operator v4.2.0, we have found a small bug when a replica is raised as primary due to failover 

**To Reproduce**
Steps to reproduce the Bug :
1. Start a cluster with one replica 
2. execute failover command 
3. the new replica can't be deleted with pgo scaledown command. 

**Please tell us about your environment:**
- Operating System: centos7
- Where is this running ( Local, Cloud Provider): VM
- Storage being used (NFS, Hostpath, Gluster, etc): Hostpath
- Container Image Tag: centos7-12.1-4.2.0
- PostgreSQL Version: 12.1
- Platform (Docker, Kubernetes, OpenShift): Kubernetes
- Platform Version: 1.16

![error](https://user-images.githubusercontent.com/25898200/72171746-e1f0eb80-33d3-11ea-87a2-da841b32bd5f.PNG)

**Comment by saltenhub** [comment]
I do have exactly the same bug, infos attached
**Describe the bug**
After failover, the replica that used to be the master node cannot be deleted anymore.
Output of `pgo show cluster`
```
cluster : postgresql (crunchy-postgres-ha:centos7-12.1-4.2.0)
	pod : postgresql-747cb9fbc8-4ssll (Running) on node03.redacted.com (3/3) (replica)
	pvc : postgresql
	pod : postgresql-bibm-5559c56495-mtbn4 (Running) on node01.redacted.com (3/3) (primary)
	pvc : postgresql-bibm
	resources : CPU Limit= Memory Limit=, CPU Request= Memory Request=
	storage : Primary=100G Replica=100G
	deployment : postgresql
	deployment : postgresql-backrest-shared-repo
	deployment : postgresql-bibm
	service : postgresql - ClusterIP (x.x.x.x)
	service : postgresql-replica - ClusterIP (x.x.x.x)
	pgreplica : postgresql-bibm
	labels : current-primary=postgresql-bibm name=postgresql crunchy-pgbadger=true crunchy_collect=true pg-pod-anti-affinity= pgouser=admin pgo-backrest=true workflowid=96370049-d636-4946-be86-bebf36014db8 pgo-version=4.2.0 archive-timeout=60 autofail=true crunchy-pgha-scope=postgresql deployment-name=postgresql pg-cluster=postgresql 
```
Output of `pgo scaledown postgresql --query`:
```
Cluster: postgresql
REPLICA             	STATUS    	NODE      	REPLICATION LAG
postgresql          	running   	node03.redacted.com	           0 MB
```
Output of `pgo scaledown postgresql --target postgresql`:
```
Error: no replicas found for this cluster
```
**To Reproduce**
Steps to reproduce the behavior:
1. Create cluster with replica
2. Manual failover to replica via `pgo failover` as described in the [manual](https://access.crunchydata.com/documentation/postgres-operator/4.2.0/pgo-client/common-tasks/#advanced-operations)
3. Try to delete replica that used to be the master node with `pgo scaledown`
4. See error `Error: no replicas found for this cluster` (see also cli output attached above)

**Expected behavior**
The replica (used to be master) node can be scaled down and deleted after failover.

**Please tell us about your environment:**
* Operating System:
* Where is this running ( Local, Cloud Provider): Local baremetal
* Storage being used (NFS, Hostpath, Gluster, etc): Hostpath
* Container Image Tag: centos7-12.1-4.2.0
* PostgreSQL Version: 12.1
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version: 1.16.3

Is there a workaround / quick fix that we can apply so that the replica can be deleted without waiting for the next release?

**Comment by andrewlecuyer** [comment]
Hi @aurelien43 , thanks so much for bringing this to our attention.  The behavior you are seeing is the result of a known limitation with the current PostgreSQL Operator in which it is not possible to scale down the original primary following a failover.

However, as a workaround you can do the following:

1.) Create a simple `pgreplica` CR representing the old primary using the following template (ensuring the cluster name and namespace match your environment):

```bash
kubectl create -f - <<END
apiVersion: crunchydata.com/v1
kind: Pgreplica
metadata:
  labels:
    name: mycluster1
    pg-cluster: mycluster1
  name: mycluster1
  namespace: pgouser1
spec:
  clustername: mycluster1
  status: completed
status:
  message: Successfully processed Pgreplica by controller
  state: pgreplica Processed
END
```

2. Re-label the Kubernetes Deployment for the old primary as follows:

```bash
kubectl label deployment mycluster1 service-name=mycluster1-replica --overwrite
```

Once the above steps have been completed, you should simply be able to proceed with scaling down the replica (i.e. the original primary) as you typically would, e.g.:

`pgo scaledown mycluster1 --target=mycluster1`

This should then result in the deletion of the original primary.
