### ISSUE TITLE
Installation via operatorhub incomplete

### ISSUE THREAD

**Issue by philipp1992** [CrunchyData/postgres-operator#1255]
there are so many things missing... 

how am i supposed to get it running from operatorhub ? where is the documentation?

**Comment by jkatz** [comment]
Hi @philipp1992,

Please be more specific. Which version are you trying to install? What issues are you running into?

(Please also note we have a patch open to update to 4.2.1 which makes more changes as well.)

Additionally, all documentation can be found here:

https://access.crunchydata.com/documentation/postgres-operator/latest/

as well as a Quickstart that covers some additional installation methods as well:

https://access.crunchydata.com/documentation/postgres-operator/latest/quickstart/

The documentation is clearly linked from the OperatorHub page, which you can view here:

https://operatorhub.io/operator/postgresql

Thanks!

**Comment by philipp1992** [comment]
okay, so im refering to the following docu:

https://operatorhub.io/operator/postgresql

**"Edit conf/postgres-operator/pgo.yaml to configure the operator deployment."**
why do i have to make decisions about the cluster before installing the operator?

**Create the pgo-backrest-repo-config Secret that is used by the operator.**
it tells me to use aws s3 credentials, what if i dont want to use s3 or backrest at all?

**Install the bootstrap credentials:**
here it doesnt tell me, that i should adjust the credentials, so i end up with an exampleuser if i dont open the script and check it.

also i cant run the script on centos because:
[root@vmd47642 postgres-operator]# $PGOROOT/deploy/install-bootstrap-creds.sh
/root/postgres-operator/deploy/install-bootstrap-creds.sh: line 31: expenv: command not found
/root/postgres-operator/deploy/install-bootstrap-creds.sh: line 31: create: command not found
/root/postgres-operator/deploy/install-bootstrap-creds.sh: line 38: create: command not found
/root/postgres-operator/deploy/install-bootstrap-creds.sh: line 38: expenv: command not found


**Create the pgo-config ConfigMap that is used by the operator.**
what configmap?

**Comment by philipp1992** [comment]
also when i then follow the instructions on operatorhub "INSTALL" it will try to install the operator to the namespace my-postgresql

**Comment by jkatz** [comment]
> **"Edit conf/postgres-operator/pgo.yaml to configure the operator deployment."**
> why do i have to make decisions about the cluster before installing the operator?

You don't have to if you don't want to. This is to provide guidance if you want to make additional customizations.

The [pgo.yaml](https://access.crunchydata.com/documentation/postgres-operator/latest/configuration/pgo-yaml-configuration/) file provides templates that help with setting up your PostgreSQL clusters. Many of these settings can be overridden with `pgo create cluster` but we allow for commonly use settings to be stored.

> **Create the pgo-backrest-repo-config Secret that is used by the operator.**
> it tells me to use aws s3 credentials, what if i dont want to use s3 or backrest at all?

You don't have to use S3 (in fact, the default is to not do that). pgBackRest is the only [backup management](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/disaster-recovery/) solution for the PostgreSQL Operator. We have standardized around this as it allows us to do several things, including:

- Backup to both mounted storage + S3 :wink:
- Efficiently scale and autoheal replicas leveraging its restore mechanisms and delta restores (particularly helpful for very large databases)
- Clone PostgreSQL clusters
- Managing retention policies, etc.

I can understand that some of these directions need to be updated. Please see below about pending updates.

> **Install the bootstrap credentials:**
> here it doesnt tell me, that i should adjust the credentials, so i end up with an exampleuser if i dont open the script and check it.

```shell
export PGOADMIN_USERNAME=pgoadmin
export PGOADMIN_PASSWORD=examplepassword
export PGOADMIN_ROLENAME=pgoadmin
export PGOADMIN_PERMS="*"
```

You can adjust these environmental variables, and I do agree we can make that easier. We can look into that for a future OLM update.

> also i cant run the script on centos because:
> [root@vmd47642 postgres-operator]# $PGOROOT/deploy/install-bootstrap-creds.sh
> /root/postgres-operator/deploy/install-bootstrap-creds.sh: line 31: expenv: command not found
> /root/postgres-operator/deploy/install-bootstrap-creds.sh: line 31: create: command not found
> /root/postgres-operator/deploy/install-bootstrap-creds.sh: line 38: create: command not found
> /root/postgres-operator/deploy/install-bootstrap-creds.sh: line 38: expenv: command not found

Run

```shell
export PGO_CMD=kubectl
```
to fix the `create` issue and then run the command. If you're deploying to OpenShift, use `oc` instead of `kubectl`.

You can download `expenv` from here:

https://github.com/CrunchyData/postgres-operator/releases/tag/v4.2.1

We are aiming to get rid of `expenv`, hopefully by the 4.3.0 release.

> **Create the pgo-config ConfigMap that is used by the operator.**
> what configmap?

This is specified on the OperatorHub page:

```shell
kubectl create configmap -n pgo pgo-config \
  --from-file=$PGOROOT/conf/postgres-operator
```

As I mentioned, there are some [updates coming](https://github.com/operator-framework/community-operators/pull/1133) that should make the experience installing from OperatorHub a bit easier. Because of the development history of the PostgreSQL Operator, we have a lot of stuff that comes with it (e.g. multiple CRDs) and because of all the different configurations you can apply to PostgreSQL, we've tried to make things both robust and easy to setup at the same time, which presents its own challenges!

Thanks.

**Comment by philipp1992** [comment]
thank you so much for the fast and detailled information, thats really awesome.

do you recommend installing via ansible?

**Comment by jkatz** [comment]
@philipp1992 Yes. The Ansible install is a bit more robust (as it accounts for some of the nuances of PostgreSQL in a Kubernetes-like environment) and easier to use at this point. We've found that people tend to love it :smile:

We do have ongoing work to make it even easier, as we are planning to build out an "installer container" as part of the 4.3.0 release, though that won't be available for a couple of months.

Our goal is to make installation as simple as possible, but allow for all of the customizations we have available. It's tough, but we hope we're getting better each release!

Hope this helps.

**Comment by dejwsz** [comment]
I can confirm the ansible installer is the best option, much better than OLM.
