### ISSUE TITLE
Openshift Postgresql operator never start up any ressource

### ISSUE THREAD

**Issue by danifernandezs** [CrunchyData/postgres-operator#1299]
Hi,

We are having trouble to deploy he operator: “Crunchy PostgreSQL for OpenShift 4.2.1” in Openshift 4.2.13.

We are using the certified (RedHat one) version of the operator. 
When the operator deploys (with no visible issues) it does not have the expected behavior. 
We have also seen that there are a multitude of pre-installation requirements, and some of them are quite striking to be a certified Operator
 
Issue:
Opening the operator and creating a Postgres Primary Cluster Member should create the resources that make up the defined postgres cluster, however it does not create anything. (no secrets, configmaps, deployments or pods)

We have performed three tests. 
The first test the behavior was slightly different, in that case if you tried to create the resources of the postgres cluster but it was wrong because some secrets were not be created automatically, if we delete that cluster the operator stopped creating the resources as in the other tests. 
In the second and third (in different projects always) nothing is created.

 **Please tell us about your environment:**
Openshift cluster over AWS

* Operating System: CoreOS
* Where is this running ( Local , Cloud Provider): AWS
* Storage being used (NFS, Hostpath, Gluster, etc): gp2
* Container Image Tag: 
* PostgreSQL Version: 
* Platform (Docker, Kubernetes, OpenShift): OpenShift
* Platform Version: 4.2.13 and 4.2.14

**Comment by jkatz** [comment]
Hi @danifernandezs,

I would recommend that you try using one of the other installation methods, in particular: 

- [Using the Ansible Installer](https://access.crunchydata.com/documentation/postgres-operator/latest/installation/install-with-ansible/)

I can assure you that this works very well and we know of many users successfully deploying on OpenShift via this method as well.

Because of some of the legacy setup we have, the OLM installer (which is what comes with the certified packages) may not be as thorough as the one mentioned above. As mentioned in #1298, we are making some significant changes to the install process in the upcoming 4.3 version that should improve this. 

Additionally, some of the prerequisite steps are for convenience: for instance, the `pgo-config` ConfigMap that you allude to allows you set pre-defined defaults for your most common PostgreSQL cluster types, so you and your users can more easily create PostgreSQL clusters with the `pgo` client.

Once the Operator is deployed, I do recommend taking a look at how to use the [`pgo` client](https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/). This helps with the automation process of being able to deploy resources. This handles a lot of the automation & complications, and is getting better with each release.

Keep in mind that the PostgreSQL Operator began development back in 2017 and certain workflows/capabilities were different back then. We are moving towards being able to support a CR-only workflow (which is the way the industry is heading), but it will take some time :smile:  If you do wish to use a CR-only workflow, you can check out this guide:

- [Deploy PostgreSQL Clusters with Kubernetes CRDs](https://info.crunchydata.com/blog/creating-a-postgresql-cluster-with-kubernetes-crds)

and we will continue to improve how the Operator can be deployed both with the OLM installation method and using said CR-only workflow.

Thanks!
