### ISSUE TITLE
How to modify max_connections on an aleady running cluster?

### ISSUE THREAD

**Issue by mnowrot** [CrunchyData/postgres-operator#1301]
** Which example are you working with? **
custom-config-ssl

**What is the current behavior?**
Cannot modify max_connections on an already deployed cluster. 

**What is the expected behavior?**
max_connections should be modifiable after the cluster has already been created

**Other information** (e.g. detailed explanation, related issues,  etc)
No matter if I edit postgres-ha.yaml in the config map directly or create a file 'postgresql.conf' in the same config map (both followed with pgo reload cluster-name) with the wanted setup, max connections is always shown as 100 by `psql -c 'show max_connections;'`

**Please tell us about your environment:**

* Operating System: RedHat Enterprise Linux 7.6
* Where is this running ( Local , Cloud Provider) Local bare metal Openshift cluster
* Storage being used (NFS, Hostpath, Gluster, etc): Gluster
* Container Image Tag: crunchydata/pgo-apiserver:centos7-4.2.0
* PostgreSQL Version: 11.6
* Platform (Docker, Kubernetes, OpenShift): Openshift
* Platform Version: 4.2.10

**Comment by andrewlecuyer** [comment]
@mnowrot in order to configure the `max_connection` setting, it must be configured in the DCS (Distributed Configuration Store) for the cluster.  This is to ensure the setting is consistent across all database servers (i.e. the primary and all replicas) within the cluster.  Therefore, when creating your custom `postgres-ha.yaml` configuration file prior to creating the cluster, please ensure `max_connections` is defined within the `dcs` section, such as:

```
---
bootstrap:
  dcs:
    postgresql:
      parameters:
        max_connections: 98
```

If you set the setting in the custom `postgresql.conf`, or in the `postgresql` section right under the root of the `postgres-ha.yaml` file, it will simply default to `100`.

If you are looking to modify this setting for an existing cluster, you will need to look for a `configMap` called `<cluster-name>-config` (which is the portion of the DCS storing cluster-wide PG configuration).  You can then open that `configMap` for editing, e.g. using `oc edit cm <cluster-name>-config`, and add the `max_connections` setting to the `config` annotation as follows:

```
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    config: '{"postgresql":{"parameters":{"max_connections":99,"archive_command":"source
...
```

After this a restart will be required, which can be accomplished by using `kubectl exec` to access the primary pod, and then running `patronictl restart`, e.g.:

```
kubectl exec -it mycluster1-6f87fd54ff-c6c2w -- patronictl restart mycluster1
```

**Comment by mnowrot** [comment]
Thank you a lot for a detailed @andrewlecuyer - the issue is now resolved. It'd be really nice if this information could find it's way into documentation of the operator
