### ISSUE TITLE
Restore deleted cluster

### ISSUE THREAD

**Issue by dvianello** [CrunchyData/postgres-operator#1305]
** Which example are you working with? **
Created a cluster called `test`, backed it up on S3 via `pgbackrest`, deleted cluster via pgo, tried a restore from s3

**What is the current behavior?**
```
bash-4.2$ pgo restore test -n postgres-dbs --pitr-target="2020-02-27 09:40:00.000000+00" --backup-opts="--type=time" --pgbackrest-storage-type s3
Warning:  If currently running, the primary database in this cluster will be stopped and recreated as part of this workflow!
WARNING: Are you sure? (yes/no): yes
Error: test was not found, verify cluster name
```
**What is the expected behavior?**
PGO recovers lost database from S3.

**Other information** (e.g. detailed explanation, related issues,  etc)
The above seems a relevant use-case to cover in case of: 
- a severe disaster recovery scenario where a K8S cluster is lost. 
- a clumsy human operator deletes the wrong cluster

**Comment by jkatz** [comment]
Did you call `pgo delete cluster` with the `--keep-backups` flag?

I will note even with that flag on, while it does keep the the pgBackRest repository, there are some hoops to jump through at the moment, and we would have to make a restore from that backup repository easier. You could be able to restore from a logical backup (if you took them) but I would have to check.

**Comment by dvianello** [comment]
Nope, no `--keep-backups` flag, as the intent was simulating the loss of a K8S cluster and recovery onto a new one, which failed.

Are we saying that `pgo` relies on the `backrest-shared-repo` pod being around _even_ for S3 backups? I thought backing off to S3 was a way to ensure that, even if everything went wrong with the cluster, one could recover from just the data stored in S3?

**Comment by jkatz** [comment]
H @dvianello ,

If you have your data in a S3 repository, you can still restore it, regardless of having the Operator around. There are some manual steps for that process, though we are working on making some improvements to ensure it's more automatic.

Thanks.

**Comment by dvianello** [comment]
Hi @jkatz,

glad to hear there are manual steps - are these documented somewhere?

Best,
Dario

**Comment by dejwsz** [comment]
I am interested in the manual steps too.

**Comment by philmcc** [comment]
I would like to know the process for this. It would be very useful for migrating data into the cluster from outside as well.

**Comment by asoltesz** [comment]
I am struggling with this exact same test and would also like to know the manual process needed for this.

@dvianello May I recommend extending the issue title with "from s3 storage" or something similar to make the issue description more specific?

**Comment by asoltesz** [comment]
> I There are some manual steps for that process, though we are working on making some improvements to ensure it's more automatic.

Currently, stanza-create fails if you try to create a cluster with S3 access parameters set with the parameters of the deleted cluster. (cluster name is the same for both: hippo). It is also not possible to execute S3 restores with the failed stanza.

If pgBackrest could properly initialize in a case like this (accept S3 as the source of thruth), the problem would be mostly solved since after the successful cluster create, you could simply call a restore from s3 with PITR.

**Comment by asoltesz** [comment]
@jkatz 
If we could manually set the system-id to pgBackrest when the new cluster is created (to the same cluster-id it had in the destroyed cluster), that may allow proper stanza-create and restores from S3.

I don't know what side-effects this may cause but this seems to be the nexus around stanza-creation and restore failures.

**Comment by asoltesz** [comment]
Side note: Easy restore capability from S3 is not only important for disaster recovery scenarios but for cross-k8s-cluster migrations as well. 

A shared S3 bucket is a good swapping place for data when migrating.

**Comment by andrewlecuyer** [comment]
Our new standby cluster feature in v4.3 allows you to bootstrap a cluster from an existing pgBackRest repository located in an S3 storage bucket, and is great for some of the disaster recovery and migration scenarios discussed here.

Essentially you provide your S3 details and credentials as always when creating the cluster via the `pgo` client, but then also provide the `--standby` flag, the `--pgbackrest-repo-path` flag that points to the location of the repo in the S3 bucket, and password credentials matching the database you will be bootstrapping from via the pgBackRest repo:

```bash
pgo create cluster mycluster \
  --standby \
  --pgbackrest-storage-type=s3 \
  --pgbackrest-s3-key=key \
  --pgbackrest-s3-key-secret=keysecret \
  --pgbackrest-s3-bucket=somebucket \
  --pgbackrest-s3-endpoint=s3.amazonaws.com \
  --pgbackrest-s3-region=us-east-1 \
  --pgbackrest-repo-path=/backrestrepo/mycluster-backrest-shared-repo \
  --password-superuser=superuserpassword \
  --password-replication=replicationpassword \
  --password=password
```

The only difference is that when creating a cluster as a standby, it will initially be in a recovery (i.e read-only) mode (great in migration scenarios, when you want to validate your data before the database is writeable).  Therefore, once you are ready to make the database writable, you can then promote the cluster with the following command (this will disable standby mode):

```bash
pgo update cluster mycluster --promote-standby
```

And before disabling standby per the above command, you'll want to be sure to shutdown any existing databases that are writing to that same pgBackRest repo (e.g. the database you are migrating from).  This can be done using the `--shutdown` flag with the `pgo update` command if that database is managed by the PostgreSQL Operator:

```bash
pgo update cluster oldcluster --shutdown
```

**Comment by asoltesz** [comment]
@andrewlecuyer Thanks, this is great.
I will try a complete DR scenario with it.

**Comment by asoltesz** [comment]
@andrewlecuyer 

I have managed to test a full S3 backup / disaster / restore scenario with a micro-sized database according to your instructions and the standby feature seems to do the job fine in my environment.

Some things that may be problems:

1) Storage type
In the original (pre-disaster) cluster state, the cluster's --pgbackrest-storage-type was "local,s3".
During the recovery, only "s3" is accepted for the "standby" mechanism. I couldn't find a way to switch it back to "local,s3" after the recovery and local backups are refused with the "s3" setting. Not a big problem for me but may be for others. Is there a way to change this after cluster create?

2) Readiness probe
During the recovery, I took a look at the readiness probe settings of the Postgres pod and they seemed to be the same as in normal mode. This doesn't feel right, because there can be situations when a huge database needs to be loaded from S3 and possibly lot of WAL segments need to be played on the database. 
I think that will result in reaching the readiness threshold and the Postgres pod gets killed in mid-recovery.

**Comment by alrooney** [comment]
@jkatz thanks for pointing me at this issue.  So seems like this would be a lot simpler if we could save and restore a pg_dump to a particular s3 bucket.  The conversation here is all around backrest which is closely tied to the specific cluster vs  a pg_dump which is much more generic.  How hard would it be to make it so that for saving or restoring pg_dump you can specify an arbitrary s3 bucket?

**Comment by jkatz** [comment]
This should be resolved in v4.4.0 by #1679, i.e. there is an automated procedure to create a PostgreSQL cluster from a pgBackRest repository even if that repository is not associated with an active PostgreSQL cluster.

**Comment by abdennour** [comment]
Fair enough @jkatz  . But where is the documentation of this feature?

**Comment by jkatz** [comment]
@abdennour As mentioned, this is coming out in the v4.4 release. You can find a preview of the release here:

[https://github.com/CrunchyData/postgres-operator/releases/tag/v4.4.0-beta.1](https://github.com/CrunchyData/postgres-operator/releases/tag/v4.4.0-beta.1)

The complete documentation will be available upon release. I actually happen to be working on a patch that describes several of these workflows.
