### ISSUE TITLE
pgo show pvc command returns error

### ISSUE THREAD

**Issue by pmereddy1** [CrunchyData/postgres-operator#136]
pgo show pvc command requires the name of PVC. If it is not specified, the command returns an error.
If a pvc name is specified, the output shows all the pvc names as shown below.

Can you modify "pgo show pvc" command to list all pvcs and "pvc show pvc <pvcname>" to show only the pvc requested ?

$ pgo show pvc
ERRO[0000] PVC name(s) required for this command        

$ pgo show pvc abc-pvc
	/abc
	/oldone
	/oldone-upgrade

**Comment by jmccormick2001** [comment]
merged into pre26...with this change 'pgo show pvc all' will give you a listing of all operator created PVCs...this is similar to the 'pgo show cluster all' command from a syntax perspective...the 'all' value will not however produce a file listing, if a user needs that, they will have to drill down using further 'pgo show pvc somepvc --pvc-root' commands due to the nature of getting PVC information in the current implementation.
