### ISSUE TITLE
pgo scale could have --backup-opts as option

### ISSUE THREAD

**Issue by jose-joye** [CrunchyData/postgres-operator#1401]
Hello,
It may make sense to consider adding the `--backup-opts` as parameter to pgo scale command (since it uses pgBackrest to scale the replica(s)).

For large dB, using a single process to restore the a dB could take a very long time.
Passing `--process-max=xyz` could improve the situation.

On our side, we are trying to scale up a DB with 3TB of data. Using `--process-max=6`, the backup takes 4 hours. However, the scaling takes much longer.

Thanks again for the great work :-)
José

**Comment by jkatz** [comment]
Good suggestion.

Curious: do you take a backup prior to scaling? That _should_ help with the restore, but as you suggest, you'd still likely need to `process-max` parameter.

**Comment by jose-joye** [comment]
@jkatz 
Yes, we did a full backup prior the scaling

**Comment by ValClarkson** [comment]
Hi @jose-joye 

With the release of [PGO v5](https://access.crunchydata.com/documentation/postgres-operator/latest/), we are now re-evaluating various GitHub issues, feature request, etc. from previous PGO v4 releases. More specifically, in order to properly prioritize the features and fixes needed by our end-users for upcoming PGO v5 releases, we are now attempting to identify which PGO v4 issues, use-cases and enhancement requests are still valid (especially in the context of PGO v5).

Therefore, please let us know if you are still interested in having the enhancement described in this issue implemented in PGO v5.

If so, you can either respond to this issue directly to ensure it remains open, or you can close this issue and submit a new one for PGO v5 (this would also be a great opportunity to include any updated details, context or any other information relevant to your issue). Otherwise, we will be closing this issue in the next 30 days.

If you are still running PGO v4, we recommend that you [upgrade to PGO v5](https://access.crunchydata.com/documentation/postgres-operator/latest/guides/v4tov5/) as soon as possible to ensure you have the latest PGO features and functionality.
