### ISSUE TITLE
Upgrade between pgo versions does not always work using the official way

### ISSUE THREAD

**Issue by jose-joye** [CrunchyData/postgres-operator#1408]
Hello,
We have recently upgraded from pgo 4.1 to 4.2.2 and also all our clusters using the way you proposed:
- backup the cluster
- scale down the cluster
- delete the clusters and keep pvcs (data and backup)
- upgrade pgo
- recreate the clusters  using the exact same names
- scale up as needed

This works great if no failover occurred. In case of a failover, the data pvc of the primary (after the failover) does not exactly match the name of the cluster any more (it has a suffix). 
In such a situation, when the cluster is newly created, a new data pvc is also created for the primary (matching exactly the cluster name) and an empty postgresql cluster will be provided.

For us, this was not a big issue. The backup was there. We had to add an extra step to restore the cluster.

It may make sense to add this information within the documentation where you explain how to upgrade the operator.

José

**Comment by jkatz** [comment]
Hi @jose-joye,

Sounds like a great thing for you to contribute :wink: The documentation around upgrading is kept over here:

[https://github.com/CrunchyData/postgres-operator/tree/master/docs/content/Upgrade](https://github.com/CrunchyData/postgres-operator/tree/master/docs/content/Upgrade)

I will note that #1364 does also make changes to the upgrade documentation (amongst other things) but I believe it would still be worth getting your notes in, and  wecan go from there, as by design #1364 will be one of the last commits prior to stamping v4.3.0

Thanks,

Jonathan

**Comment by jose-joye** [comment]
Hi @jkatz ,

I just created a pull request for this.
Not sure my English is good enough....

José
