### ISSUE TITLE
Postgres-operator version compatibility?

### ISSUE THREAD

**Issue by huizengaJoe** [CrunchyData/postgres-operator#1414]
Hi, hopefully this is an appropriate place to post a question,  I am working with multiple product teams that are looking to use your postgres-operator, unfortunately several of the teams have requirements for a different version, anywhere from 4.0.1 > 4.3.  With CRD's being cluster scoped, I am wondering if it is possible for each product to use a different version of the operator?  These products could very well be running within the same cluster.

**Comment by jkatz** [comment]
I don't remember which version this changed (it may be 4.1), but CRDs are no longer Cluster scoped. As of 4.3, the Operator itself does not require any `ClusterRole` privileges to successfully use most functionality (really, everything but the multi-namespace support).

Each product could use a different version of the Operator, but I would recommend at least 4.2 due to the changes in how [high-availability is handled](https://github.com/CrunchyData/postgres-operator/releases/tag/v4.2.0) and due to where ongoing updates to the containers are being applied -- and really 4.3 (which will be GA "soon") which increases flexibility in how it can be deployed as well.
