### ISSUE TITLE
Namespaces doubt

### ISSUE THREAD

**Issue by jangel97** [CrunchyData/postgres-operator#1425]
Good morning, 

After checking the documentation, I don't see a very clear way to reconfigure the operator. For instance, I would like to deploy Crunchy clutsers in existing OpenShift namespaces, so then I have to create (serviceaccounts, roles, rolebindings) for each project. Another possibility would be to uninstall the operator and fill the variable namespace of the ansible inventory with all the existing namespaces I would like to use. Is there any way to do this without uninstalling the operator?

**Comment by jkatz** [comment]
You can use one of the installers. This is all documented here:

[Installation](https://access.crunchydata.com/documentation/postgres-operator/latest/installation/)

You can quickly get started using the [Operator quickstart](https://access.crunchydata.com/documentation/postgres-operator/latest/quickstart/), which can deploy the PostgreSQL Operator

There is also a section on [namespace management](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/namespace/) and since the 4.1 release, you have the ability to dynamically add and remove namespaces from the Operator:

- [`pgo create namespace`](https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/reference/pgo_create_namespace/)
- [`pgo delete namespace`](https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/reference/pgo_delete_namespace/)

I encourage you to thoroughly read through the documentation, the information is generally available in there. If there is something that is unclear in it, we can revise it.
