### ISSUE TITLE
[pgo 4.2.2] backrest pod eating all the memory in some situation

### ISSUE THREAD

**Issue by jose-joye** [CrunchyData/postgres-operator#1453]
Hello,
Recently we had 2 of our backrest pods that have eaten all our server memory.
One of the has taken up to 200 GB of RAM :-)

It is currently hard to say what was the situation that has caused the issue. We have tried to reproduced it but for now we did not succeed.

In order to prevent this to further occur, we want to set a request and a limit memory in the deployment for the backrest.

My questions are the following:

1. To what I have seen, it seems that the backrest pod needs at most 120 MB of Memory. Will it be ok if we set the requested value to 150 MB and the limit to 300 MB?
2. We also want to change the modify the template file used by pgo to create the backrest deployment. We have found 2 templates:

      - postgres-operator/conf/postgres-operator/pgo-backrest-repo-template.json
      - postgres-operator/ansible/roles/pgo-operator/files/pgo-configs/pgo-backrest-repo-template.json

       Which one do we need to modify?
3. It may make sense to also add this limits to the template in the original repository?
      Do you want me to create a pull request?

Thanks,
José

**Comment by jkatz** [comment]
@jose-joye Please review #1391 as this will help with some of what you are asking. (#1443 and #1428 are relateD).

My preference would be to _not_ PR the changes given as of 4.3 it's configurable :smile: 

However, this raises a good question about limits.  We've been doing a lot of research on this for a variety of reasons because of the observed behavior described in #1391. In 4.3, we're supporting memory requests and cpu requests+limits.

I'm going to do some research around adding the limit to pgBackRest (and pgBouncer). If we're following the Kubernetes guidelines for getting a [guaranteed QoS](https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/#create-a-pod-that-gets-assigned-a-qos-class-of-guaranteed) we'd want to set request the same as limit -- this does not prevent a process from within the Pod from being killed, but perhaps that is OK for pgBackRest + pgBouncer (this is not OK for PostgreSQL :wink:). That said, I'd rather do something that at least gets the better `oom_score_adj` vs. having the range.

Let me talk to some of the pgBackRest folks to get their thoughts and I'll circle back.

**Comment by dwsteele** [comment]
> One of them has taken up to 200 GB

That's a lot of memory! I'm not sure what could cause that much memory usage unless there is a bug or some other process using it up. Please let us know (https://github.com/pgbackrest/pgbackrest/issues) if you are able to reproduce.

Memory usage in pgBackRest is a function of `buffer-size`, `process-max`, the selected features (e.g. compression, encryption, etc.), and how may files are in the backup. So if you set the memory limit too tightly and then increase `process-max` or create many more tables you may cause problems.

The easiest way to save memory is to reduce `buffer-size`, which currently defaults to 4mb. Each process will use N number of buffers depending on the selected features. The current `buffer-size` was optimal for the old Perl version but our new benchmarks indicate that the pure C version does fine with smaller buffers. We're planning to reduce `buffer-size` in the next version based on our new benchmarks, but you can safely set it down to `1mb` without impacting performance if you want to save memory.

**Comment by jose-joye** [comment]
@jkatz & @dwsteele 
Thanks a lot for the answer!
I will have a deep look at them 

I have been able to reproduce the issue the following way :-)  :

In fact, I have a large cluster (1.5 TB of data).
I perform a scale --> during the scale the memory needed by the backrest went up to 200 GB.

José

**Comment by jose-joye** [comment]
For now, we decided not to set a memory limitation. In fact, since we do not fully understand the reason, we prefer to raise an alarm when the container uses more than 600 MB of memory.
This will allow us to better understand the cause of this issue.

We use the following metric for for the alarm:

`container_memory_working_set_bytes{pod_name=~".*backrest-shared-repo.*",container_name!~"POD"} > (600 * 1024 *1024)`


José
