### ISSUE TITLE
Documentation issues in operator hub listing

### ISSUE THREAD

**Issue by ctron** [CrunchyData/postgres-operator#1464]
**Describe the bug**

There are a number of documentation issues in the getting started information of the operator hub listing:

* > Install the bootstrap credentials:
  > ~~~
  > $PGOROOT/deploy/install-bootstrap-creds.sh
  > ~~~
  This doesn't work, as the script expects the `PGO_CMD` variable to be set, which at this point isn't.
  
  I would suggest to:
    * Add `set -e` to all scripts. As this script simply continues and continues failing.
    * Check if the `PGO_CMD` variable is set, and maybe use a reasonable default like `kubectl`. Or do a `which` for both `kubectl` and `oc`.

* > ### Service
  >
  > ~~~
  > oc expose deployment -n pgo postgres-operator --type=LoadBalancer
  > ~~~
  > 
  > For the pgo client to communicate with the operator, it needs to know where to connect. Export the service URL as `PGO_APISERVER_URL` in the shell.
  >
  > ~~~
  > export PGO_APISERVER_URL=https://<url of exposed service>:8443
  > ~~~
  
  This misses the step wiring up the load balancer.
  
  I would suggest to do the following instead:
    ~~~
    oc -n pgo expose deployment postgres-operator
    oc -n pgo create route passthrough --service=postgres-operator
    export PGO_APISERVER_URL=https://$(oc get route postgres-operator -ojsonpath="{.status.ingress[*].host})
    ~~~

* In the end, it still doesn't work:
  
  ~~~
  $ pgo status
  Error: empty namespace is not valid from pgo clients
  ~~~

**To Reproduce**
1. Following the readme

**Expected behavior**

It gives you a working setup.

**Please tell us about your environment:**

* Operating System: Fedora 31
* Where is this running: AWS
* Storage being used: AWS
* Container Image Tag: centos7-12.2-4.2.2
* PostgreSQL Version: ???
* Platform (Docker, Kubernetes, OpenShift): OpenShift
* Platform Version: 4.3

**Additional context**

**Comment by ctron** [comment]
I also think you can make it easier to use the certificates by using:

~~~
export PGO_CA_CERT=$PGOROOT/conf/postgres-operator/server.crt
export PGO_CLIENT_CERT=$PGOROOT/conf/postgres-operator/server.crt
export PGO_CLIENT_KEY=$PGOROOT/conf/postgres-operator/server.key
~~~

Rather than copying out the certs from the container.

**Comment by jkatz** [comment]
CC @cbandy to review.

We're working on our upcoming release and have begun the process to update our OLM deployment files.

Thanks!

**Comment by tirelibirefe** [comment]
@ctron you're completely right. I had to fix each of topics you mentioned in my installation . It's interesting they ignore so simple flashing faults.

**Comment by jkatz** [comment]
Hi @tirelibirefe,

Thanks for the interest in the PostgreSQL Operator on OperatorHub! I wanted to give you a bit of context around the evolution on it as it may help with your comments:

The PostgreSQL Operator was actually one of the first Operators on OperatorHub, which launched ~1 yr ago. Since then, quite a bit has changed, from Kuberenetes, OpenShift, OLM, and even the PostgreSQL Operator itself!

One of the challenges we had with OLM early on was how the PostgreSQL Operator relied on some additional Kubernetes objects to be set up, which was not supported in OLM at the time. This required those additional manual steps. However, OLM has recently improved support for it, and we are looking to take advantage of this.

Likewise, the PostgreSQL Operator has also evolved and is less reliant on some of the instructions that are presented in the OLM guide. Over the past few releases, we have placed great emphasis of ease of installation (in fact, in the 4.3 release which will be available, shortly, you can see that in some cases, the installation is as easy as [two `kubectl` commands](https://github.com/CrunchyData/postgres-operator#postgresql-operator-installation).

We support various installation methods to different environments, and we do our best to test and keep them all in sync, but rely on people to let us know what works and what does not. For example, the OLM CSV that we may have available that may work at one point may change over the course of a month and we need to adjust it. This seems to be the case with the things that @ctron and it looks like they are very easy fixes.

Finally, the beauty of an open source project is that it's very easy to offer up contributions! All of the [OLM source‘(https://github.com/CrunchyData/postgres-operator/tree/master/installers/olm) is available and is easy to PR against. When changes are accepted, we then upload it to OperatorHub.

Thanks!

**Comment by tirelibirefe** [comment]
@jkatz Hello Jonathan;
Sounds good. I would like to say "let's wait and see" but I am impatient.
Yesterday I tried 4.3.0-rc.1 both OLM and Ansible installation scenarios, there were issues.
OLM installation procedure installs the operator but pgo client couldn't have connected same like in previous version v4.2.2. I throwed towel and tried to follow Ansible installation procedure.
Ansible couldn't install even operator. The pod crashed all the time crashloopbackoff like the previous installation v4.2.2 .

I see you published 4.3.0 Release Candidate 2 3 hours ago, now I would like to attempt olm and Ansible installation scenarios but if you didn't change anything related existing problems, my installation attemptions fail again.

Couple of days ago I asked assistance for OLM installation / pgo client connectivity issue, nobody responded yet.

Do you mind to help me accomplish the installation of operator? We can start with pgo client connectivity issue. If we cannot figure it out, we can try to accomplish Ansible installation.

Thanks & Best Regards

**Comment by tirelibirefe** [comment]
I tried to install 4.3.0-rc.1 setup:
1) Ansible > images&&pgo client cannot be pulled. Probably paths are wrong in playbooks.
2)OLM > setup doesn't create svc.

I see v4.3 was published 18 minutes ago, now I will try it. I hope it works.

**Comment by Qeeq777** [comment]
https://www.qeeq.com/a/mcs18596
--

**Comment by jkatz** [comment]
Updates will be available on the next OperatorHub.io publications:

- [https://github.com/operator-framework/community-operators/pull/1832](https://github.com/operator-framework/community-operators/pull/1832)
- [https://github.com/operator-framework/community-operators/pull/1833](https://github.com/operator-framework/community-operators/pull/1833)
