### ISSUE TITLE
postgres-operator pod fail to run when disable TLS

### ISSUE THREAD

**Issue by zhubx007** [CrunchyData/postgres-operator#1504]
**Describe the bug**
I want to disable the TLS with following the doc [https://access.crunchydata.com/documentation/postgres-operator/4.3.0/configuration/tls/](tls)
But at last the postgres-operator pod fail to run, only 3/4 READY.

**To Reproduce**
1. get install yaml
`curl https://raw.githubusercontent.com/CrunchyData/postgres-operator/v4.3.0/installers/kubectl/postgres-operator.yml >postgres-operator.yml`
2. at the last of the install yaml file, add the following info:
```yaml
- name: PGO_DISABLE_TLS
  value: "true"
- name: PGO_APISERVER_PORT
  value: "8000"
- name: PGO_TLS_NO_VERIFY
  value: "false"
```
3. Run command 'kubectl create namespace pgo' to create namespace
4. Run command 'kubectl apply -f postgres-operator.yml' to begin installing

**Expected behavior**
Succeed to create postgres-operator 4/4 READY

**Screenshots**
![2020-05-09_175931.png](https://zbx-bucket.oss-cn-hongkong.aliyuncs.com/2020-05-09_175931.png)

**Please tell us about your environment:**

* Operating System: CentOS 7
* Where is this running: Local
* Storage being used (NFS, Hostpath, Gluster, etc): NFS
* Container Image Tag: v4.3.0
* PostgreSQL Version: 12.2
* Platform (Docker, Kubernetes, OpenShift): OpenShift
* Platform Version: openshift v3.11.0+5abc673-231-dirty

**Comment by jkatz** [comment]
It appears the issue is here:

https://github.com/jkatz/postgres-operator/blame/master/deploy/deployment.json#L39;L48
https://github.com/jkatz/postgres-operator/blob/master/installers/ansible/roles/pgo-operator/templates/deployment.json.j2#L41;L50

The readiness/liveness checks are being forced over HTTPS which, if TLS is disabled, is going to crash and burn.

You can hot fix this in your Kubernetes by editing the Operator deployment file, and switching `scheme` from `HTTPS` to `HTTP` in the two instances it appears. You can do this with `kubectl edit deployment -n pgo postgres-operator`

Note that if you set `PGO_DISABLE_TLS` to `true` you will also have to set `PGO_TLS_NO_VERIFY` to `true` as well.

**Comment by zhubx007** [comment]
Great~
Thanks for your reply. It is very useful for me.
Looking forward to the new images to fix the issue :)
