### ISSUE TITLE
Failing Create Cluster RBAC Task

### ISSUE THREAD

**Issue by Fpanebianco** [CrunchyData/postgres-operator#1532]
TASK [pgo-operator : Create Cluster RBAC (namespace_mode 'dynamic')] **************************************************************************************************************************fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["oc", "create", "-f", "/root/.pgo/pgo/output/cluster-rbac.yaml"], "delta": "0:00:00.956027", "end": "2020-05-15 11:29:12.521585", "msg": "non-zero return code", "rc": 1, "start": "2020-05-15 11:29:11.565558", "stderr": "The ClusterRoleBinding \"pgo-cluster-role\" is invalid: subjects[0].apiGroup: Unsupported value: \"rbac.authorization.k8s.io\": supported values: \"\"", "stderr_lines": ["The ClusterRoleBinding \"pgo-cluster-role\" is invalid: subjects[0].apiGroup: Unsupported value: \"rbac.authorization.k8s.io\": supported values: \"\""], "stdout": "clusterrole \"pgo-cluster-role\" created", "stdout_lines": ["clusterrole \"pgo-cluster-role\" created"]}

**To Reproduce**
Running ansible-playbook -i inventory --tags=install main.yml
Failing on Create Cluster RBAC (namespace_mode 'dynamic') stage
* Operating System:
Deploying into Openshift

**Comment by jkatz** [comment]
This is fixed in #1527 which will be committed shortly.

It appears you are using the Ansible installer off of `master`. While we do our best to keep things stable on the `master` branch, the code on `master` represents unreleased code. It's better to check out the exact version of the Operator you want to deploy, e.g.

```
git checkout v4.3.0
```

for 4.3.0.
