### ISSUE TITLE
postgres-operator 4.3.0 namespace management

### ISSUE THREAD

**Issue by dadez** [CrunchyData/postgres-operator#1552]
**What is the motivation or use case for the feature?**

In the namespaces where we deploy pgclusters, there are also other servies, ie: minio, kafka, ...
We want allow the operator to "partially" manage the namespace (update, watch, ..) but not create or delete them.
```bash
$ rakkess --sa pgo:postgres-operator --verbs get,list,watch,update,create,delete | grep namespace
namespaces                                                    ✔    ✔     ✔      ✔       ✖       ✖
```

**Describe the solution you'd like**
It would be nice to have a between Dynamic and Read only Operating mode where we could manage only existing namespaces.

**Describe any alternatives you've considered**
Until 4.3.0 we was working with the permissions, omitting the perms `createNamespace` and `deleteNamespace`, 
calling then 
```bash
$ pgo update namespace cfae-david-1
Error: Method POST for URL /namespaceupdate is not allowed in current the Operator install: 405
```
does not work anymore as you are expecting the operator to  have all the following roles (verbs) in https://github.com/CrunchyData/postgres-operator/blob/v4.3.0/ns/nslogic.go#L141

```
"namespaces":      {"get", "list", "watch", "create", "update", "delete"},
"serviceaccounts": {"get", "create", "delete"},
"roles":        {"get", "create", "delete", "bind", "escalate"},
"rolebindings": {"get", "create", "delete"},
```

**Please tell us about your environment:**

* Operating System:
* Where is this running: Local
* Storage being used : NFS
* Container Image Tag: centos7-11.7-4.3.0
* PostgreSQL Version: 11.7
* Platform: Kubernetes
* Platform Version: 1.10.11

**Comment by andrewlecuyer** [comment]
@dadez there are some new features in the `v4.3.1` release that should fit the use case you described.  Specifically, it is now possible to assign the Operator the privileges it requires to manage RBAC within a target namespace by assigning the Operator the proper privs within that namespace itself.  Therefore, you no longer need to assign the Operator a ClusterRole to manage RBAC within a target namespace - this can instead be done using only local namespace privs.  This means you can limit the namespace privs assigned to the Operator to `get`, `list` and `watch`, but still get the ability to update RBAC within a target namespace.  And since this now only requires privileges to be assigned to the Operator at the local namespace level, this can be leveraged even when using the `readonly` and `disabled` namespace modes.

To leverage this feature, you'll want to ensure any target namespace has the RBAC defined in the new [local-namespace-rbac.yaml file](https://github.com/CrunchyData/postgres-operator/blob/v4.3.1/deploy/local-namespace-rbac.yaml).  And if you are installing via the `kubectl`, Ansible or Bash methods, you can also have the installer create the RBAC in this file (`local-namespace-rbac.yaml`) when creating any target namespaces.  This is specifically done using one of the following depending on your install method:

- **kubectl**: `DYNAMIC_RBAC="true"`
- **Ansible**: `dynamic_rbac='true'`
- **Bash**: `PGO_DYNAMIC_RBAC=true`

As for the `pgo update namespace` command, this will still not be available for use when in a `readonly` namespace operating mode since that command also updates the namespace itself (specifically it's labels), and therefore still requires a cluster role.  However, this command should no longer be needed due to the RBAC reconciliation logic that is now baked into the Operator.  Specifically, the Operator will now attempt to reconcile the RBAC for any target namespace it is managing at a regular interval (60 seconds by default) if it detects that is it has the proper privileges to do so.  

Therefore, if the Operator detects that it has the privs defined in the `local-namespace-rbac.yaml` file discussed above in a target namespace, it will attempt to either create any missing RBAC (ServiceAccounts, Roles and RoleBindings), or fix any RBAC that is invalid.  This means that even when using a `readonly` mode, the Operator can still create and manage RBAC (this simply occurs behind the scenes at a regualr interval).  This therefore also means you can still create namespaces outside of the Operator and assign them the proper labels, and the Operator will then start reconciling RBAC for that namespace once it detects that new namespace and starts managing it.

**Comment by dadez** [comment]
Hi @andrewlecuyer, thanks for the feedback, and sorry for the delay.

We use the pgo-osb servicebroker for allow our customers to order pgclusters. 
If I understand you right, we could let the pgo-osb to 
- create the role and rolebinding as defined in `local-namespace-rbac.yaml` 
- label the namespaces

we don't need to upgrade the operator installation for each new watched namespace ?

If yes, the environment variable `NAMESPACE` defined in the operator container will not be upgraded, is this a problem ?

**Comment by dadez** [comment]
In both pgo 4.3.1 and 4.3.2 versions, 
with the ansible installation, by setting the `namespace_mode=readonly` and `dynamic_rbac=true`, the installation or update will attempt to create the namespaces.
see: [namespace.yml](https://github.com/CrunchyData/postgres-operator/blob/v4.3.2/installers/ansible/roles/pgo-operator/tasks/namespace.yml#L23)

In that case, we should allow the operator to create namespaces, so this is not realy readonly in my opinion.

### Workaround
I have now installed the operator in version 4.3.2, with `namespace_mode=readonly` and `dynamic_rbac=false`.

- Labeling a namespace as would the [add-targeted-namespace-dynamic-rbac.sh](https://github.com/CrunchyData/postgres-operator/blob/v4.3.2/deploy/add-targeted-namespace-dynamic-rbac.sh) 
- adding the role and rolebindng as defined in [local-namespace-rbac.yaml](https://github.com/CrunchyData/postgres-operator/blob/v4.3.2/deploy/local-namespace-rbac.yaml)

causes the operator to starts the RBAC reconciliation and all objects are created.
We can map this operations into our pgo-osb.
