### ISSUE TITLE
Copy to program commands

### ISSUE THREAD

**Issue by Witcher1994** [CrunchyData/postgres-operator#1598]
**Describe the bug**
When I tried to execute command "copy (select 1) to program 'mkdir --mode=777 -p /tablespaces/fasthdd/fasthdd/test1' " only master executed that query successfully, but all replicas exited with error:

2020-06-04 07:08:08,962 INFO: restarting after failure in progress
/tmp:5432 - rejecting connections
/tmp:5432 - rejecting connections
/tmp:5432 - rejecting connections
/tmp:5432 - rejecting connections
/tmp:5432 - rejecting connections
WARNING:  terminating connection because of crash of another server process
DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
HINT:  In a moment you should be able to reconnect to the database and repeat your command.
/tmp:5432 - no response
2020-06-04 07:08:14,733 WARNING: Postgresql is not running.

wal_level was set to logical

**To Reproduce**
1. Create pg cluster with at least 1 replica.
2. Execute copy query on master

**Please tell us about your environment:**

* Operating System:
* Where is this running: AWS EKS
* Storage being used EFS, EBS
* Container Image Tag: v4.3.0
* PostgreSQL Version: 12
* Platform Kubernetes
* Platform Version: 1.15

**Comment by jkatz** [comment]
I attempted to run this and did not run into any issues. Overall, the behavior sounds correct.

`COPY .. PROGRAM` only executes on a single instance, so if you execute it on the primary, it only executes on the primary. Similarly, if you execute it on the replica, it only executes on the replica. I have gone ahead and verified this.

Additionally, there's no reason to be creating directories, particularly those with world writeable privileges, in the tablespace directory. The tablespace directory is an extension of the "pgdata" directory, i.e. it behaves just like the PostgreSQL filesystem. It's not different than trying to do that within the "pgdata" directory, and you are likely not going to get the results that you desire.

Lastly, the error you encountered is not caused by the COPY command and is mostly likely related to the environment you are running in. Make sure you have enough memory in your environment available for running your PostgreSQL instances.
