### ISSUE TITLE
PGO client not displaying logs and results for operations

### ISSUE THREAD

**Issue by asoltesz** [CrunchyData/postgres-operator#1604]
The pgo command line client doesn't seem to provide any tracking for the operations it starts. It starts the operation and displays what it starts but then the user/administrator is left without the actual result and has to manually check for problems and issues.

For example: when creating a cluster, I would expect logs displayed on the console and an actual result for the operation when the cluster is successfully started up with all of its constituent parts (primary, standby replicas, pgbackrest stanza ...etc everything). If there is a problem (like failed stanza creation), I would expect it to be logged on the console.

Is there any way to get logging and proper result codes from the pgo client? 

I understand that I can manually track the workflows but that is also very limited in logging and also doesn't provide actual result codes. (at least I see nothing from the events of the failed restore operation I have tried the last time).

**Comment by andrewlecuyer** [comment]
I recommend checking out the eventing subsystem, which provides insight into various activities and events as they occur within the Operator:

https://access.crunchydata.com/documentation/postgres-operator/4.3.2/architecture/eventing/

Please note that the `pgo` CLI is only responsible for creating various Kubernetes resources, e.g. a `pgcluster` Custom Resource when creating a new cluster, and considers the successful creation of this resource a success.  From there the rest of the cluster creation process is asynchronous by nature, since there are no guarantees as to when when Kubernetes will actually detect and process the resource.  The eventing system therefore allows you to subscribe to various topics in order to gain additional visibility into various actions that occur asynchronously as various resources are created and processed by the Operator.

**Comment by asoltesz** [comment]
Thanks, I am aware of the events and will try to utilize it.

I argue that the pgo CLI client should have the responsibility of not only initiating the necessary Kubernetes actions but also tracking and reporting their completion. It doesn't really matter that these are async in nature, the client can poll the statuses of the Kubernetes objects until the desired state is achieved. After a predefined timeout or when it sees that the workflow is not possible to complete anymore, it stops polling and returns with the error. It should also try to collect as much logs/events to the console output as possible.

There are many notable examples of CLI clients working like this around Kubernetes. Maybe the best example is Rancher's RKE.

The current way of things puts a pretty big burden on the user/administrator of PGO. When I start a major process (say "pgo backup"), I have to manually check for the completion of the process often requiring issuing multiple kubectl commands, copying/pasting workflow IDs...etc. If anything fails, I have to manually query the pod names and collect logs from the pods. 

Since the client is the main interface between the user and PGO, this makes working with PGO much less pleasant than it needs to be. There is a definite, percievable resistance.

Also, without this, it is extremely hard to automate anything around PGO because the user needs to implement all of the polling and checks of the desired state that should have been done by the pgo cli client. Implementing these are non-trivial even with a strong programming background.

**Comment by rubin55** [comment]
I just noticed this issue, I actually just created #1825 essentially because of what @asoltesz highlights; it's definitely a significant burden on our side and I would be much helped by anything that could wait or otherwise foreground the command/job so I could, say, check the return code to see if something was succesful or not.

**Comment by ValClarkson** [comment]
Hi @asoltesz,

With the release of [PGO v5](https://access.crunchydata.com/documentation/postgres-operator/latest/), we are now re-evaluating various GitHub issues, feature requests, etc. from previous PGO v4 releases. More specifically, in order to properly prioritize the features and fixes needed by our end-users for upcoming PGO v5 releases, we are now attempting to identify which PGO v4 issues, use-cases, and enhancement requests are still valid (especially in the context of PGO v5).

Therefore, please let us know if you are still interested in having the enhancement described in this issue implemented in PGO v5.

If so, you can either respond to this issue directly to ensure it remains open, or you can close this issue and submit a new one for PGO v5 (this would also be a great opportunity to include any updated details, context, or any other information relevant to your issue). Otherwise, we will be closing this issue in the next 30 days.

If you are still running PGO v4, we recommend that you [upgrade to PGO v5](https://access.crunchydata.com/documentation/postgres-operator/latest/guides/v4tov5/) as soon as possible to ensure you have the latest PGO features and functionality.
