### ISSUE TITLE
Continual ServiceAccount  reconciliation

### ISSUE THREAD

**Issue by aceeric** [CrunchyData/postgres-operator#1744]
I'm following instructions here: https://access.crunchydata.com/documentation/postgres-operator/latest/custom-resources/

I have the PGO operator running. Note - I installed it into a different namespace, rather than "pgo". Every minute, the logs have:
```
time="2020-07-29T14:32:44Z" level=debug msg="ServiceAccout pgo-default in namespace backing is invalid and will now be reconciled" func="internal/ns.ReconcileServiceAccount()" file="internal/ns/nslogic.go:405" version=4.4.0
time="2020-07-29T14:32:44Z" level=debug msg="ServiceAccout pgo-target in namespace backing is invalid and will now be reconciled" func="internal/ns.ReconcileServiceAccount()" file="internal/ns/nslogic.go:405" version=4.4.0
time="2020-07-29T14:32:44Z" level=debug msg="ServiceAccout pgo-backrest in namespace backing is invalid and will now be reconciled" func="internal/ns.ReconcileServiceAccount()" file="internal/ns/nslogic.go:405" version=4.4.0
time="2020-07-29T14:32:44Z" level=debug msg="ServiceAccout pgo-pg in namespace backing is invalid and will now be reconciled" func="internal/ns.ReconcileServiceAccount()" file="internal/ns/nslogic.go:405" version=4.4.0
```
Is this a known issue? Do you suppose the operator doesn't expect to be running in a namespace other than "pgo"?

**Comment by jkatz** [comment]
The Operator can exist in namespaces not named `pgo` -- this is configured at installation time.

Those messages are debug messages, they occur at a refresh interval of every 60 seconds to check if the permissions are set. However, there are no error messages coming up, so the reconciliation appears to be successful, but perhaps something else is changing the Service Accounts in the environment.

**Comment by aceeric** [comment]
I'm running Code Ready Containers:
```
$ ./crc version
CodeReady Containers version: 1.13.0+8070bae
OpenShift version: 4.5.1 (embedded in binary)
```
I don't have anything that would be modifying these service accounts. If you run: `watch 'kubectl get sa -ocustom-columns=NAME:.metadata.name,RESVER:.metadata.resourceVersion'` you will see the resource version change on at least some of the "pgo-" service accounts - so they're definitely being modified.

I doubt it's a big deal but it looks to me like the operator may doing work it doesn't need to do.

**Comment by jkatz** [comment]
So this is known to happen in OpenShift (and by extension CRC - which I am a huge fan of CRC for testing).

OpenShift does its own things to set up the ServiceAccounts and is modifying them. With `RECONCILE_RBAC` set to `true`, the Operator then tries to [reconcile its RBAC](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/namespace/#rbac-reconciliation) to ensure it has the appropriate permissions. So there is back-and-forth between the Operator and OpenShift.

The good news is that it's all being set correctly, i.e. because the only log entries are around the Service Accounts. If there were permission failures, we could be see the Operator reporting on other Kubernetes objects.

Anyway, I do recommend this section of the documentation which talks about permissions and reconciliation:

[https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/namespace/#rbac-reconciliation](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/namespace/#rbac-reconciliation)

If you have your RBAC setup and are not doing any modifications to the Operator managed objects, you can set `RECONCILE_RBAC` to `FALSE`.

**Comment by jkatz** [comment]
Oops, forgot to mention that you can also disable `DEBUG` logging as an option as well. 😄

**Comment by aceeric** [comment]
Wel.. I started from https://access.crunchydata.com/documentation/postgres-operator/latest/quickstart/. That tells you to get: https://raw.githubusercontent.com/CrunchyData/postgres-operator/v4.4.0/installers/kubectl/postgres-operator.yml

The only things I patched in that yaml file were in the `pgo-deployer-cm` config map:
1. There are two hard-coded namespaces `pgo` that I patched to my `backing` namespace
2. There is a `disable_fsgroup: "false"` which causes all crunchy clusters to fail to create in OpenShift - so changed that to `disable_fsgroup: "true"`

After applying the patched manifest, I see a new cluster role `pgo-cluster-role` - presumably created by the operator, with:
```
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - get
  - create
  - update
  - delete
```
And in the `pgo-deployer-cm` config map I see: `namespace_mode: "dynamic"`. So the mode and the RBAC match what is in the article you forwarded for the dynamic namespace model. It would appear then that - "out of the "box" with this YAML - there are two settings that are not accommodating of OpenShift: one being the `fsgroup` setting, and the other being the RBAC contention that causes the continual updating of the service accounts.
