### ISSUE TITLE
How to scale postgres operator itself for high availability?

### ISSUE THREAD

**Issue by junaid-a10** [CrunchyData/postgres-operator#1808]
**Which example are you working with?** 
Postgres Operator 4.3.2

**What is the current behavior?**
If the node on which Postgres Operator is running goes down then the failover doesn't happens.

**What is the expected behavior?**
Postgres Operator and PGO client to run with high availability

**Other information** (e.g. detailed explanation, related issues,  etc)
I have a multi node k8s cluster with master and postgres operator running on one node say n1 and 2 replicas running on nodes n2 and n3 respectively. If n1 goes down then ideally failover should happen and replica should be promoted to master but since postgres operator goes down as well so no replica is promoted.

How can I scale postgres operator and pgo-client for high availability to avoid this scenario?
I can see that both postgres-operator and pgo-client are deployed as replica-sets. Can I simply set their desired state to say 2 or 3 and expect it to work fine?
Moreover, how to set node affinity for these workloads?

**Please tell us about your environment:**

* Operating System: CentOS 7.7.1908 / CentOS 7.8.2003
* Where is this running ( Local , Cloud Provider): Local
* Storage being used (NFS, Hostpath, Gluster, etc): NFS
* Container Image Tag: crunchydata/pgo-apiserver:centos7-4.3.2
* PostgreSQL Version: 12.3
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version: v1.14.1 / v1.18

**Comment by jkatz** [comment]
Please review the [high availability](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/high-availability/) architecture documentation:

[https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/high-availability/](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/high-availability/)

The PostgreSQL clusters can and do fail over in a downtime scenario even if the PostgreSQL Operator Pod is unavailable. The replica may not be able to heal effectively if the Operator is down, but your primary will be promoted and available.

If the cause of the downtime is due to the Kubernetes cluster in general (e.g. the Kubernetes API is unavailable), you may have availability issues, though this is again explained in the documentation.
