### ISSUE TITLE
Add SHA-256 checksums for downloadable artifacts

### ISSUE THREAD

**Issue by rubin55** [CrunchyData/postgres-operator#1815]
**What is the motivation or use case for the feature? **
Currently the assets available for download don't have a checksum file (*.asc) associated with them. Hence, downloaded binaries cannot be verified.

**Describe the solution you'd like**
Provide SHA-256 checksums for:
  * pgo
  * pgo-mac
  * pgo.exe
  * postgres-operator.*.tar.gz

For each of the above, provide a $file.asc which contains a SHA-256 checksum.

**Comment by ValClarkson** [comment]
Hi @rubin55!

With the release of [PGO v5](https://access.crunchydata.com/documentation/postgres-operator/latest/), we are now re-evaluating various GitHub issues, feature requests, etc. from previous PGO v4 releases.  More specifically, in order to properly prioritize the features and fixes needed by our end-users for upcoming PGO v5 releases, we are now attempting to identify which PGO v4 issues, use cases and enhancement requests are still valid (especially in the context of PGO v5). 

Therefore, please let us know if you are still interested in having the enhancement described in this issue implemented in PGO v5 

If so, you can either respond to this issue directly to ensure it remains open, or you can close this issue and submit a new one for PGO v5 (this would also be a great opportunity to include any updated details, context, or any other information relevant to your issue).  Otherwise, we will be closing this issue in the next 30 days.

If you are still running PGO v4, we recommend that you [upgrade to PGO v5](https://access.crunchydata.com/documentation/postgres-operator/latest/guides/v4tov5/) as soon as possible to ensure you have the latest PGO features and functionality.
