### ISSUE TITLE
Metrics not available in pgbadger with 4.3.2

### ISSUE THREAD

**Issue by avanichy25** [CrunchyData/postgres-operator#1854]
**Describe the bug**
The metric is not available with pgbadger in 4.3.2 . Attached the error logs of the collector pod. 
```
at Sep  5 03:40:08 UTC 2020 INFO: Setting credentials for collect PG user using file system
Sat Sep  5 03:40:08 UTC 2020 INFO: Waiting for PostgreSQL to be ready..
127.0.0.1:5432 - no response
127.0.0.1:5432 - no response
127.0.0.1:5432 - accepting connections
Sat Sep  5 03:40:12 UTC 2020 INFO: Checking if PostgreSQL is accepting queries..
psql: error: could not connect to server: FATAL:  password authentication failed for user "ccp_monitoring"
             now
------------------------------
 2020-09-05 03:40:14.81959+00
(1 row)
Sat Sep  5 03:40:14 UTC 2020 INFO: No custom queries detected. Applying default configuration..
Sat Sep  5 03:40:15 UTC 2020 INFO: Starting postgres-exporter..
time="2020-09-05T03:40:15Z" level=info msg="Established new database connection to \"127.0.0.1:5432\"." source="postgres_exporter.go:814"
time="2020-09-05T03:40:15Z" level=info msg="Semantic Version Changed on \"127.0.0.1:5432\": 0.0.0 -> 12.3.0" source="postgres_exporter.go:1335"
time="2020-09-05T03:40:15Z" level=info msg="Starting Server: :9187" source="postgres_exporter.go:1576"
````
**To Reproduce**
1. install 4.3.2 operator
2. create cluster using below command
```
pgo create cluster test --replica-count=2 --sync-replication --cpu-limit 1 --cpu 500m --memory-limit 2Gi --memory 512Mi -n pgo --pgbadger --metrics --pgbouncer --pgbouncer-replicas 2 --pgbouncer-cpu-limit 2 --pgbouncer-cpu 1 --pgbouncer-memory-limit 512Mi --pgbouncer-memory 256Mi
```
**Expected behavior**

**Screenshots**

**Please tell us about your environment:**

* Operating System: 
* Where is this running ( Local, Cloud Provider) Azure
* Storage being used (NFS, Hostpath, Gluster, etc): Default
* Container Image Tag: 4.3.2
* PostgreSQL Version:  4.3.2
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version: 1.15

**Additional context**

**Comment by jkatz** [comment]
That looks like normal operation to me. The `ccp_monitoring` user cannot initially connect because the account is not created. Once it is created, it successfully executes a query that returns the current time (possible changed to `SELECT 1;` in the upcoming release), and begins scraping data.

Keep in mind, that's for the metric collection system (which is getting a [major overhaul in Operator 4.5](https://crunchydata.github.io/postgres-operator/latest/architecture/monitoring/). pgBadger runs as its own sidecar, and, pgBadger runs on _PostgreSQL logs_ -- you need to ensure your logs are being stored in a directory (typically `/pgdata/<clusterName>/pg_log) and that you are logging somewhere between some and all query statements (`log_statement = all`).

The metrics container provides an exporter endpoint for Prometheus to scrape the metrics, and subsequently be visualized in Grafana. This is separate from pgBadger. And as mentioned, the way this works is changed (read "improved") in the upcoming Operator 4.5 release. Preview here:

[https://crunchydata.github.io/postgres-operator/latest/architecture/monitoring/](https://crunchydata.github.io/postgres-operator/latest/architecture/monitoring/)
