### ISSUE TITLE
Suggestions for Rollback

### ISSUE THREAD

**Issue by v3nturetheworld** [CrunchyData/postgres-operator#1864]
Hi,

I have a somewhat unusual use case requirement that after an upgrade there is a possibility to rollback all upgraded services via helm rollbacks. This includes rolling back to the previously deployed Crunchy Operator and Images version. As expected, doing a `pgo upgrade` with older images doesn't work out of the box, and since we use the Crunchy Installer Image with a custom helm chart to install the operator itself, there are a few more variables to deal with to make a graceful rollback work. 

My thoughts are that the most seamless way to enable rollback with Crunchy would be to clone the cluster prior to upgrading to a new version of crunchy, then when we upgrade the operator and cluster, there's the cloned cluster sticking around prior to the upgrade. When we rollback, we'd likely need to remove the cluster on the newer version, reinstall the operator, then **if possible**, ensure the operator on the older version detects and manages that cloned cluster. If this is even possible, what would it take to have the newly installed, older versioned operator detect the previously cloned cluster?

If that's not possible, another option would be to ensure the pgBackRest Backup that's created prior to an upgrade (or potentially even the post upgrade, pre-downgrade backup) is kept persistently (I believe this already happens), then tear down the existing cluster and treat the operator as a fresh install, then do a `pgo create cluster --from-backup`. 

If either of these ideas are crazy and not worth the effort to make work with the way the crunchy operator works, or if you have any suggestions on a better approach I'd appreciate any kind of thoughts on the topic.

**Comment by ValClarkson** [comment]
Hi @v3nturetheworld!

With the release of [PGO v5](https://access.crunchydata.com/documentation/postgres-operator/latest/), we are now re-evaluating various GitHub issues, feature requests, etc. from previous PGO v4 releases.  More specifically, in order to properly prioritize the features and fixes needed by our end-users for upcoming PGO v5 releases, we are now attempting to identify which PGO v4 issues, use-cases, and enhancement requests are still valid (especially in the context of PGO v5). 

Therefore, please let us know if you are still interested in having the enhancement described in this issue implemented in PGO v5 

If so, you can either respond to this issue directly to ensure it remains open, or you can close this issue and submit a new one for PGO v5 (this would also be a great opportunity to include any updated details, context or any other information relevant to your issue).  Otherwise, we will be closing this issue in the next 30 days.

If you are still running PGO v4, we recommend that you [upgrade to PGO v5](https://access.crunchydata.com/documentation/postgres-operator/latest/guides/v4tov5/) as soon as possible to ensure you have the latest PGO features and functionality.
