### ISSUE TITLE
Are there a way to create new cluster from a locally stored dump?

### ISSUE THREAD

**Issue by IJOL** [CrunchyData/postgres-operator#1891]

**Comment by jkatz** [comment]
I need more details to provide an appropriate answer.

- Is the backup taking as part of a physical backup (pgBackRest) or using pg_dump?
- How as the backup taken? Was it taken by the Operator or indepently.
- "locally stored dump" can mean a lot of things. Where is the backup file residing? Is it in a PVC? Is it on your computer? Is it in an object storage system?

**Comment by IJOL** [comment]
What I mean, is we have a locally , and I refer to 9gb file where we
operate the cluster, i can up it wherever is need to do the job, but i now
i have it stored outside the k8s cluster, i can up it in s3 inside a pvc,
something we can automate a bit..


Saludos,
--------------------------------------------
Ignacio J.Ortega
skype:ignacioj.ortega

**Comment by jkatz** [comment]
This still doesn't answer the question in terms of how the backup was taken. Is it a physical backup (pgBackRest) or is it with pg_dump?

**Comment by IJOL** [comment]
Yep, sorry, is a regular pgdump one, but i can get the pgdata
directory itself if useful,

Saludos,
--------------------------------------------
Ignacio J.Ortega
skype:ignacioj.ortega

**Comment by IJOL** [comment]
To be more precise, we are on the verge of moving some big databases from
our old system to our fancy new k8s cluster with pgo for the postgres dbs,
we can use our app to restore a backup but hat implies uploading some
really bug files by the browser, so we can get a pg_basebackup or a pg_dump
p_restore or whatever, I was looking for a way to preload the DB before
starting the a thus alleviate the task of translation our dbm we have seen
the pgo load command, what is  supposed to do? doc are very brief, we  have
tried also to get a logical  backup, but after pgo bacup type=pgdump, we
didn't found where it's stored...

Of course I've understand that there the simple option  of give a nodeport
to the primary and di a pg_dump | psql into the new server, could this be
possible?


Saludos,
--------------------------------------------
Ignacio J.Ortega
skype:ignacioj.ortega

**Comment by jkatz** [comment]
@IJOL Thanks, that description is very helpful :smile:

Large data migrations is definitely a complicated topic in any system, let alone when using K8S. I should probably ask a follow-up question in terms of how much downtime you're afforded, if any. However, even without knowing that, I can make a few suggestions, in order of complexity.

### pg_dumpall

This would be similar to using the [pg_dumpall method for upgrading](https://www.postgresql.org/docs/current/upgrading.html#UPGRADING-VIA-PGDUMPALL) though instead you are moving data.

First, to ensure that you do not lose any transactions, you would have to ensure no clients are connected to your old database.

After creating a new PostgreSQL database in the Operator, you would `kubectl exec` into your primary container and run:

`pg_dumpall <connection settings to remote database> | psql`

The advantage of this method is that it's simple to do, but it may not be the most efficient and if it gets interrupted during the transfer, you will have to start over.

You can always bring over your pg_dumpall dump, store it in a PVC, and manually mount that PVC to your PostgreSQL instance so the backup is at least closer.

### pg_basebackup

If you wanted to use pg_basebackup to bring the data in, you could set up a pg_basebackup job that writes the data to a PVC that matches the format of the cluster you want to create. So, if you cluster is named `hippo`, you will want your `pvc` to be named `hippo`.

Also note: do _not_ create your PostgreSQL cluster with the Operator yet.

First, manually create the PVC that you want to write the data to. Then, follow steps similar to setting up the [pg_basebackup](https://access.crunchydata.com/documentation/crunchy-postgres-containers/latest/examples/backup-restoration/pgbasebackup/) example found here:

[https://access.crunchydata.com/documentation/crunchy-postgres-containers/latest/examples/backup-restoration/pgbasebackup/](https://access.crunchydata.com/documentation/crunchy-postgres-containers/latest/examples/backup-restoration/pgbasebackup/)

Once the job completes, create a PostgreSQL cluster with the same name of your PVC, e.g.:

`pgo create cluster hippo`

This will create an Operator managed cluster using the data you've imported.

You do need to be cognizant about PostgreSQL major version when running pg_basebackup. Also similar to the pg_dump example, you will have to stop your applications from accessing your live cluster to ensure you have all your data available. However, this method would be faster than the `pg_dump` method as you will not have to rebuild all of your indexes, etc. (There are some more complex things you can do, but they are out of scope for this reply :wink:)

### pgBackRest

If you are sensitive to downtime, you will want to follow a method similar to setting up a [multi-Kubernetes Operator deployment](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/high-availability/multi-cluster-kubernetes/):

[https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/high-availability/multi-cluster-kubernetes/](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/high-availability/multi-cluster-kubernetes/)

However, instead of setting up two Operators, you would do the following:

- Create a pgBackRest repository for your existing cluster, in a place that's accessible via S3 or a S3 interface ensuring the names match the same patterns as the PostgreSQL Operator would expect. You can determine this by trying this out with the PostgreSQL Operator
- Within your Kubernetes cluster create a PostgreSQL cluster as a standby, restoring from the pgBackRest repository that you've created.

In this way, all the changes will stream over from your existing cluster, so you can limit downtime. The tradeoff is that this is the most complex way to set this up.

-------
There are other ways to migrate the data over too: this it not an exhaustive guide, but more as a way to get started.

Hope this helps!

**Comment by IJOL** [comment]
Ok, thanks, we commented that we are seasoned pg users, we actually were
asking for and how to say it, "integrated" way to start a cluster and in
the same operation load a dump, a SQL, or whatever... just as we did in our
images for docker swarm in the past, it seemed to us the logical way to do
it and wondered if that itch was scratched by someone else...


Saludos,
--------------------------------------------
Ignacio J.Ortega
skype:ignacioj.ortega
