### ISSUE TITLE
Queries about tablespace in postgres operator

### ISSUE THREAD

**Issue by kseswar** [CrunchyData/postgres-operator#1908]
** Which example are you working with? **
Currently tried using tablespace to spread data across multiple PVCs. We are trying to use many small PVCs, so we are using this feature tablespace.
We would want to understand few things about tablespace for implementing it.
we are planning to store db in multiple pvcs. ---> like tablespace
how backup , restore wil work for tablespace?
how to manage pvc size if its get full after sometime for tablespace?
is there any performance issue?

**Please tell us about your environment:**

Operating System: Linux based
Where is this running ( Local, Cloud Provider) - GCP GKE cluster
Storage being used (NFS, Hostpath, Gluster, etc):GCP PVC,
Container Image Tag: centos7-4.3.0 / centos7-12.2-4.3.0
PostgreSQL Version:12.2
Platform (Docker, Kubernetes, OpenShift): Kubernetes
Platform Version: 1.16.11-gke.5

**Comment by jkatz** [comment]
> how backup , restore wil work for tablespace?

This leverages [pgBackRest's support for tablespace backup/restore](https://pgbackrest.org/#features/tablespace-link-support).

In other words, it works just fine. Otherwise we would not have implemented it :wink:

> how to manage pvc size if its get full after sometime for tablespace?

I actually think the PostgreSQL [documentation on tablespaces provides the best introduction for this topic](https://www.postgresql.org/docs/current/manage-ag-tablespaces.html):

> Even though located outside the main PostgreSQL data directory, tablespaces are an integral part of the database cluster and cannot be treated as an autonomous collection of data files. They are dependent on metadata contained in the main data directory, and therefore cannot be attached to a different database cluster or backed up individually. Similarly, if you lose a tablespace (file deletion, disk failure, etc), the database cluster might become unreadable or unable to start. Placing a tablespace on a temporary file system like a RAM disk risks the reliability of the entire cluster.

In other words, treat a tablespace the same way you would treat the main PostgreSQL data directory: if it's unavailable, your system will be down.

In terms of resizing, you would follow the same methodology at this point as if you were resizing a data directory, a pgBackRest repository, or a WAL archive PVC. At some point, the PostgreSQL Operator will support an operation to help with the resize of a PVC, but that will be in a future release. For now, you will need to employ your own strategy for resizing.

is there any performance issue?

There's no way to answer this question without more information about your system, e.g.

- How much data are you storing on a tablespace?
- What is the quality of the storage?
- What are the data access patterns? What is the read/write ratio?
- How is the data structured? What does the schema look like? What indexes are being used?

Based on this, perhaps you see performance improvements, perhaps not. I don't know based on the information provided. One of the original use cases for tablespaces was to offload I/O workload from the main data directory onto a separate mount point, so if employed correctly, you can distribute the work.

However, let me focus in on the word "distribute": by increasing the number of tablespaces, you're increasing the number of potential failure points. Now, it may be an acceptable risk based on what you're trying to accomplish, but you will want to ensure have appropriate redundancy, understand how your underlying storage system works, and truly measure the tradeoffs that you have between using tablespaces or other systems.

That said, if you are going down this route, I do recommend running a version of the Operator later than 4.3.0, at least the latest patch release (4.3.3). There were  improvements made to the restore system in 4.4.0, with even more coming out in 4.5.0.
