### ISSUE TITLE
pg instance 4.5.0, what are the exporter Memory and cpu values to be set for a QoS of guaranted?

### ISSUE THREAD

**Issue by jose-joye** [CrunchyData/postgres-operator#1940]
Hello,

We try to have our cluster instances with a QoS of _guaranted_.
Do you know what will be the values we can set for the "exporter" container related to CPU and Memory (for V 4.5)?

Thanks a lot,
José

**Comment by jkatz** [comment]
You should just need to follow the guaranteed QoS guidelines:

[https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/#create-a-pod-that-gets-assigned-a-qos-class-of-guaranteed](https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/#create-a-pod-that-gets-assigned-a-qos-class-of-guaranteed)

I have not tested it out myself, but presumably those work, and the Operator exposes the flags/attributes to do so.

**Comment by jose-joye** [comment]
@jkatz, 
Thanks for the quick reply. 
We already touched a word about it for version 4.3 --> https://github.com/CrunchyData/postgres-operator/issues/1526
At that time you set for collect a value of 100mi for CPU and 24MB for the memory.

Do you think it is a good setting for the "exporter" container as well.

A side question: For 4.3, you strongly advised to have the QoS of the pg cluster set to "_guaranted_". Do you still have that in mind?

Thanks
José

**Comment by jkatz** [comment]
With little knowledge of your system and what you're deploying, it's very difficult to make specific recommendations over what you should be running as, and it also ventures into [production support](https://access.crunchydata.com/documentation/postgres-operator/latest/support/) territory.

I can offer up a few suggestions:

1. Via #1671 we discovered that if you are on PostgreSQL 11+ and have `jit = on` (which is the default in PostgreSQL 12), there is the potentially for a memory leak to arise in the query that is mentioned. You may want to either set `jit = off` for that specific query, or turn off JIT altogether in the cluster.

2. With the Guaranteed QoS, it seems that Kubernetes 1.19 fixes the issue that we were concerned about due to how cgroups v2 handles memory limits. As long as your memory growth is controlled, you _should_ be OK, though I will emphasize the word _should_ as well as the expression "do your own testing" :wink:
