### ISSUE TITLE
Change the preferre replication method in patroni

### ISSUE THREAD

**Issue by IJOL** [CrunchyData/postgres-operator#1952]
Hi, i found that using pgbackrest to create replicas is not doing well for us, is rather slow, and has problems when s3 is down, i would like to change the default patroni snippet to change order in this part:

		  create_replica_methods:
		  - pgbackrest
		  - basebackup

but i dont find where this part has his template.. where can i change that for every cluster in mi installlation?

**Comment by jkatz** [comment]
Why is it slow? Have you tried adjusting the pgBackRest configuration? The pgBackRest documentation has guides on the various settings you can tune here:

[https://pgbackrest.org/](https://pgbackrest.org/)

pgBackRest is designed to handle backups that are multi-terabytes. Additionally, the Postgres Operator allows you to choose having your backups stored to a local repository if you do not want to rely solely on S3.

The `create_replica_methods` setting is part of each local configuration. You can read more about customizing it here: [https://access.crunchydata.com/documentation/postgres-operator/latest/advanced/custom-configuration/](https://access.crunchydata.com/documentation/postgres-operator/latest/advanced/custom-configuration/).

That said, I would recommend tweaking your pgBackRest configuration parameters because restores from pgBackRest should outperform ones from `pg_basebackup` (and I am speaking to this from personal experience managing PostgreSQL clusters).

**Comment by IJOL** [comment]
Ok, thanks got the info, i will try and get back to you, we fund that in
some case, de replica lags for about 10 minutes until reach lag 0 sometimes
the lag grows unmanageable and the replica just stales sits above 16000 mb
of lag and doesn't advance, we didn't know why, but we just assume that the
primary is just ok, why we need to read all these wal logs ? , its just
faster to do a basebackup and just start over,

After 3 week in production use of crunchy operators, we found some things
very annoying that we will try to summarize in a next question.. one of the
more urgent is the above problem with very big wal logs and replicas stuck
reading , what?

Saludos,
--------------------------------------------
Ignacio J.Ortega
skype:ignacioj.ortega

**Comment by jkatz** [comment]
We're always welcome to feedback. For [production support](https://access.crunchydata.com/documentation/postgres-operator/latest/support/), please reach out to info@crunchydata.com
