### ISSUE TITLE
Setting pgbouncer parameters in users.txt and pgbouncer.ini during deployment/cluster creation

### ISSUE THREAD

**Issue by aprilito1965** [CrunchyData/postgres-operator#1969]
**What is the motivation or use case for the change? **
For now some deployment parameters have to be configured manually even in helm-way deployment. Its pretty frustrating, not documented and not gitops-like at all.

**Describe the solution you'd like**
It would be great if we can configure pgbouncer.ini (pool mode, pool size), users.txt (and may be some other configmap ncluded files) with values in helm chart (as default ones) or parameters during cluster creation (as cluster specific).

**Please tell us about your environment:**
Google Kubernetes Engine cluster
Container Image Tag: crunchy-postgres-ha:centos7-12.4-4.5.0
Platform Version: 1.17.9-gke.6300

**Comment by DavidKmn** [comment]
@jkatz any reason why the configuration cant be done in this way?

**Comment by jkatz** [comment]
We just moved the `pgbouncer.ini` configuration to a ConfigMap for the 4.5.0 release -- before it was buried in a Secret, which was a bit more difficult to modify :wink: I'm glad that the 4.5.0 release exposes the possibility of being able to further customize pgBouncer.

We are continuing to iterate on the Operator to make it more "GitOps" friendly. The types of workflows that people are using Operators for have changed since the Operator was first open sourced almost 4 years ago.

There are various ways of deploying Kubernetes manifests, and from my observations and discussions it seems that people are standardizing around Helm or Kustomize.

Which leads to the question:

> why the configuration cant be done in this way?

There's no reason it can't: part of it has been waiting to understand what toolchains should be supported. Even in the past year I've seen that space change a lot: Helm v3 (GA'd just under a year ago) has had a major impact on Helm adoption, and Kustomize has certainly seen an uptick in growth.

Do I think we'll provide official Helm support? Probably, there's seems to be enough demand. But it also involves doing certain things to the Operator itself to make it more "GitOps" friendly, which I can tell you is in the works. Because of the long history of the Operator, it will take a moment to make everyone happy with the changes, but it will be well worth it.

If you want to roll your own piece of a Helm chart or are interested in proposing a patch that could either be added to the examples or the documentation, this is the current pgbouncer.ini template file that we use to load into the ConfigMap:

[https://github.com/CrunchyData/postgres-operator/blob/master/installers/ansible/roles/pgo-operator/files/pgo-configs/pgbouncer.ini](https://github.com/CrunchyData/postgres-operator/blob/master/installers/ansible/roles/pgo-operator/files/pgo-configs/pgbouncer.ini)

When adding a pgBouncer to a cluster, if the Operator already detects an existing ConfigMap for that cluster, it will continue onward with adding the other associated Kubernetes objects.

Thanks for the feedback. I can assure you this is something we are looking at, and of course suggestions and contributions are welcome.

**Comment by ValClarkson** [comment]
Hi @aprilito1965 !

With the release of [PGO v5](https://access.crunchydata.com/documentation/postgres-operator/latest/), we are now re-evaluating various GitHub issues, feature requests, etc. from previous PGO v4 releases.  More specifically, in order to properly prioritize the features and fixes needed by our end-users for upcoming PGO v5 releases, we are now attempting to identify which PGO v4 issues, use cases, and enhancement requests are still valid (especially in the context of PGO v5). 

Therefore, please let us know if you are still experiencing this issue in PGO v5.

If so, you can either respond to this issue directly to ensure it remains open, or you can close this issue and submit a new one for PGO v5 (this would also be a great opportunity to include any updated details, context or any other information relevant to your issue).  Otherwise, we will be closing this issue in the next 30 days.

If you are still running PGO v4, we recommend that you [upgrade to PGO v5](https://access.crunchydata.com/documentation/postgres-operator/latest/guides/v4tov5/) as soon as possible to ensure you have the latest PGO features and functionality.
