### ISSUE TITLE
Centos8 images not present on dockerhub --> any reason?

### ISSUE THREAD

**Issue by jose-joye** [CrunchyData/postgres-operator#1972]
Hello,

I have seen that the Centos7 images for the release 4.5 are all on DockerHub. However, the one for centos8 are not there yet.
Any reason for this?
Is it "safe" to use Centos8 for production yet or should stick on Centos7 for now?

Thanks a lot,
José

**Comment by jkatz** [comment]
The [CentOS 8 images are available in the developer portal](https://www.crunchydata.com/developers/download-postgres/containers) as well as our customer portal. We have no plans to make them available on DockerHub at present time.

Whether or not CentOS 8 is ready for production use is your call. Our production supported containers exist in the customer portal. We do have customers running the EL8 containers in production. This is the first release with EL8 support, so there may be specific bugs we uncover due to being in the EL8 environment (see #1953), but this is no different than most fundamental software changes.
