### ISSUE TITLE
Replication broken for postgres operator

### ISSUE THREAD

**Issue by kseswar** [CrunchyData/postgres-operator#1976]
The below query yields different results on master DB v/s replica DB 
select count(*) from intrusionsettable i
where domain_id='TEST-1' AND state=1;"
Why does this happen?

And replication is broken for postgres cluster without warning.
Is there anyway to recover this without rebuilding the cluster. 

**Please tell us about your environment:**

Operating System: Linux based
Where is this running ( Local, Cloud Provider) - GCP GKE cluster
Storage being used (NFS, Hostpath, Gluster, etc):GCP PVC,
Container Image Tag: centos7-4.3.0 / centos7-12.2-4.3.0
PostgreSQL Version:12.2
Platform (Docker, Kubernetes, OpenShift): Kubernetes
Platform Version: 1.16.11-gke.5

**Comment by jkatz** [comment]
There are a few questions to ask when looking at issues with out-of-sync replicas

- How did you create the replicas?
- How is PostgreSQL configured? Did you customize your PostgreSQL deployments at all in a way that would affect replication?
- What is your backup retention policy?

In its default setting, the PostgreSQL Operator backs each cluster with a pgBackRest repository, so that there are as many write-ahead logs as long as you have a replica set up.

There is a bunch of literature around PostgreSQL replication monitoring and management. Here are some articles that may help:

- [Troubleshooting Streaming Replication Synchronization](https://info.crunchydata.com/blog/wheres-my-replica-troubleshooting-streaming-replication-synchronization-in-postgresql)
- [https://info.crunchydata.com/blog/postgresql-monitoring-for-app-developers-alerts-troubleshooting](https://info.crunchydata.com/blog/postgresql-monitoring-for-app-developers-alerts-troubleshooting) (the section on "Replication Lag," which points to several articles)

With the query, there is potentially a lag between a replica and primary anyway if you're using asynchronous replication. If your application is sensitive to losing writes, and/or you want your replicas to always match the primary, consider using [Synchronous Replication](https://access.crunchydata.com/documentation/postgres-operator/4.5.0/architecture/high-availability/#synchronous-replication-guarding-against-transactions-loss). There is typically a performance / availability tradeoff with synchronous replication.

Also, there have been 3 bug fix releases for 4.3 (as well as two additional minor releases). It's always recommended to be on the latest patch release (in this case 4.3.3) to ensure you have the latest bug fixes.

Anyway, without more information, I don't think this is a bug. If this is in production, please refer to our [support](https://access.crunchydata.com/documentation/postgres-operator/latest/support/) policy.
