### ISSUE TITLE
Ability to set Operator TLS version and cipher suites

### ISSUE THREAD

**Issue by DanielTolczyk** [CrunchyData/postgres-operator#1978]
**What is the motivation or use case for the change? **

I'd like the ability to set the minimum TLS version to 1.2 or 1.3.
I'd like the ability to set my own set of cipher suites to ensure I'm using the same suites across my cluster. 

**Describe the solution you'd like**

This line at https://github.com/CrunchyData/postgres-operator/blob/master/apiserver.go#L156 shows the minimum TLS version.

I found https://stackoverflow.com/questions/31226131/how-to-set-tls-cipher-for-go-server/31227225#31227225 which shows an example of what I think that could start to look like. 

I'd like it to be configurable via a configmap or environment variable.

**Comment by stevekerrison** [comment]
While securing PGO installations, I realised this issue too. I can configure the `postgres` server's TLS via the `bootstrap/dcs/postgresql/parameters` section in a `postgres-ha.yaml` file. And for `pgadmin` it can easily be TLS-fronted by an appropriately configured ingress.

One _quick fix_ would be to bump the minimum version and set some modern cipher suite defaults in the `apiserver` code. The PGO client should have no issue dealing with this.

Longer term, these could be configurable via environment variable, which itself could be set via `pgo-install.yaml` or whatever method people are using.

**Comment by stevekerrison** [comment]
Drafted a PR here: https://github.com/CrunchyData/postgres-operator/issues/1978

It deals with the quick fix. I'll see when I get a chance to test it out, but others welcome to take a look too.

**Comment by jkatz** [comment]
I'm OK with bumping up the minimum to TLS 1.2, but I wouldn't backpatch it.

**Comment by ValClarkson** [comment]
Hi @DanielTolczyk !

With the release of [PGO v5](https://access.crunchydata.com/documentation/postgres-operator/latest/), we are now re-evaluating various GitHub issues, feature requests, etc. from previous PGO v4 releases.  More specifically, in order to properly prioritize the features and fixes needed by our end-users for upcoming PGO v5 releases, we are now attempting to identify which PGO v4 issues, use cases, and enhancement requests are still valid (especially in the context of PGO v5). 

Therefore, please let us know if you are still experiencing this issue in PGO v5.

If so, you can either respond to this issue directly to ensure it remains open, or you can close this issue and submit a new one for PGO v5 (this would also be a great opportunity to include any updated details, context or any other information relevant to your issue).  Otherwise, we will be closing this issue in the next 30 days.

If you are still running PGO v4, we recommend that you [upgrade to PGO v5](https://access.crunchydata.com/documentation/postgres-operator/latest/guides/v4tov5/) as soon as possible to ensure you have the latest PGO features and functionality.
