### ISSUE TITLE
pgbouncer configuration

### ISSUE THREAD

**Issue by Aussenac** [CrunchyData/postgres-operator#1983]
Hi

Could you please explain me how connections are routed to the new master pod in case of failover ?

In the file pgbouncer.ini,  the first line reference the primary name
  = host={{.PG_PRIMARY_SERVICE_NAME}} port={{.PG_PORT}} auth_user=pgbouncer

During my testing, I could observe that PG_PRIMARY_SERVICE_NAME is not re evaluated in case of failover

How Kubernetes can switch to the correct endpoint ?

It was tested with Crunchy Data 4.3.2, is it working differently in 4.5.0

Regards
Marie

**Comment by jkatz** [comment]
@Aussenac Sorry that this took a long time to reply to -- I had thought I answered it awhile ago, but it turns out I was mistaken!

Using this:

`* = host={{.PG_PRIMARY_SERVICE_NAME}} port={{.PG_PORT}} auth_user=pgbouncer`

The default configuration that the Operator provides is for it to connect to the primary *Service*. In Kubernetes, [Services are stable](https://kubernetes.io/docs/concepts/services-networking/service/), but allow for the Pods they represent to change.

During a failover event, the Operator's HA system will change the identifying label for the primary Pod -- the Service `selector` will handle this. At this point, if the Pod's labels have changed, you will need to wait on Kubernetes to identify that the Pod labels have changed and in turn, update the Service to point at those Pods.

By using the defined configuration, pgBouncer does not need to perform any updates during a failover, given the Service is a stable endpoint it can point at. Given the Service will be automatically pointed at the new Pod, though the timeline will depend on how quickly Kubernetes can refresh this change.
