### ISSUE TITLE
Request for Benchmark information - using / not using --sync-replication flag in create cluster command

### ISSUE THREAD

**Issue by devopsevd** [CrunchyData/postgres-operator#2011]
** Which example are you working with? **
I have setup a postgres cluster using the operator

**What is the current behavior?**
- works as expected 
**What is the expected behavior?**
- works as expected 
**Other information** (e.g. detailed explanation, related issues,  etc)
-NA
**Please tell us about your environment:**
Test environment deployed on GKE
* Operating System:
* Where is this running ( Local , Cloud Provider) - Cloud GCP
* Storage being used (NFS, Hostpath, Gluster, etc): GCP PVC
* Container Image Tag: centos7-4.3.0 / centos7-12.2-4.3.0
* PostgreSQL Version: 12.2
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version: 1.17

---------
Request for information, if available -
Can you provide me any bench mark information ( latency related to the replication between primary and the replicas ) when the --sync-replication  is used ( enabled ) vs when its not being used.

**Comment by jkatz** [comment]
The short answer is no.

The longer answer is this can vary greatly based upon the environment you are in. There is almost definitely a performance penalty when using synchronous replication as any replica needs to acknowledge that the transaction is received before it can be completed. However, the performance of this step can vary due to a variety of environmental circumstances, including:

- Transaction rate
- Network speed & saturation
- Resource availability of the replica
- The underlying storage

and more.

You will need to run your own benchmarks to understand the tradeoffs in your environment. If your application is sensitive to losing writes, you may need to accept the performance penalty when using synchronous replication.

Here are some resources that discuss sync replication in PostgreSQL and some things to consider when monitoring it:

- [https://info.crunchydata.com/blog/synchronous-replication-in-postgresql](https://info.crunchydata.com/blog/synchronous-replication-in-postgresql)
- [https://info.crunchydata.com/blog/postgresql-monitoring-for-application-developers-dba-stats](https://info.crunchydata.com/blog/postgresql-monitoring-for-application-developers-dba-stats)
- [https://info.crunchydata.com/blog/postgresql-monitoring-for-app-developers-alerts-troubleshooting](https://info.crunchydata.com/blog/postgresql-monitoring-for-app-developers-alerts-troubleshooting)

Lastly, any analysis should be performed on a newer version of the Postgres Operator. The latest 4.3.x bugfix version is 4.3.3 which includes many bug fixes, and the current feature version is 4.5.0.
