### ISSUE TITLE
Don't use SSHD

### ISSUE THREAD

**Issue by james-callahan** [CrunchyData/postgres-operator#2017]
I'm trying to figure out the architecture of postgres-operator and why there is an SSHD running in there. It seems to be used for pgbackrest functionality; but its not quite obvious, or I've missed some docs.

Depending on the reason for its existence; if pgbackrest is running as a sidecar, it's possible to have it share a mount point with the main container.

**Comment by jkatz** [comment]
There are a few reasons that `sshd` is employed for utilizing the archiving and pgBackRest backup capabilities.

Consulting with some of the [pgBackRest](https://github.com/pgbackrest/pgbackrest) folks, if pgBackRest were to run as a sidecar to a PostgreSQL instance, we would need to determine the sidecar sees the exact same mounts as the kernel filesystem cache as the PostgreSQL container regardless of filesystem type (e.g. network-based filesystems, which are fairly common in Kubernetes). Perhaps this is not an obstacle now as when the original decision was made and could be determined with some experimentation, though presently we support Kubernetes back to 1.11 and need to ensure the Operator is still compatible with older versions of Kubernetes.

If we did include the pgBackRest repository as a sidecar, we would then need to ensure it is present in any replicas of a PostgreSQL Pod in order to optimize the amount of time it would take to promote a replica in a failover scenario. However, in this scenario, this would require the pgBackRest repository PVC to be mounted by each Pod containing the pgBackRest sidecar, and not all Kubernetes environments support `ReadWriteMany` and/or the mounting of a single PVC multiple times.

Now, there are several things that the pgBackRest folks could do to help make this scenario possible directly, however, there is an existing solution: use the [S3 compatible support](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/disaster-recovery/#using-s3) that pgBackRest provides. Using this, you can store your backups inside your Kubernetes cluster using [MinIO](https://github.com/minio/minio). This allows you to store archives and backups within your Kubernetes cluster but not use sshd.

If you have further questions about this or would like to discuss further, I'd be happy to set up a chat (jonathan.katz@crunchydata.com) to better understand your use case and why `sshd` is restricted.

**Comment by james-callahan** [comment]
> use the [S3 compatible support](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/disaster-recovery/#using-s3) that pgBackRest provides. Using this, you can store your backups inside your Kubernetes cluster using [MinIO](https://github.com/minio/minio). This allows you to store archives and backups within your Kubernetes cluster but not use sshd.

oh; we are intending to use the S3 compatible support. If this means we don't have to run SSHD we just need a way to turn it off (if its not already)
