### ISSUE TITLE
backup and restore 1tb in gcs using postgres operator

### ISSUE THREAD

**Issue by kseswar** [CrunchyData/postgres-operator#2018]
Hi There,

We are trying to test backup and restore into a gcs bucket for our postgres operator.
When i backup 1tb file its not available in gcs bucket.

So i tried with 100gb file, for which i could find the backup file in the gcs bucket.
But when tried to restore the same file. Im not able to to it.
I have also tried increasing the pvc size and memory.

**Please tell us about your environment:**

Operating System: Linux based
Where is this running ( Local, Cloud Provider) - GCP GKE cluster
Storage being used (NFS, Hostpath, Gluster, etc):GCP PVC,
Container Image Tag: centos7-4.3.0 / centos7-12.2-4.3.0
PostgreSQL Version:12.2
Platform (Docker, Kubernetes, OpenShift): Kubernetes
Platform Version: 1.16.11-gke.5

**Comment by jkatz** [comment]
This is next to impossible to troubleshoot without additional information, particularly logs and deployments topology, which is what is presented in the other issues that were opened.

And as mentioned in previous issues, if is referencing a bug, i could very well have been fixed in the latest bug fix release of 4.3.x or in a new version of the Operator, which has fixes and improvements to restore.
