### ISSUE TITLE
Using pgo client from the same machine to manage to different postgres-operator installs

### ISSUE THREAD

**Issue by IJOL** [CrunchyData/postgres-operator#2020]
How can i make a second install of pgo client for another postgres-operator in another k8s cluster, without making the first unavailable forever, I will need to use it along with the new one, and be able to switch between the two installs, as I've assume that the pgo client will be different in version 44.4.0 than in 4.5.0.. so I think I need to make 2 installs in parallel but I'm open to any suggestions..

**Comment by jkatz** [comment]
This could be a good case for using the [`pgo-client` container](https://access.crunchydata.com/documentation/postgres-operator/latest/installation/pgo-client/#pgo-client-container):

[https://access.crunchydata.com/documentation/postgres-operator/latest/installation/pgo-client/#pgo-client-container](https://access.crunchydata.com/documentation/postgres-operator/latest/installation/pgo-client/#pgo-client-container)

Through this, you can run `pgo` locally either via your Docker/Podman environment, or deploy it within your Kubernetes cluster and run commands by execing into it. Either way, it allows you to keep your `pgo` binaries separated.

**Comment by IJOL** [comment]
I did like very much to go with the pgo-cliente container,, but AFAIK the
docs say that ansible is needed this a no go for us..


Saludos,
--------------------------------------------
Ignacio J.Ortega
skype:ignacioj.ortega

**Comment by ValClarkson** [comment]
Hi @IJOL!

With the release of [PGO v5](https://access.crunchydata.com/documentation/postgres-operator/latest/), we are now re-evaluating various GitHub issues, feature request, etc. from previous PGO v4 releases.  More specifically, in order to properly prioritize the features and fixes needed by our end-users for upcoming PGO v5 releases, we are now attempting to identify which PGO v4 issues, use-cases and enhancement requests are still valid (especially in the context of PGO v5). 

Therefore, please let us know if you are still experiencing this issue in PGO v5.

If so, you can either respond to this issue directly to ensure it remains open, or you can close this issue and submit a new one for PGO v5 (this would also be a great opportunity to include any updated details, context or any other information relevant to your issue).  Otherwise, we will be closing this issue in the next 30 days.

If you are still running PGO v4, we recommend that you [upgrade to PGO v5](https://access.crunchydata.com/documentation/postgres-operator/latest/guides/v4tov5/) as soon as possible to ensure you have the latest PGO features and functionality.

For questions regarding version release on operatorhub
OperatorHub releases are always behind our direct releases -- which is unfortunate but reasonable since OperatorHub releases have to go through testing and review on that side of things. In the meantime, if you want to check out 5.1.1 before then, please see the [docs](https://access.crunchydata.com/documentation/postgres-operator/v5/installation/) and in [the postgres-operator-examples repo](https://github.com/CrunchyData/postgres-operator-examples) for instructions on installing directly.
