### ISSUE TITLE
PLV8

### ISSUE THREAD

**Issue by wayne-o** [CrunchyData/postgres-operator#2044]
** Which example are you working with? **
quickstart
**What is the current behavior?**
I can't enable PLV8
**What is the expected behavior?**
I would like to be able to enable PLV8
**Other information** (e.g. detailed explanation, related issues,  etc)

If it's not possible natively - how can I switch out the postgres image used by the operator to use an image with PLV8 already installed?

w

**Comment by wayne-o** [comment]
I am trying to figure out how to add PLV8 myself and perhaps submit a PR - can anyone give me some pointers to get me started?

thank you

**Comment by jkatz** [comment]
Speaking with the build team, adding PL/V8 would add a lot of weight to the containers as we would have to bring in all of Chromium, which is a nonstarter at this time.

I am certainly a fan of PL/V8 ([I co-presented a talk about it about six years ago](https://www.slideshare.net/jkatz05/webscale-postgresql-jsonb)) so the answer is not at this time, but we are exploring ways to better accommodate extensions like PL/V8, PL/R, etc.

**Comment by tunatoksoz** [comment]
I would like to open this issue, adding some of the extensions (or having instructions to build custom postgres image to be used with pgo can enable great deal of flexibility.

For my use case, i work with JSON fields a lot, and i want to use projections on a column, and the easiest way to do this is plv8. It's a large column with many fields, and selecting saves users bandwidth etc, and picking which columns (instead of materializing) at runtime is a great hlp

**Comment by skhilar** [comment]
Is there any plan to support plv8 extension. Or can we use custom image to support plv8.
