### ISSUE TITLE
Migrating non-trivial sized database into the operator

### ISSUE THREAD

**Issue by dennisjac** [CrunchyData/postgres-operator#2076]
Is there a way to bootstrap a new cluster from an external physical backup? I'm currently looking into options of migrating a reasonably large database (>100G) into the operator but from what I can tell there are only two ways of bootstrapping a new cluster:
1. Import from a logical backup
2. Restore from the backup of another operator managed cluster

What I'm looking for is a way to import a physical backup (something like pg_basebackup or pgbackrest) on bootstrap to keep the 
import time manageable. What would be the best way to accomplish this?

One way this could work would be to provide an option the pre-populate the data-pvc from an external source (e.g. S3).
Another way that would not require modification of the creation process would be the ability to import an existing pgbackrest backup from an external source into the backup repository of an existing cluster and then trigger a restore from this backup using the already existing mechanisms.

**Comment by jkatz** [comment]
> What I'm looking for is a way to import a physical backup (something like pg_basebackup or pgbackrest) on bootstrap to  keep the import time manageable.

There are different ways to approach this.

If the goal is to create a cluster from a pgBackRest backup, you can leverage the `--restore-from` option in `pgo create cluster`. Since Operator 4.4 (current version 4.5.1), you are able to do this from an existing pgBackRest repository **without** being attached to a running PostgreSQL cluster.

Your pgBackRest repository would have to follow the present naming scheme the Operator recognizes for this to work with outside data (e.g. `<clusterName>-pgbr-repo` for a PVC. I'd have to double check the S3 naming scheme but I believe it's similar).

Documentation on this is here:

- [https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/disaster-recovery/#restores](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/disaster-recovery/#restores)
- [https://access.crunchydata.com/documentation/postgres-operator/latest/tutorial/disaster-recovery/](https://access.crunchydata.com/documentation/postgres-operator/latest/tutorial/disaster-recovery/)

Another option would be to create a standby cluster that is managed by the Operator that replicates the data from the cluster you are trying to migrate. This can be accomplished in a few ways:

- Create a standby cluster that is connected directly to the primary you are looking to migrate from
- Create a standby cluster that is connected to a broker S3 repository that is replaying the WAL logs. This type of architecture is in these docs, though you would not need to worry about the multi-Operator setup:

[https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/high-availability/multi-cluster-kubernetes/](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/high-availability/multi-cluster-kubernetes/)

I will note that I have seen all of the above method used successfully for performing limited downtime migrations into the Operator.

**Comment by OmarEltamasehy** [comment]
Please advice if there is another way to migrate my production database that is not managed by PGO  to the database created by command >> `pgo create cluster mycluster `

I think that some data will be missed during creating backup and restoring the backup to pgo cluster as the old database in production mode so I search about way to avoid data loss and down time.

**Comment by jkatz** [comment]
A method to perform a migration that limits downtime is [described in this comment](https://github.com/CrunchyData/postgres-operator/issues/2076#issuecomment-734912430). Repeating it for the sake of clarity:

-----
Another option would be to create a standby cluster that is managed by the Operator that replicates the data from the cluster you are trying to migrate. This can be accomplished in a few ways:

- Create a standby cluster that is connected directly to the primary you are looking to migrate from
- Create a standby cluster that is connected to a broker S3 repository that is replaying the WAL logs. This type of architecture is in these docs, though you would not need to worry about the multi-Operator setup:

[https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/high-availability/multi-cluster-kubernetes/](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/high-availability/multi-cluster-kubernetes/)

I will note that I have seen all of the above method used successfully for performing limited downtime migrations into the Operator.
