### ISSUE TITLE
Install PGO Client on Windows 10 - TLS certificates question

### ISSUE THREAD

**Issue by command0r** [CrunchyData/postgres-operator#2079]
**Which example are you working with?**
I'm working on the PGO client configuration on Windows 10. The documentation [here](https://access.crunchydata.com/documentation/postgres-operator/4.5.0/installation/pgo-client/) is clear up until the point where you need to configure Client TLS certificates. It's not clear where do I get those certificates... are these self-generated/self-signed (in IIS, for instance?)

**What is the current behavior?**
The client created with this command "**pgo create pgadmin hippo**" fails. I see the error: "level=fatal msg="failed to set up TLS client: PGO_CA_CERT not specified". It seems the step with certs setup is mandatory.

**What is the expected behavior?**
Working PGO Client

**Please tell us about your environment:**
* Operating System: Windows 10 /1903
* Where is this running: local
* Target Platform: Kubernetes (AKS)

**Comment by jkatz** [comment]
Does this help?

[https://info.crunchydata.com/blog/set-up-and-run-postgresql-operator-client-on-windows](https://info.crunchydata.com/blog/set-up-and-run-postgresql-operator-client-on-windows)

**Comment by command0r** [comment]
@jkatz, thanks for the prompt reply! Not really helpful. This article doesn't explain the thing with certificates as well. Where do I get **.crt** and **.pem**? I need to setup these variables:
- PGO_CA_CERT
- PGO_CLIENT_CERT
- PGO_CLIENT_KEY

but I can't find any explanation how do we receive these certs???

**Comment by jkatz** [comment]
The quickstart has a way of getting these certificates:

[https://access.crunchydata.com/documentation/postgres-operator/latest/quickstart/#install-the-pgo-client](https://access.crunchydata.com/documentation/postgres-operator/latest/quickstart/#install-the-pgo-client)

However, those exist in a Bash shell script, so I don't believe it maps well to Windows. The source code (and in turn steps) is in here:

[https://raw.githubusercontent.com/CrunchyData/postgres-operator/master/installers/kubectl/client-setup.sh](https://raw.githubusercontent.com/CrunchyData/postgres-operator/master/installers/kubectl/client-setup.sh)

**Comment by command0r** [comment]
Thank you, @jkatz. What's the best way to process with configuration then? Do I install in Linux and copy the certificates to Windows machine? Are there any steps specific for Windows-based configuration?

**Comment by AleksanderRoszig** [comment]
@command0r you can save tls.crt and tls.key from pgo.tls secret in namespace where is your operator and then save this in windows as client.crt and client.key and set this files as PGO_CA_CERT, PGO_CLIENT_CERT, PGO_CLIENT_KEY. That should help for you.

**Comment by command0r** [comment]
@AleksanderRoszig, I didn't quite get what you were trying to say. Where do I get those certificates in the first place? Using **client-setup.sh**?

**Comment by AleksanderRoszig** [comment]
@command0r  
In openshift I do:
`oc get secret pgo.tls -n operator_namespace -o yaml` and then get data from tls.key and tls.crt. Decode this from base64 and then you have client.crt and client.key in windows. 
Please let me know if it helped you

**Comment by command0r** [comment]
Ok, guys, to tackle this issue I decided to use Ubuntu WSL (the one that is installed on top of Windows 10) and it worked well. I got to the point where I can start creating the cluster. Here's the problem though... whenever I run `pgo create cluster -n pgo hippo`, I get the error: `Error: pgo client and server version mismatch`. Indeed, the latest release version of the pgo client [here](https://github.com/CrunchyData/postgres-operator/releases) is **4.4.2**, wheres documentation [here](https://access.crunchydata.com/documentation/postgres-operator/latest/quickstart/#install-the-pgo-client) suggests to install postgres-operator with version **4.5.1**, i.e.: `kubectl apply -f https://raw.githubusercontent.com/CrunchyData/postgres-operator/v4.5.1/installers/kubectl/postgres-operator.yml`.
Thoughts?

**Comment by jkatz** [comment]
The latest version is actually here: [https://github.com/CrunchyData/postgres-operator/releases/tag/v4.5.1](https://github.com/CrunchyData/postgres-operator/releases/tag/v4.5.1) but I don't know how to make GitHub actually treat this as the true "latest."

**Comment by command0r** [comment]
Ok, I figured the trick with the release and now have the cluster installed. If you're to install Postgres Operator from Windows 10 machine, as I did, I think Ubuntu WSL is the way to go. Another option is the Linux-based bastion host you're accessing the cluster from (up to you at the end). Closing the thread. Thanks everyone for the help!

**Comment by jkatz** [comment]
Glad to hear it's working.

If there are steps we can add to the directions for the other Windows method, I'd gladly welcome to them.

**Comment by command0r** [comment]
Hi @jkatz, absolutely! I outlined everything I knew in the blog post [here](https://strive2code.com/post/2020/12/08/deploy-crunchy-postgresql-operator-to-aks1).

**Comment by sam1216p** [comment]
@aleksrosz  your inputs to extract certificate and key from pgo.tls works for me. I managed to extract from pgo.tls and configure my pgo client on windows. Thanks!!

**Comment by Venryx** [comment]
It might be a good idea to link to the section about pgo-client setup (ie. https://access.crunchydata.com/documentation/postgres-operator/latest/quickstart/#install-the-pgo-client), from this quick-start page: https://access.crunchydata.com/documentation/postgres-operator/5.0.1/quickstart

It was very confusing to me to have followed the quickstart instructions, and yet be unable to use the standard `pgo` tool that is meant for creating clusters. I did not realize there was another quickstart that was necessary for using the `pgo` tool, until I tried to run it and got a not-very-informative `could not find pgouser file` message.

The error message perhaps could have a hint, something like:
> "Could not find pgouser file.
> Did you forget to copy the '.pgo/..." files from Linux, and/or set the six environment variables to point to it?
> See here for more info: https://access.crunchydata.com/documentation/postgres-operator/latest/quickstart/#install-the-pgo-client"

**Comment by Venryx** [comment]
EDIT: Nevermind, it looks like the "latest" page is in fact the old version, and the v5 page is the newest/current.

In that case, where are the instructions on setting up the `pgo` tool on Windows in v5? The instructions for 4.7 appear to not work. (I get the error `Error from server (NotFound): secrets "pgouser-admin" not found` when running `./client-setup.sh` -- which I need to in order for the `.pgo` folder to get generated)

**Comment by cornel-masson** [comment]
@Venryx I have the same issue.

I followed the latest documentation: https://access.crunchydata.com/documentation/postgres-operator/5.0.4/

I could get the cluster going, but there's no v5 documentation for the pgo _client_. I tried the 4.0.1 installation procedure at https://access.crunchydata.com/documentation/postgres-operator/4.0.1/installation/install-pgo-client/ and downloaded the 4.7.3 pgo file for Linux: https://github.com/CrunchyData/postgres-operator/releases/download/v4.7.3/pgo. It seems this is the latest client file, there is no v5 pgo client?

`pgo --help` works. Then I tried `pgo version`, but got a succession of startup errors. 

First, I had to set PGO_APISERVER_URL. The older docs that I found said to port-forward to **svc/postgres-operator**, but there is no such service deployed. In the end I created a port-forward to the pgo pod that I could see, port 8443. Not sure if this works, because I got stuck again...

`pgo version` now complains: "could not find pgouser file". I found instructions in the old docs, and created a `~/.pgo/pgoser` file, but I didn't know what to use for username:password. Some other older docs I found refers to a file `conf/postgresql-operator/pgouser` that is referenced during the cluster installation, but I can see no such file in the example repo that I forked (which is the latest documented way of starting a cluster). I still don't know where to find the username:password.

I also don't know where to find the client certificate files referenced in: https://access.crunchydata.com/documentation/postgres-operator/4.7.0/installation/pgo-client/. Nowhere in my cluster installation (from the forked example repo) does it mention this, and the client docs suggest that you get this from the admin who installed the cluster, which is me, and me don't know.

**Comment by jkatz** [comment]
@cornel-masson If you're starting on a new project, I suggest beginning with v5. I would recommend following through the tutorial.

There is currently no pgo client for v5. The pgo client is for v4. All of the objects you are referencing above are specific to v5, and would not be compatible with v4.

If you do need to work with v4, I do similarly suggest following the quickstart and the tutorial:

https://access.crunchydata.com/documentation/postgres-operator/latest/quickstart/

The quickstart also includes a guide to getting any certificates related to the v4 PGO API server, including the use of the "client-setup.sh" script.

**Comment by cornel-masson** [comment]
@jkatz I have now installed the 4.7.3 client as per your link. I still have two unresolved issues:

1. pgo client complains:

**pgouser-admin Secret not found** in namespace: postgres-operator
Please ensure that the PostgreSQL Operator has been installed.

This is because the postgres operator installation did not create that secret. I used the helm installation: no such secret.

2. The postgres-operator installation also did not install **svc/postgres-operator**, so the port-forward to the api-server does not work.

**Comment by cornel-masson** [comment]
@jkatz I have now installed the 4.7.3 client as per your link.
- I had to work around some inconsistencies between 4.7.3 and 5.0.4 installation documentation. 
- I still have one unresolved issue.

** Workarounds **
1. pgo client complains: _pgouser-admin_ Secret not found in namespace: postgres-operator. Please ensure that the PostgreSQL Operator has been installed.

This is because the postgres operator installation did not create that secret. I used the helm installation for v5: no such secret. I manually created such a secret, providing "username" and "password" data, which worked.

2. pgo client also can't find the next secret: _pgo.tls_. It seems in v5 this secret is called "...cluster-cert": I manually extracted the client.crt and client.key files from this.

** Unresolved issue **
After fixing the above, the pgo client still can't connect to the api-server, because the postgres-operator installation (helm release) did not install **svc/postgres-operator**, so the port-forward to the api-server does not work.
