### ISSUE TITLE
unrecognized configuration parameter "wal_keep_segments" in file "/pgdata/rmgl/postgresql.conf

### ISSUE THREAD

**Issue by Bhagi33** [CrunchyData/postgres-operator#2094]
**Describe the bug** i upgraded the crunchy postgresl cluster from 12.4 to 13.1 version

After upgrade postgresql is not running due to the error "unrecognized configuration parameter "wal_keep_segments" in file "/pgdata/rmgl/postgresql.conf". Please fix the bug. and provide me the solution.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Please tell us about your environment:**

* Operating System:
* Where is this running ( Local, Cloud Provider) cloud
* Storage being used (NFS, Hostpath, Gluster, etc):NFS
* Container Image Tag: 
* PostgreSQL Version:13
* Platform (Docker, Kubernetes, OpenShift):kubernetes
* Platform Version:

**Additional context**

2020-12-03 05:53:49,400 INFO: Lock owner: None; I am rmgl-5b8446c48c-l4qhk
2020-12-03 05:53:49,410 INFO: Reaped pid=4763, exit status=0
2020-12-03 05:53:49,411 INFO: Lock owner: None; I am rmgl-5b8446c48c-l4qhk
2020-12-03 05:53:49,411 INFO: starting as a secondary
2020-12-03 05:53:49.602 GMT [4769] LOG:  unrecognized configuration parameter "wal_keep_segments" in file "/pgdata/rmgl/postgresql.conf" line 27
2020-12-03 05:53:49.602 GMT [4769] FATAL:  configuration file "/pgdata/rmgl/postgresql.conf" contains errors
2020-12-03 05:53:49,609 INFO: postmaster pid=4769
/tmp:5432 - no response
2020-12-03 05:53:49,642 WARNING: Postgresql is not running.
2020-12-03 05:53:49,642 INFO: Lock owner: None; I am rmgl-5b8446c48c-l4qhk

**Comment by jkatz** [comment]
The PostgreSQL Operator does not use the `wal_keep_segments` parameter. This is likely set due to a custom configuration. Please review the section of the documentation on customizing the Operator configuration:

[https://access.crunchydata.com/documentation/postgres-operator/latest/advanced/custom-configuration/](https://access.crunchydata.com/documentation/postgres-operator/latest/advanced/custom-configuration/)

Based on how to Operator manages PostgreSQL clusters, I would recommend removing that parameter. However, if you wish to keep using it, this parameter is renamed to `wal_keep_size` in PostgreSQL 13. You can read more about it in the [PostgreSQL 13 release notes](https://www.postgresql.org/docs/13/release-13.html).

**Comment by leosussan** [comment]
To be clear - I get the exact same bug, and I have applied zero customizations to the postgresql.conf file. But - it's almost certainly due to the use of an improper upgrade path (attempting to use `pgo upgrade` on a major release). There isn't a clear how-to in the documentation re: major releases, so this is understandable -- a clear no-downtime upgrade path would probably mitigate such issues.

**Comment by tchellomello** [comment]
I also hit this bug without any customization on my side. I checked my configmaps and I don't have such configuration. Even modifying the file directly on the PVC, upon restart it gets initiated again.

**Comment by tchellomello** [comment]
Digging a little bit, the issue seems to be coming when reading the data from the backrest-repo PVC as it seems the `wal_keep_segments` is coming from the file from the older version. I was able to reproduce the same issue when trying to create a new cluster from the backup 

```
pgo create cluster toca-restored --restore-from=toca
```
I'll check how I can mount the backup and modify the file or maybe specify a older PostgreSQL version to get the database started.

**Comment by tchellomello** [comment]
Just a follow-up, I looked at all my backups and replicas and they all had the `wal_keep_segments`. Somehow this was created on the older versions and the PG13 throws an error.  To speedup my recovery, I delete the cluster, created a new one and restored from a cold backup.

**Comment by jkatz** [comment]
Out of curiosity, how did you upgrade between major versions?

**Comment by tchellomello** [comment]
@jkatz I'm using the kubernetes operator, so I downloaded the newer `yaml`, used the `cleanup`, and deployed the new operator. 

Then updated the `pgo` client and latest `pgo upgrade cluster`.

**Comment by jkatz** [comment]
If you're coming from a version of PostgreSQL older than 13 (e.g. 12, 11, etc.) and you did not follow a major upgrade procedure, that could certainly leave odd things in configurations. Presently the easiest way to do major upgrades when running the Operator is via the [`crunchy-upgrade`](https://access.crunchydata.com/documentation/crunchy-postgres-containers/latest/container-specifications/crunchy-upgrade/) container.

Otherwise, yes, a backed up `postgresql.conf` file with a removed setting can cause failures.

**Comment by tchellomello** [comment]
@jkatz yes probably that was my issue.  Trying to see how can I use `crunchy-upgrade` with the `crunchy-operator` in my k8s.
