### ISSUE TITLE
Pg Backrest repo is growing fastly

### ISSUE THREAD

**Issue by kapomaho** [CrunchyData/postgres-operator#2143]
Hello,

Although primary and replicas are a normal in size on the NFS , backrest repo's size growing fastly. How can i safely reduce the pgbr repo ? 

We are using ;
On premise Kubernetes 1.17.6
Nfs storage class;
Postgres and crunchy version: crunchy-postgres-gis-ha:centos7-12.3-4.3.2
  
 
![5](https://user-images.githubusercontent.com/3909094/102800738-55152700-43c5-11eb-9027-59aea0a5452f.png)

![2](https://user-images.githubusercontent.com/3909094/102800019-598d1000-43c4-11eb-95ad-4d9a857b7358.png)

![3](https://user-images.githubusercontent.com/3909094/102800204-99ec8e00-43c4-11eb-8c26-f75a5f706eac.png)

![4](https://user-images.githubusercontent.com/3909094/102800220-9fe26f00-43c4-11eb-9f66-bfa4b150d540.png)

**Comment by jkatz** [comment]
Consider setting backup retention policies. This is covered in the documentation:

- [https://access.crunchydata.com/documentation/postgres-operator/latest/tutorial/disaster-recovery/](https://access.crunchydata.com/documentation/postgres-operator/latest/tutorial/disaster-recovery/)
- [https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/disaster-recovery/](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/disaster-recovery/)

Based upon the total number of backups that you have, the repository size has likely grown due to the fact you have made a lot of changes to your data, and as such have pushed a lot of WAL archives. A healthy backup retention policy will help balance the current state of the data while ensuring you can recover to a particular point-in-time should you need to do so.

Additionally, there have also been several patch releases to the 4.3.x series since 4.3.2. You should also consider upgrading or going to a newer version of the Operator as well.

There will be a feature in version 4.6 (#2142) that will allow for you to explicitly expire backups, but this is meant as an emergency measure and you should instead set a proper retention policy.
