### ISSUE TITLE
Create a Helm Chart URL when creating PGO Releases

### ISSUE THREAD

**Issue by shicholas** [CrunchyData/postgres-operator#2231]
**What is the motivation or use case for the feature? **
Using Neo4j as an example, they publish their helm charts [as releases](https://github.com/neo4j-contrib/neo4j-helm/releases/tag/4.2.2-1). By doing so, I can write Terraform Code to source the [GitHub link directly](https://github.com/NeonLaw/codebase/blob/development/infrastructure/kubernetes/modules/neo4j_helm/main.tf#L3)

**Describe the solution you'd like**
In a release for PGO, like [this](https://github.com/CrunchyData/postgres-operator/releases/tag/v4.5.1), I should be able to also see a link to a tarball of just the helm chart in the `installers/helm` directory, so I can easily install/update my PGO using Helm and Terraform.

**Describe any alternatives you've considered**
The current alternatives necessitate me to download and `cd` into a directory. This is fine, but not as simple as what Neo4j does.

**Please tell us about your environment:**

* Operating System: Linux
* Where is this running ( Local , Cloud Provider): GKE, Infra is scripted with Terraform Cloud
* Storage being used (NFS, Hostpath, Gluster, etc): default gke storage
* Container Image Tag: 4.5.1
* PostgreSQL Version: 13
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version: 4.5.1

**Additional context**
Happy to answer questions about this feature request.

**Comment by shicholas** [comment]
I'm happy to help code this if I understand more about how you do releases. Thanks for this awesome lib!

**Comment by keithlayne** [comment]
It also might be trivially easy to publish a helm repo that can be used with `helm repo add ...`. I'm not sure what the requirements are, but I think the bar is low.

**Comment by keithlayne** [comment]
https://helm.sh/docs/topics/chart_repository/

**Comment by daadu** [comment]
Here is how I think this should be implemented,

1. Have an "orphan" git branch, say - "repo" or "helm-reo"
2. This branch will contain the chart repo for postgres-operator
3. With "Github Actions" - when new release is made - we run `helm package` and `helm index`, copy this resources to "repo" branch and commit it
4. Advertise (in docs and README) to use "Github Raw File" path to add the repo with `helm repo add`
5. Additional, instead of using seperate "orphan" branch, a directory could be created that contains the repo.

I use `helmfile` as GitOps/IaC tool to deploy to my k8s project, in that case a "helm repo" is required, and therefore this is pre-requisit for me, I have already done this in [my fork](https://github.com/daadu/postgres-operator/tree/helm-repo)(you can use `https://raw.githubusercontent.com/daadu/postgres-operator/helm-repo/installers/helm/repo` to run `helm repo add`, if you want) - but need to regularly update this - which I think could be achieved with Github Actions.


Let me know if this is a sound idea, I am willing to work on it.

**Comment by politician** [comment]
Here's a tutorial
https://harness.io/blog/helm-chart-repo/

**Comment by torbendury** [comment]
This would enable us to install and manage the operator Helm Chart with third party tools like Terraform to ensure a certain state in the cluster. Is this on any roadmap yet? I saw a PR that looked good, but was not merged

**Comment by jcpunk** [comment]
Posting to artifacthub.io once this is automated would be a huge help in assisting folks in finding this.

**Comment by benjaminjb** [comment]
Revisiting this issue now that we are releasing our Helm chart to an OCI-based registry: https://github.com/CrunchyData/postgres-operator-examples/pull/28#issuecomment-1361970898

That would seem to answer the issues here, but please reopen if that doesn't.
