### ISSUE TITLE
Provide capability to map the pgadmin application URL to a path under root ("/pgadmin/")

### ISSUE THREAD

**Issue by VasylSamoilov** [CrunchyData/postgres-operator#2232]
**What is the motivation or use case for the change? **
Configuring Kubernetes ingress to map the pgadmin container's root to a path under the cluster's root ("/pgadmin/") appears to result in http redirect errors from the python web application.

**Describe the solution you'd like**
Please provide parameter(s) for mapping the pgadmin website URL to a path other than the root ("/"). Also please consider defaulting to a location other than the root to avoid conflicts with other packages or services running in shared Kubernetes clusters

**Please tell us about your environment:**
EKS with nginx ingress and path-based routes.

* Operating System: linux
* Where is this running ( Local, Cloud Provider) AWS
* Storage being used (NFS, Hostpath, Gluster, etc): EBS/EFS
* Container Image Tag:
* PostgreSQL Version:
* Platform (Docker, Kubernetes, OpenShift):
* Platform Version:

**Additional context**
Issue was already described https://github.com/CrunchyData/postgres-operator/issues/496 and was moved to containers repo. Now container has this variable, but pgadmin template and operator don't, so there is still no way to configure it.

**Comment by ValClarkson** [comment]
Hi @VasylSamoilov,

With the release of [PGO v5](https://access.crunchydata.com/documentation/postgres-operator/latest/), we are now re-evaluating various GitHub issues, feature requests, etc. from previous PGO v4 releases.  More specifically, in order to properly prioritize the features and fixes needed by our end-users for upcoming PGO v5 releases, we are now attempting to identify which PGO v4 issues, use cases and enhancement requests are still valid (especially in the context of PGO v5). 

Therefore, please let us know if you are still interested in having the enhancement described in this issue implemented in PGO v5 

If so, you can either respond to this issue directly to ensure it remains open, or you can close this issue and submit a new one for PGO v5 (this would also be a great opportunity to include any updated details, context or any other information relevant to your issue).  Otherwise, we will be closing this issue in the next 30 days.

If you are still running PGO v4, we recommend that you [upgrade to PGO v5](https://access.crunchydata.com/documentation/postgres-operator/latest/guides/v4tov5/) as soon as possible to ensure you have the latest PGO features and functionality.
