### ISSUE TITLE
Documentation: instructions needed to create OLM CatalogSource

### ISSUE THREAD

**Issue by maykelg** [CrunchyData/postgres-operator#2259]
** Documentation Question **

The "Installation" section of the link:

https://access.crunchydata.com/documentation/postgres-operator/4.6.0/installation/other/operator-hub/

states:

*Create an OperatorGroup and a Subscription in your chosen namespace. Make sure the source and sourceNamespace match the CatalogSource from earlier.*

I could not find a reference to **CatalogSource** anywhere else in the documentation.  What are the steps required to create one?

**Comment by jkatz** [comment]
I don't know if those instructions are still relevant as they were written for an older version of the Operator/OLM/OperatorHub.  I would recommend either [following the instructions on OperatorHub](https://operatorhub.io/operator/postgresql) itself (which will also be further simplified once 4.6 is published https://github.com/operator-framework/community-operators/pull/3066 https://github.com/operator-framework/community-operators/pull/3067) or using the [quickstart](https://access.crunchydata.com/documentation/postgres-operator/latest/quickstart/) method, with the notes for OpenShift.

**Comment by andrewlecuyer** [comment]
Since this issue involves the OLM installation process for and older version of Crunchy Postgres for Kubernetes, I am going to proceed with closing this specific issue.

If you have any additional questions, and/or if you would like to further discuss the OLM installation process, please feel free to reach out on the [PostgreSQL Operator community mailing list](https://groups.google.com/a/crunchydata.com/forum/#!forum/postgres-operator/join).

And for more information about Crunchy Postgres for Kubernetes v5 (including guidance for upgrading from v4), please see the latest documentation:
https://access.crunchydata.com/documentation/postgres-operator/latest/

Thanks!
