### ISSUE TITLE
Support HTTP Client-Cert header with apiserver

### ISSUE THREAD

**Issue by tlvenn** [CrunchyData/postgres-operator#2280]
**What is the motivation or use case for the change? **

I am trying to setup an ingress using Traefik 2 and its [passTlsClientCert middleware](https://doc.traefik.io/traefik/middlewares/passtlsclientcert/) that puts the client TLS in the http header `X-Forwarded-Tls-Client-Cert` for the apiserver to consume but it does not seem to work outside of the box.

**Describe the solution you'd like**
The apiserver should be able to use the client TLS given in the http header by a proxy.

**Comment by jkatz** [comment]
This header appears to be specific to Traefik. Is there a particular reason why you are looking for this support? What is the use case?

**Comment by tlvenn** [comment]
Hi @jkatz ,


This is not a specific Traefik header but the standard one when it comes to proxied TLS connection, Istio is using the same for example.

The usecase is rather simple, i am trying to have a regular k8s ingress and tls client auth support at the same time to expose the api server. For https traffic, Traefik like most / all ingress controllers will terminate the SSL connection so the only way to keep the client TLS auth going is to ask Traefik to talk to the api server over https and to forward the client cert.

Since this is not working, i am forced to use a TCP route which support TLS passthrough but this forces me to open another port, specifically for pgo api server which is far from ideal.

**Comment by jkatz** [comment]
The standard headers looks like it's [Client-Cert](https://tools.ietf.org/id/draft-bdc-something-something-certificate-01.html#name-client-cert-http-header-fie). It seems most proxies use `X-Forwarded-Client-Cert` in this regard, with Traefik adding `Tls` in the middle.

Thanks for explaining this. I think if we did something to support this, I would want to skew towards the standard headers, but it's not inconceivable that we support something like:

- `Client-Cert`
-  `X-Forwarded-Client-Cert`
- `X-Forward-Tls-Client-Cert`

**Comment by andrewlecuyer** [comment]
Since this issue involves the API server for and older version of Crunchy Postgres for Kubernetes, I am going to proceed with closing this specific issue.

If you have any additional questions, and/or if you would like to further discuss the v5 API's, please feel free to reach out on the [PostgreSQL Operator community mailing list](https://groups.google.com/a/crunchydata.com/forum/#!forum/postgres-operator/join).

And for more information about Crunchy Postgres for Kubernetes v5 (including guidance for upgrading from v4), please see the latest documentation:

https://access.crunchydata.com/documentation/postgres-operator/latest/

Thanks!
