### ISSUE TITLE
Missing variable in pgo.yaml.j2 ?

### ISSUE THREAD

**Issue by Remp69** [CrunchyData/postgres-operator#2308]
**Describe the bug**
No variable "Policies:" in file  postgres-operator/installers/ansible/roles/pgo-operator/templates/pgo.yaml.j2. And no corresponding varible in ansible inventory.
When using ansible installation, no policies are applied on new pg clusters.

When adding "Policies" varibale in pgo.yaml. Policies listed in it are correctly applied on new clusters.

**To Reproduce**
Install with ansible and look at pgo.yaml file. Variable is missing.

**Expected behavior**
Example :
- In pgo.yaml.j2 :
Policies: {{ policy_list }} 
- In postgres-operator/installers/ansible/values.yaml :
policy_list:""

**Environment**
PGO v4.6.1

**Comment by jkatz** [comment]
Are you applying the policies uniformly across your PostgreSQL clusters?
Are you able to provide the policies one-off using the `--policies` flag on `pgo create cluster` or `pgo apply`?

**Comment by Remp69** [comment]
Are you applying the policies uniformly across your PostgreSQL clusters?
=> Yes
Are you able to provide the policies one-off using the --policies flag on pgo create cluster or pgo apply?
=> Yes

**Comment by prlaurence** [comment]
@Remp69 doing a bit of house cleaning and noticed this issue is a bit dated now. we currently recommend using either [kustomize](https://access.crunchydata.com/documentation/postgres-operator/latest/installation/kustomize/) or [helm](https://access.crunchydata.com/documentation/postgres-operator/latest/installation/helm/) for installation.  the Crunchy Data Developer Portal has a hopefully [helpful set of step by step install instructions](https://www.crunchydata.com/developers/get-started/postgres-operator). if Ansible installation is still of interest of course feel free to reopen or create a new issue.
