### ISSUE TITLE
configure postgres operator in k8s

### ISSUE THREAD

**Issue by kiranmudemela** [CrunchyData/postgres-operator#232]
I m following https://crunchydata.github.io/postgres-operator/installation/quick-installation/ 
to setup postgres operator in kubernetes cluster.  

github don't provide the steps .  Could you share the step-by-step procedure for configuring it ? 

bash-3.2$ pwd
/Users/mac/postgres-operator
bash-3.2$ pgo version
bash: pgo: command not found
bash-3.2$

**Comment by jmccormick2001** [comment]
for mac, you will need to download the release tar ball, and in that is the pgo-mac binary, you would use that to connect to the Operator running on your Kube.  Since the Kube is remote to your Mac, you will need to 'kubectl port-forward operatorpodname 18443:8443'....but I'll make a note to document the steps for Mac users as well in the docs...will leave this issue open until that doc work is done.

**Comment by kiranmudemela** [comment]
from MAC i m connecting to kubernetes cluster  which is in Cloud.

**Comment by Zman94** [comment]
Hello. Did the documentation ever get updated?

**Comment by cahoonpwork** [comment]
@Zman94 
Here is the link to the most up to date documents.  These will work for what is on the develop branch and 3.5 release candidates.  We are still working on the documents, so if you use them and run into issues let us know.

https://crunchydata.github.io/postgres-operator/latest/installation/installation/
