### ISSUE TITLE
Restore with pgbackrest fails

### ISSUE THREAD

**Issue by Schmaetz92** [CrunchyData/postgres-operator#2321]
**Describe the bug**
When restoring a cluster with PGBackrest, errors often occur. 
Two variants were tested: 
pgo restore cluster --pitr-target=2021-03-08 11:26:32.955223+00
pgo restore pgo-ssp-owncluster-dev --backup-opts="--set=20210308-101351F"

Pitr fails every time. Using snapshots only partially.
I attach the log as an attachment. 

**To Reproduce**
1. Create cluster
2. restore via initial snapshost
3. See error from bootstrap-Pod

**Expected behavior**
It is to be expected that the restore is carried out successfully every time.

**Please tell us about your environment:**

* Operating System:
* Where is this running ( Local, Cloud Provider): Cloud-Provider
* Storage being used (NFS, Hostpath, Gluster, etc): own Storage
* Container Image Tag: crunchy-postgres-ha:centos8-12.6-4.6.1
* PostgreSQL Version: 12.6
* Platform (Docker, Kubernetes, OpenShift): Openshift
* Platform Version: 4.6.18

**Additional context**
[log.txt](https://github.com/CrunchyData/postgres-operator/files/6100714/log.txt)

**Comment by jkatz** [comment]
Since you are specifying a specific recovery point, you also need to specify the recovery target type. This is covered in the documentation:

[https://access.crunchydata.com/documentation/postgres-operator/4.6.1/tutorial/disaster-recovery/#point-in-time-recovery-pitr](https://access.crunchydata.com/documentation/postgres-operator/4.6.1/tutorial/disaster-recovery/#point-in-time-recovery-pitr)

**Comment by Schmaetz** [comment]
Hi, 
Thanks for your message. 
My mistake, I forgot to add this to the bug report. 
However, the problem is the same for both procedures. 

pgo restore test --pitr-target="2021-03-09 06:06:04.062997+00" --backup-opts="--type=time"

I have attached the logs again. 

Best regards

[log (1).txt](https://github.com/CrunchyData/postgres-operator/files/6106253/log.1.txt)

**Comment by Schmaetz** [comment]
It seems that the problem is much bigger. 
When creating a new cluster with the following command:
pgo create cluster test-0  --restore-from test   --restore-opts "--type=time --target='2021-03-09 06:06:04.062997+00'"

basically the same problem occurs. 
I have attached the log. 

Best regards

[log (3).txt](https://github.com/CrunchyData/postgres-operator/files/6106477/log.3.txt)

**Comment by jose-joye** [comment]
Hello, 
From my side, when I want to perform a PITR restore, I always add the --set option within the backup-opts parameters.

eg: 
pgo restore test --pitr-target="2021-03-09 06:06:04.062997+00" --backup-opts="--type=time **--set=20210308-104753F**"

The backup-set should be the backup that is just prior the point you want to restore (to be determined with the pgo show backup cmd).

This way works for me (using pgo 4.5.1)

**Comment by Schmaetz** [comment]
Hi, 
Thank you very much for your advice. 
I have tried the whole thing once and basically it is the same result. Sometimes the restore works and sometimes not. 
I used the following command: 
pgo restore test --pitr-target="2021-03-09 08:54:07.062997+01" --backup-opts="--type=time --set=20210309-075406F"

The following backups are available: 

` full backup: 20210309-075406F
            timestamp start/stop: 2021-03-09 08:54:06 +0100 CET / 2021-03-09 08:54:26 +0100 CET
            wal start/stop: 000000010000000000000002 / 000000010000000000000002
            database size: 31.5MiB, backup size: 31.5MiB
            repository size: 3.8MiB, repository backup size: 3.8MiB
            backup reference list:

        incr backup: 20210309-075406F_20210309-075739I
            timestamp start/stop: 2021-03-09 08:57:39 +0100 CET / 2021-03-09 08:57:41 +0100 CET
            wal start/stop: 000000010000000000000004 / 000000010000000000000004
            database size: 31.5MiB, backup size: 112.3KiB
            repository size: 3.8MiB, repository backup size: 13.2KiB
            backup reference list: 20210309-075406F

        incr backup: 20210309-075406F_20210309-075857I
            timestamp start/stop: 2021-03-09 08:58:57 +0100 CET / 2021-03-09 08:59:01 +0100 CET
            wal start/stop: 000000010000000000000007 / 000000010000000000000007
            database size: 31.5MiB, backup size: 2.2MiB
            repository size: 3.8MiB, repository backup size: 239.8KiB
            backup reference list: 20210309-075406F, 20210309-075406F_20210309-075739I`

Under V 4.5.1 I had no problems, everything went through fine. I have attached the logs. 

Best regards

[log (4).txt](https://github.com/CrunchyData/postgres-operator/files/6106954/log.4.txt)

**Comment by Schmaetz** [comment]
Hi @jkatz 
can you please take another look at the subject matter. From my point of view, this is an actual problem and is not due to the solution you propose. 
I myself can not reopen the issue unfortunately. 

Thank you and best regards
