### ISSUE TITLE
TLS certificates not reloaded when secret is updated

### ISSUE THREAD

**Issue by irishandyb** [CrunchyData/postgres-operator#2353]
**Describe the bug**
I have found that server TLS secrets are not reloaded when the secrets specified in the `spec.tls.*Secret` field are updated.

For context - I am using cert-manager to issue and renew TLS certificates for my servers.
The initial certificate is generated and loaded my the server. However, when cert-manager issues a renewed certificate by updating the TLS secret, it is not captured by the postgres server.

I have noted that postgres itself does not automatically reload certs when the files change on disk, but does reload the certs upon `pg_ctl reload` or `pg_reload_conf()`.

This works as expected in a pure Docker deployment of postgres, see blow.

I believe that the cause is that the last modified timestamps for the cert/key files are not updated when the secret is updated.
The timestamps of the underlying Kubernetes symlinks are updated but not the link name.

```
bash-4.4$ ls -la /pgconf/tls
total 0
drwxrwsrwt 3 root postgres 180 Mar 28 17:50 .
drwxrwsrwt 8 root postgres 280 Mar 28 16:06 ..
drwxr-sr-x 2 root postgres 140 Mar 28 17:50 ..2021_03_28_17_50_21.411771128
lrwxrwxrwx 1 root root      13 Mar 28 16:04 ca.crt -> ..data/ca.crt
lrwxrwxrwx 1 root postgres  31 Mar 28 17:50 ..data -> ..2021_03_28_17_50_21.411771128
lrwxrwxrwx 1 root root      14 Mar 28 16:04 tls.crt -> ..data/tls.crt
lrwxrwxrwx 1 root root      14 Mar 28 16:04 tls.key -> ..data/tls.key
lrwxrwxrwx 1 root root      26 Mar 28 16:04 tls-replication.crt -> ..data/tls-replication.crt
lrwxrwxrwx 1 root root      26 Mar 28 16:04 tls-replication.key -> ..data/tls-replication.key


bash-4.4$ ls -la /pgconf/tls/..2021_03_28_17_50_21.411771128/
total 20
drwxr-sr-x 2 root postgres  140 Mar 28 17:50 .
drwxrwsrwt 3 root postgres  180 Mar 28 17:50 ..
-r--r----- 1 root postgres 1996 Mar 28 17:50 ca.crt
-r--r----- 1 root postgres 1562 Mar 28 17:50 tls.crt
-r--r----- 1 root postgres 1679 Mar 28 17:50 tls.key
-r--r----- 1 root postgres 1562 Mar 28 17:50 tls-replication.crt
-r--r----- 1 root postgres 1679 Mar 28 17:50 tls-replication.key
```

Note that the timestamp for ca.crt, tls.crt, and tls.key is Mar 28 16:04 however the link target (e.g., ..2021_03_28_17_50_21.411771128/tls.key) is Mar 28 17:50.

**To Reproduce**
As above, deploy a postgres instance with TLS enabled and update the tls secret.
The attached script described below can be used to generate the certificates without cert-manager.

**Expected behavior**
Ultimately, the expected behavior is that the operator would detect the updated secret and trigger the server to reload the certificates automatically.
However, at a minimum, we need a workaround for the issue of postgres ignoring the cert unless the timestamp has changed.

**Please tell us about your environment:**

* Operating System: Ubuntu
* Where is this running: local k3s
* Storage being used: hostpath
* Container Image Tag: crunchy-postgres-ha:centos8-13.1-4.6.0
* PostgreSQL Version: 13.1-4.6.0
* Platform: Kubernetes
* Platform Version: 1.20.2

**Additional context**
I have been able to successfully update certificates in a standalone Docker container via Docker volume mounts and `pg_ctl reload`.
I have attached a `certs.sh` script which generates a sample root CA and two signed certificates.
1) a cert for mydomain.com valid for 1 day
2) a cert for mydomain2.com valid for 2 days

I understand that these certs do not represent valid use case, but they serve as two distinct certificates.

When the certs are generated, one of them must be selected, renamed, and permissions set for the containers context:

```
$ cp mydomain.com.key server.key
$ cp mydomain.com.crt server.crt
$ sudo chown 1000:1000 server.*
$ sudo chmod 600 server.*
```

```
$ docker run --rm --name postgres -p 15432:5432 -e POSTGRES_HOST_AUTH_METHOD=trust \
-v "$(pwd)/server.crt:/var/lib/postgresql/server.crt:ro" \
-v "$(pwd)/server.key:/var/lib/postgresql/server.key:ro" \
postgres:12-alpine -c ssl=on -c ssl_cert_file=/var/lib/postgresql/server.crt -c ssl_key_file=/var/lib/postgresql/server.key
```

When the server is running, you can test the cert as follows:

`$ openssl s_client -starttls postgres -connect localhost:15432 < /dev/null | openssl x509 -noout -text | less
`
Make not of the Not Before / Not After values.

Replace the server.key and crt files with the mydomain2.key and cert. Then call pg_ctl reload.

`$ docker exec -ti -u postgres postgres pg_ctl reload
`
Testing the openssl x509 output again will reveal the new certificate has a Not After of 2 days instead of the original 1 day.

Any input or help on this issue would be gratefully appreciated.

**Comment by irishandyb** [comment]
Just realized that I can't attach files. Contents of the cert creation script:

```bash
# Generate a sample root CA
openssl genrsa -des3 -out ca.key 4096
openssl req -x509 -new -nodes -key ca.key -sha256 -days 1024 -out ca.crt

# Generate a key for mydomain.com, create a CSR, and then sign the cert - valid for 1 day
openssl genrsa -out mydomain.com.key 2048
openssl req -new -sha256 -key mydomain.com.key -subj "/C=US/ST=CA/O=MyOrg, Inc./CN=mydomain.com" -out mydomain.com.csr
openssl x509 -req -in mydomain.com.csr -CA ca.crt -CAkey ca.key -CAcreateserial -out mydomain.com.crt -days 1 -sha256

# Generate a key for mydomain2.com, create a CSR, and then sign the cert - valid for 2 days
openssl genrsa -out mydomain2.com.key 2048
openssl req -new -sha256 -key mydomain2.com.key -subj "/C=US/ST=CA/O=MyOrg, Inc./CN=mydomain2.com" -out mydomain2.com.csr
openssl x509 -req -in mydomain2.com.csr -CA ca.crt -CAkey ca.key -CAcreateserial -out mydomain2.com.crt -days 2 -sha256

# Examine the certs to verify the not before / not after values
# openssl x509 -in mydomain.com.crt -text -noout | less
# openssl x509 -in mydomain2.com.crt -text -noout | less

```

**Comment by jkatz** [comment]
> I have noted that postgres itself does not automatically reload certs when the files change on disk, but does reload the certs upon pg_ctl reload or pg_reload_conf().

That is correct -- though you could also use [`pgo reload`](https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/reference/pgo_reload/) to do this as well (and would likely be preferable as it will reload the entire cluster.

Having the Operator reload all of the instances upon the values of the Secret being updated would be new work.

**Comment by irishandyb** [comment]
Hi @jkatz,

I understand that having the operator automate the config reload upon secret update would be extra work - it would just be a nice feature.

However, putting that aside, there is still the bug in which the certs cannot be updated even with a manual reload.

The problem is that the tls.crt and tls.key files represented by the kubernetes secret are backed by symlinks.
When the secret is updated, kubernetes updates the underlying files in the `..data` directory - the last modified timestamp is updated for these target files, but the timestamp for the symlink files are not updated.

When the reload command is executed, postgres is not loading the new certificate ..  my Docker based testing indicates that this is because the timestamp of the cert file has not updated.

So, while even though the cert secret has been updated, and the new cert can be seen by `exec`ing into the pod and viewing it, the postgres server doesn't load the cert because the files timestamp hasn't changed.

Ultimately, one could call this an issue rooted in either kubernetes or postgres.

On the kubernetes side, when a secret or configmap is updated, the last modified time of the symlink presented within the pod should be updated.
On the postgres side, new certs should be recognised/reloaded based on the files contents, not its last modified time.

While neither of these issues are directly caused by the operator - its still a major flaw or lacking functionality in the operator.

If my report is correct, my understanding is that postgres instances deployed by the operator basically cannot use TLS.
While yes, you can deploy with TLS turned on, but once that cert expires (typically 90 days) there is no way to renew or update the cert.

Of course, I may be wrong, very happy for any feedback or alternatives.

**Comment by jkatz** [comment]
And what does `pgo restart ...` yield?

I have to check again what the exact implementation is as I have not looked at it in awhile. However, there are certain things to consider when running TLS + PostgreSQL in Kubernetes:

- PostgreSQL checks the ownership/group permissions of the key/certificates files. They can be no more permissive than `0640`. Typically you set it to `0600` as these are owned by the `postgres` user.
- However, in Kubernetes, Secrets are owned by the `root` user, though we can at least mount them with a GID that matches the `postgres` user. In this case, we mount it as `0640`.
- ...yet another however, if you want to a PostgreSQL instance and use a certificate, libpq forces the certificate to be no more permissive than `0600`, forcing it to be required as root. For the "replication TLS" feature, this means we have to keep a local copy of the certificate on the Pod in order to have proper ownership.

This is namely handling Kubernetes setting `root` to be the owner of the Secret.

Conceivably it would be possible to make a patch for libpq to allow for `0640` ownership to match what you have on the server front, but even if that were committed today, the earliest it would be available would be PostgreSQL 14, so we would only be able to set the proper GID ownership on that.

Anyway, this could be worth looking into further. I'm not convinced that "that postgres instances deployed by the operator basically cannot use TLS" as we have plenty of customers who are security conscious that are using this for almost a year now and this has not come up. I would also need to see more beyond Docker based testing as this is particularly targeting Kubernetes.

I may play around with this in a bit to see if/what/how I can reproduce the scenario.

**Comment by jkatz** [comment]
OK, so I went through the exact scenario I described and was unable to reproduce any issues.

1. I created a Postgres cluster e.g. `pgo create cluster hippo-tls --server-ca-secret=postgresql-ca --server-tls-secret=hippo.tls --tls-only`. This the key cert is using RSA.

  1a. I set up a port forward to my host machine, which is why you will see "localhost" in the examples

2. I confirmed that I had the certificate that I expected:

```
openssl s_client -starttls postgres -connect localhost:5432
```

(truncating output)

```
Peer signing digest: SHA256
Peer signature type: RSA-PSS
```

3. In the `hippo.tls` Secret, I added a ECDSA key/cert.

4. *I waited for the Secret to be refreshed on the Pod*. Note that this is subject to your Kubernetes Node refresh policy.

5. I ran `pgo reload hippo-tls`

6. Upon running `openssl s_client -starttls postgres -connect localhost:5432` I saw the new certificate, which was based upon the ECDSA pair:

```
Peer signing digest: SHA256
Peer signature type: ECDSA
```

So this appears to work as expected, and presently the additional work involved is running `pgo reload` manually. As such, this still falls under an enhancement request for the Operator to handle this step automatically.

**Comment by irishandyb** [comment]
Hi @jkatz 

Apologies for the late reply, I have been offline recently.

I am glad that you were able to get it working as expected.
The difference that I notice is that you are using `pgo reload`.
I am trying to use only the custom resources, so I am deploying the `Pgcluster` resource, updating the TLS secret and manually executing `pg_ctl reload` or `pg_reload_conf()`.
I am curious as to how the `pgo reload` differs from `pg_ctl` or `pg_reload_conf().

Either way, while I was hoping to avoid needing an additional client, it seems that the solution is to use the `pgo` client.

I will close the story as I have a way forward.

Lastly, I am very grateful for your time and effort in reproducing and troubleshooting this issue.
