### ISSUE TITLE
Lifecycle of PGO / Backward compatiblity

### ISSUE THREAD

**Issue by marco-devopsdojo** [CrunchyData/postgres-operator#2412]
Currenlty, we try to figure out a valid process to operate two versions for upgrading purpose. We do not want to have a big bang upgrade but a upgrade on namespace level.

Therefore, we were able to install to PGO in parallel by creating a seperate namespace for each Postgres-Operator(v.4.5.1 and 4.6.1). Afterwards we use `pgo update namespace MYNAMESPACE` and then `pgo upgrade MYCLUSTER -n MYNAMESPACE`.

So far no issue, but what we saw is that there were changes made at the CRD for [pgcluster](https://github.com/CrunchyData/postgres-operator/commits/master/installers/ansible/roles/pgo-operator/files/crds/pgclusters-crd.yaml) without specifing a version ([Kubernetes CRD versioning](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/)) which makes the global CRD not backwards compatible. Would it be possible to apply a fix and simply add the "old" version as deprecated to allow backward compatibility?

**Comment by jkatz** [comment]
At present, the CRD is specifically designed to be backwards compatible. There aren't any breaking changes between versions of it -- this is by design. Values in the custom resources may change, but the CRD remains the same. There will be a future release where that does not remain the case, but said release will support proper Kubernetes CRD versioning.

However, I would suggest that while it is "OK" to run two Operators simultaneously over a short period during the upgrade process, you should really get down to one, as you do not want two different Operators watching the same custom resources.

**Comment by marco-devopsdojo** [comment]
Yes thats the idea, we need two instances just during the upgrade process

 Thank you for the fast answer and clarification! :)
