### ISSUE TITLE
Enabling the crunchy-postgres-exporter sidecar on already deployed PostgreSQL cluster is not working

### ISSUE THREAD

**Issue by danibangelov** [CrunchyData/postgres-operator#2432]
We have already deployed PostgreSQL cluster on OpenShift cluster, most probably with previous version of the operator, the current one is "postgresoperator.v4.6.1".
I need to scrape the metrics, that why I am trying to enable the sidecar exporter.
Deploying new cluster with the postgresoperator.v4.6.1 and pgo flag --metrics or directly in the CR kind: Pgcluster, exporter: true, I am able to get the metrics from the exporter, it is working on the new created cluster.
The problem is, when the cluster had been already created with a previous version of the operator (sorry, I have no info, which version it was) and now I am trying:
"pgo update cluster clusterName --enable-metrics" or "exporter: true" in CR of type Pgcluster. Neither of the options is able to enable the sidecar exporter.
I was searching the existing issues for something similar, could not find anything.
Could you share with me, what could be the possible solutions?

**Comment by jkatz** [comment]
Toggling the metrics sidecar was introduced in [4.6.0](https://access.crunchydata.com/documentation/postgres-operator/latest/releases/4.6.0/) as described in the release notes. Doing so is described in various parts of the documentation:

- [Custom Resources](https://access.crunchydata.com/documentation/postgres-operator/4.6.2/custom-resources/#monitoring)
- [Tutorial](https://access.crunchydata.com/documentation/postgres-operator/4.6.2/tutorial/customize-cluster/#create-a-postgresql-cluster-with-monitoring)
- [Monitoring](https://access.crunchydata.com/documentation/postgres-operator/4.6.2/architecture/monitoring/#getting-started)

If there is a suspected bug, I would need to see logs from at least the `operator` container, otherwise this is nearly impossible to troubleshoot.

**Comment by jkatz** [comment]
> time="2021-04-27T09:19:49Z" level=error msg="could not update metrics collection sidecar: "/bin/bash: /opt/crunchy/bin/exporter/install.sh: No such file or directory\n"" func="internal/controller/pgcluster.(*Controller).onUpdate()" file="internal/controller/pgcluster/pgclustercontroller.go:247" version=4.6.1

This sounds to me like you have the incorrect container for `crunchy-postgres-ha`, or that the container image is tagged incorrectly. The installation file for the exporter scripts was moved to the `/opt/crunchy/bin/exporter/` directory when 4.6 was released, i.e. in https://github.com/CrunchyData/crunchy-containers/commit/4912f4a97

The good news is that moving to the correct `crunchy-postgres-ha` container should fix your issues.
