### ISSUE TITLE
automountServiceAccountToken override option

### ISSUE THREAD

**Issue by dave-b-code** [CrunchyData/postgres-operator#2453]
## Overview

A number of serviceaccounts (most notably pgo-default https://github.com/CrunchyData/postgres-operator/blob/cdcf3c7699e4131cc09d05b50031fec69a3c09de/installers/ansible/roles/pgo-operator/files/pgo-configs/pgo-default-sa.json#L8) have automountServiceAccountToken set to false which can't be overriden from the CRD.

## Use Case

Service meshes like istio or custom sidecars may require the service account token to be mounted for authentication with the kubernetes API server.

## Desired Behavior

A CRD field allowing all (or some of) automountServiceAccountToken parameters to be set to true.

Many thanks for the library and any assistance on this issue.

**Comment by jkatz** [comment]
Is there specific documentation in Istio that describes this requirement?

**Comment by dave-b-code** [comment]
This is not universal for all istio deployments, as some clusters support 3rd party jwts by default, but for those that don't istio will default to mounted first party tokens (https://istio.io/latest/docs/ops/best-practices/security/#configure-third-party-service-account-tokens). Having this as a configurable override will allow users to tailor their crunchy CRD to their environment, allowing clusters with only first-party jwt capabilities to allow the istio proxy to authenticate (such as KIND and other test environments).

**Comment by cbandy** [comment]
> A number of serviceaccounts (most notably pgo-default) have automountServiceAccountToken set to false

This is intentional. The pods we build that use this SA do not make calls to the Kubernetes API.

The recommended practice is to disable automount when possible:

- https://issue.k8s.io/57601
- https://www.cncf.io/blog/2019/01/14/9-kubernetes-security-best-practices-everyone-must-follow/
- https://www.openshift.com/blog/fine-grained-policy-enforcement-in-openshift-with-open-policy-agent
- https://hackersvanguard.com/abuse-kubernetes-with-the-automountserviceaccounttoken/


> Having this as a configurable override will allow users to tailor their crunchy CRD to their environment

The availability of this token API is cluster-wide, so I think the approach should be to configure it at the operator. You can do this by changing the `pgo-default-sa.json` file inside the `pgo-config` configmap then restarting the operator.

Are you using automatic (mutating webhook) [sidecar injection](https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/)? If so, I believe the fault lies with Istio. Istio is adding a container that needs this credential but neglects to mount it.

It seems to me that a Pod mutator should set `automountServiceAccountToken` of the Pod because it [takes precedence](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#use-the-default-service-account-to-access-the-api-server). Based on the closed issues on this topic, they don't seem to agree...

- https://github.com/istio/istio/issues?q=automountServiceAccountToken
