### ISSUE TITLE
Best practices for failover automatization

### ISSUE THREAD

**Issue by Martin-Hogge** [CrunchyData/postgres-operator#2474]
Hi,

In regards of the issue #2458, could you tell us if their are any best practices when no primary is promoted and we are forced to do a manual failover ?

I tought about a script that turn every X minutes checking if their is at least one primary up and if not, executing the `failover --target --force` command but I'm not sure it won't conflict with an eventual automatic failover ?

Thank you.

_Originally posted by @Martin-Hogge in https://github.com/CrunchyData/postgres-operator/issues/2458#issuecomment-847576939_

**Comment by tjmoore4** [comment]
Since this issue involves functionality from an older version of Crunchy Postgres for Kubernetes, I am proceeding with closing this issue. If you have any additional questions - or if you would like to discuss scenarios, processes, functionality, etc. with Crunchy Postgres for Kubernetes v5 - further, please feel free to reach out on the [[PostgreSQL Operator community mailing list](https://groups.google.com/a/crunchydata.com/forum/#!forum/postgres-operator/join)](https://groups.google.com/a/crunchydata.com/forum/#!forum/postgres-operator/join). And for more information about Crunchy Postgres for Kubernetes v5 (including guidance for upgrading from v4), please see the latest documentation:

https://access.crunchydata.com/documentation/postgres-operator/latest/

Thanks!
