### ISSUE TITLE
4.7.0 operator NAMESPACE env var

### ISSUE THREAD

**Issue by aceeric** [CrunchyData/postgres-operator#2514]
We are moving to the 4.7.0 operator. There is documentation [here](https://access.crunchydata.com/documentation/postgres-operator/4.7.0/architecture/namespace/) describing the ability for the operator in the `pgo` namespace to watch one, many, or all other namespaces. It doesn't say how to do that in the doc, but I found older docs [here](https://access.crunchydata.com/documentation/postgres-operator/4.0.0/gettingstarted/design/namespace/) indicating that the `NAMESPACE` env var of the operator could be set to `NAMESPACE=`  to have the operator watch ALL namespaces.

Out of the box, the NAMESPACE var is configured with value `pgo`. I hand-patched it to empty but the operator would not reconcile a `Pgcluster` CR in my namespace. When I hand-patched the namespace into the Operator Deployment env var - then the operator *did* perform the reconciliation.

Is it a supported feature to reconcile ALL namespaces and if so - what is the syntax - assuming this is still using the NAMESPACE env var in the Operator Deployment. Thank you.

**Comment by jkatz** [comment]
The current capabilities of [namespaces](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/namespace/), configurations, permissions, etc. are addressed here in the docs:

[https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/namespace/](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/namespace/)

PGO 4.7 does not support the namespace "all" mode due to maintaining backwards compatibility to OCP 3.11. However, an upcoming release is addressing "all" mode.

**Comment by aceeric** [comment]
Ok thank you.
