### ISSUE TITLE
operator 4.7.0 creates resources in watched namespaces

### ISSUE THREAD

**Issue by aceeric** [CrunchyData/postgres-operator#2517]
Regarding operator version 4.7.0. I've configured it to watch multiple namespaces. In _each_ watched namespace, the operator creates the following resources:

Secret(s):
pgo-backrest-token-zzzzz
pgo-default-token-zzzzz
pgo-pg-token-zzzzz
pgo-target-token-zzzzz

ServiceAccount(s):
pgo-backrest
pgo-default
pgo-pg
pgo-target

RoleBinding(s)
pgo-backrest-role-binding
pgo-pg-role-binding
pgo-target-role-binding

Role(s)
pgo-backrest-role
pgo-pg-role
pgo-target-role

It does this even though the namespace does not contain a `Pgcluster` resource. The operator shouldn't intervene in the namespace unless a `Pgcluster` resource exists. This approach conflicts with running a testing process like:

1. tear down namespace to a clean state
2. create resources and run test
3. evaluate results
4. change some condition
5. repeat

With the operator creating resources this way it makes it difficult to ensure a test starts from an absolutely clean state. Also - this approach seems atypical to me with regard to other operators. Compare to Strimzi Kafka, Elastic Cloud for k8s.

A more typical approach is - as stated earlier - the operator stays out of the namespace until a watched resource type - in this case a `Pgcluster` is generated into the namespace. Then at that point, and only at that point, the operator takes action. Ideally, when the `Pgcluster` is subsequenty removed, the operator would clean up all resources that *it* created as a  result of the appearance of the `Pgcluster` CR.

**Comment by andrewlecuyer** [comment]
Since this issue involves and older version of Crunchy Postgres for Kubernetes, I am proceeding with closing this issue.

To further discuss questions with RBAC, Secrets and/or Service Accounts in Crunchy Postgres for Kubernetes v5, please feel free to reach out on the [PostgreSQL Operator community mailing list](https://groups.google.com/a/crunchydata.com/forum/#!forum/postgres-operator/join).

And for more information about Crunchy Postgres for Kubernetes v5 (including guidance for upgrading from v4), please see the latest documentation:

https://access.crunchydata.com/documentation/postgres-operator/latest/

Thanks!
