### ISSUE TITLE
Export/Download Backups

### ISSUE THREAD

**Issue by semaja2** [CrunchyData/postgres-operator#2533]
What is the correct method for quickly downloading, or scheduling exports of the backups completed by PGO?

Ideally there is a way to issue a single command to initiate a download, or open a web ui to download from

**Comment by jkatz** [comment]
It depends on which backups you are looking to grab and where you are looking to place them.

If you are looking for the binary equivalent ones, you would need to copy the data directly from the PVC or blob storage system you are using.

Otherwise, if you are using `pg_dump`, you can run `pg_dump` on an external system and point it at the database that you want to extract the logical backup from.
