### ISSUE TITLE
HA Crunchy cluster service defined without a selector

### ISSUE THREAD

**Issue by stenwt** [CrunchyData/postgres-operator#2577]
With a new crunchy 5.0 cluster with 3 replicas, the service endpoints have no selector defined

environment: k3s 1.21, x86_64, crunchy 5.0

With this manifest: 

```
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: crunchy-db1
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-ha:centos8-13.3-0
  postgresVersion: 13
  instances:
    - name: crunchy-db1
      replicas: 3
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi

```
This fails: 

```
$ kubectl port-forward -n crunchy-db1 svc/crunchy-db1-primary 5432
error: cannot attach to *v1.Service: invalid service 'crunchy-db1-primary': Service is defined without a selector
$ kubectl port-forward -n crunchy-db1 svc/crunchy-db1-ha 5432
error: cannot attach to *v1.Service: invalid service 'crunchy-db1-ha': Service is defined without a selector
```

**Comment by stenwt** [comment]
the "Connect via psql in the Terminal" section in the quickstart works for me....

**Comment by jkatz** [comment]
I would check the namespace in the above example (i.e. kubectl port-forward -n crunchy-db1). Is your database deployed to the `crunchy-db1` namespace or the `postgres-operator` namespace (which is the default if you did not specify the namespace)

**Comment by cbandy** [comment]
```
$ kubectl port-forward -n crunchy-db1 svc/crunchy-db1-primary 5432
error: cannot attach to *v1.Service: invalid service 'crunchy-db1-primary': Service is defined without a selector
```

This is happening because `kubectl port-forward` only connects to pods. Passing a service, deployment, etc actually goes through this helper that grabs the first pod returned by that thing's selector: [k8s.io/kubectl/pkg/polymorphichelpers/helpers.go](https://github.com/kubernetes/kubernetes/blob/v1.21.0/staging/src/k8s.io/kubectl/pkg/polymorphichelpers/helpers.go#L84).

The services that point to the primary Postgres instance no longer use selectors. Instead, the process that elects the primary sets the service endpoints directly. This is safer during some failure modes but less friendly for users.
