### ISSUE TITLE
Any specific reason why PGO v5 is not on GitHub Releases?

### ISSUE THREAD

**Issue by DanielFerreiraJorge** [CrunchyData/postgres-operator#2617]
Hello, are there any reasons why the v5 is not on the github releases? I'm asking because a change in the policy may have occurred, maybe PGO is commercial now... I don't know... Thank you very much!

**Comment by jkatz** [comment]
You can find the packages here:

[https://www.crunchydata.com/developers/download-postgres/containers/postgres-operator-5x](https://www.crunchydata.com/developers/download-postgres/containers/postgres-operator-5x)

The v5 code is open source and available on the `master` branch.

**Comment by DanielFerreiraJorge** [comment]
Please, the original question was not addressed... Since the beginning of the project we have tagged GitHub Releases, but not for version 5. I've seen this question being ignored in other issues raised other people, like #2604 . 

Please, understand that there is a legitimate concern regarding this topic, because people depend on this project. And while it is completely fair that this project takes ANY direction you see fit, a little clarity is MUCH appreciated. The release pattern clearly changed, and there must be a reason why.

Thank you very much

**Comment by jkatz** [comment]
First, thanks for using PGO!

With PGO v5 we've made some changes to our overall process. Instead of providing quarterly release tags, we are focused on ongoing active development in the v5 primary development branch (`master`, which will become `main`).  Consistent with our practices in v4, previews of stable releases are made available in the [Crunchy Data Developer Portal](https://www.crunchydata.com/developers).

These changes will allow for more rapid feature development and releases in the upstream PGO project, while providing [Crunchy Postgres for Kubernetes](https://www.crunchydata.com/products/crunchy-postgresql-for-kubernetes/) users with stable releases for production use.

Currently we are continuing to tag and release our v4 version of the project in the same manner in which it has been previously.

To the extent you have concerns / constraints specific to your use, please feel free to reach out on info@crunchydata.com and we are happy to discuss how we can address those specifically.

As always, we make info available regarding various [support options](https://access.crunchydata.com/documentation/postgres-operator/v5/support/).
