### ISSUE TITLE
Save backup pgdump to S3 and list backup pgdump

### ISSUE THREAD

**Issue by Aussenac** [CrunchyData/postgres-operator#2645]
Save pgdump to S3
=============

We would like to be able to save a pgdump export to S3
We are able to save database with pgbackrest to S3, but not with backup-type pgdump 

The option --pgbackrest-storage-type is not taken into account when
we use it with the option --backup-type=pgdump.

```
pgo backup cluster-ha-async-pgbouncer --backup-type=pgdump --database=cluster-ha-async-pgbouncer --pgbackrest-storage-type=s3 -n pgouser1
created Pgtask backup-cluster-ha-async-pgbouncer-pgdump
```

What is the issue with above command ?
and what's the best way to save pg_dump export to S3 ?

List export pgdump
=============

pgo show backup mycluster -n ns shows only the last successfull backup 

```
pgo backup cluster-ha-async-pgbouncer --backup-type=pgdump --database=cluster-ha-async-pgbouncer  -n pgouser1
created Pgtask backup-cluster-ha-async-pgbouncer-pgdump

pgo show backup cluster-ha-async-pgbouncer --backup-type=pgdump -n pgouser1

pgdump : backup-cluster-ha-async-pgbouncer-pgdump
               PVC Name:         backup-cluster-ha-async-pgbouncer-pgdump-cluster-ha-async-pgbouncer-pvc
               Access Mode:    ReadWriteOnce
               PVC Size:             1G
               Creation:             2021-08-27 08:25:16 +0000 UTC
               CCPImageTag:   centos8-13.3-4.7.1
               Backup Status:   job completed [backup-cluster-ha-async-pgbouncer-pgdump-ynbq]
               Backup Host:     cluster-ha-async-pgbouncer
               Backup User Secret:       cluster-ha-async-pgbouncer-postgres-secret
               Backup Port:      5432
               Backup Opts:     

```               

```
pgo backup cluster-ha-async-pgbouncer --backup-type=pgdump --database=cluster-ha-async-pgbouncer  -n pgouser1
created Pgtask backup-cluster-ha-async-pgbouncer-pgdump

pgo show backup cluster-ha-async-pgbouncer --backup-type=pgdump -n pgouser1

pgdump : backup-cluster-ha-async-pgbouncer-pgdump
               PVC Name:         backup-cluster-ha-async-pgbouncer-pgdump-cluster-ha-async-pgbouncer-pvc
               Access Mode:    ReadWriteOnce
               PVC Size:             1G
               Creation:             2021-08-27 08:31:35 +0000 UTC
               CCPImageTag:   centos8-13.3-4.7.1
               Backup Status:   job submitted [backup-cluster-ha-async-pgbouncer-pgdump-crvi]
               Backup Host:     cluster-ha-async-pgbouncer
               Backup User Secret:       cluster-ha-async-pgbouncer-postgres-secret
               Backup Port:      5432
               Backup Opts:     
```

What is the option to use to have a complete list of the backup pgdump ?

Regards

**Comment by andrewlecuyer** [comment]
Hi @Aussenac!

Since this issue involves backup commands/support for an older version of Crunchy Postgres for Kubernetes, I am proceeding with closing this issue.

If you have any additional questions - or if you would like to further discuss support for logical backups (e.g. via `pg_dump`) as relates to v5 of the operator - please feel free to either submit a new issue with your latest use-case/detailas, or you can also reach out on the [PostgreSQL Operator community mailing list](https://groups.google.com/a/crunchydata.com/forum/#!forum/postgres-operator/join).

And for more information about Crunchy Postgres for Kubernetes v5 (including guidance for upgrading from v4), please see the latest documentation:

https://access.crunchydata.com/documentation/postgres-operator/latest/
