### ISSUE TITLE
Update documention for exposing PSQL using Openshift Routes (if possible)

### ISSUE THREAD

**Issue by YiannisGkoufas** [CrunchyData/postgres-operator#2671]
## Overview

While there are instructions about exposing PSQL externally (to the K8s/OCP cluster) via port forwarding, was wondering whether there can be instructions about exposing PSQL using Openshift Routes. That's only in the case that this is possible

## Use Case

Would like to connect remotely to the PSQL exposed by an Openshift cluster which I don't have kubectl tooling installed (in order to use port forwarding)

## Desired Behavior

Would love to see the instructions include samples of Openshift Routes configuration to expose the PSQL and some instructions about connecting under the specific setup in https://access.crunchydata.com/documentation/postgres-operator/v5/tutorial/connect-cluster/

## Environment

Tell us about your environment:

Please provide the following details:

- Platform:  Openshift
(the rest are omitted as I believe they are not needed)

**Comment by jkatz** [comment]
We can certainly consider adding it. Contributions are of course welcome.

**Comment by wideblue** [comment]
As far as I understand this is not possible with default ingress  controller  that is configured trough Openshift Routes resource, since psql does not use HTTP protocol. 
[Docs](https://docs.openshift.com/container-platform/4.9/networking/configuring_ingress_cluster_traffic/configuring-ingress-cluster-traffic-ingress-controller.html#configuring-ingress-cluster-traffic-ingress-controller)
"_An Ingress Controller is configured to accept external requests and proxy them based on the configured routes. This is limited to HTTP, HTTPS using SNI, and TLS using SNI, which is sufficient for web applications and services that work over TLS with SNI._"

**Comment by benjaminjb** [comment]
From my reading on this subject, it looks like you can't use routes for Postgres. I'm going to close this issue, but if I've misread or if you've found something else, feel free to reopen this issue.
