### ISSUE TITLE
pgreplica does not change value in cluster after successful failover.

### ISSUE THREAD

**Issue by jazz0013** [CrunchyData/postgres-operator#2686]
pgreplica does not change value in cluster after successful failover.
Sequencing:
1. A new cluster is being created. (testdb02-fthu: primary)
2. A replica is add to the cluster (testdb02-fthu : primary; testdb02-tydg : replica; pgreplica : testdb02-tydg).
3. Failover succeeds (testdb02-fthu : replica; testdb02-tydg : primary; pgreplica : testdb02-tydg)
4. A replica is deleted (before failover, the role of which is primary - testdb02-fthu : primary; pgreplica : testdb02-fthu)

We have two problems:
- the monitoring metrics for the primary database after failover are executes as for the replica.
- when upgrading pgo to a higher version, a new replica is created, the pgreplica value is overridden.

Why is the pgreplica override not executed during failover?
How can I override pgreplica in the cluster after failover? 

```
cluster : testdb02 (crunchy-postgres-ha:centos8-13.3-4.7.0)
	pod : testdb02-fthu-7b8ddd5547-5xzkr (Running) on .eu-west-1.compute.internal (2/2) (replica)
		pvc: testdb02-fthu (5Gi)
	pod : testdb02-tydg-7cf88bfd5d-f9lhh (Running) on .eu-west-1.compute.internal (2/2) (primary)
		pvc: testdb02-tydg (5Gi)
	resources : CPU: 100m Memory: 1Gi
	limits : CPU: 2 Memory: 2Gi
	deployment : testdb02-backrest-shared-repo
	deployment : testdb02-fthu
	deployment : testdb02-tydg
	service : testdb02 - ClusterIP () - Ports (9187/TCP, 2022/TCP, 5432/TCP)
	service : testdb02-replica - ClusterIP () - Ports (9187/TCP, 2022/TCP, 5432/TCP)
	pgreplica : testdb02-tydg
	labels : pgouser=admin workflowid=77293f11-06ee-4316-9c49-0c227d25b0b6 crunchy-pgha-scope=testdb02 deployment-name=testdb02-tydg name=testdb02 pg-cluster=testdb02 pgo-version=4.7.0
```
```
kubectl -n test-aws get pgreplica
NAME            AGE
testdb02-tydg   3h26m
```

**Comment by gricuk** [comment]
The same question, @jkatz do you have any solutions for how to avoid this situation?

**Comment by tjmoore4** [comment]
Since this issue involves functionality from an older version of Crunchy Postgres for Kubernetes, I am proceeding with closing this issue. If you have any additional questions - or if you would like to discuss scenarios, processes, functionality, etc. with Crunchy Postgres for Kubernetes v5 - further, please feel free to reach out on the [PostgreSQL Operator community mailing list](https://groups.google.com/a/crunchydata.com/forum/#!forum/postgres-operator/join). And for more information about Crunchy Postgres for Kubernetes v5 (including guidance for upgrading from v4), please see the latest documentation:

https://access.crunchydata.com/documentation/postgres-operator/latest/

Thanks!
