### ISSUE TITLE
PGO Client container

### ISSUE THREAD

**Issue by ackerr01** [CrunchyData/postgres-operator#2715]
Hi I am trying to figure out how I can install the pgo client on a container instead of my machine. Looking at the docs it says I have to use the ansible installer & update the following value pgo_client_container_install. I searched the repo however was only able to find the ansible installer under the gcp-marketplace. Is there a helm alternative or another way I can install the pgo client container if I am not on GCP?

**Comment by jkatz** [comment]
If this is a new project, I recommend starting with [v5](https://access.crunchydata.com/documentation/postgres-operator/v5/).

Otherwise, if you need v4 the instructions for using the installers are here:

- [https://access.crunchydata.com/documentation/postgres-operator/latest/installation/postgres-operator/](https://access.crunchydata.com/documentation/postgres-operator/latest/installation/postgres-operator/)
- [https://access.crunchydata.com/documentation/postgres-operator/latest/installation/other/ansible/](https://access.crunchydata.com/documentation/postgres-operator/latest/installation/other/ansible/)
- [https://access.crunchydata.com/documentation/postgres-operator/latest/installation/pgo-client/](https://access.crunchydata.com/documentation/postgres-operator/latest/installation/pgo-client/)

**Comment by ackerr01** [comment]
So I was able to install the operator with the yaml link provided in the first document. the second document that talks about how to install with ansible refers to the installers/ansible which I can't seem to find in your repo. In fact if you click the link in the document it returns a 404 from github(https://github.com/CrunchyData/postgres-operator/tree/master/installers/ansible). the last article simply has the following instruction (which I am guessing I would us in that ansible folder I can't seem to find?)

The pgo-client container can be installed with the Ansible installer by updating the pgo_client_container_install variable in the inventory file. Set this variable to true in the inventory file and run the ansible-playbook. As part of the install the pgo.tls and pgouser-<username> secrets are used to configure the pgo client.

Thank you so much for the quick response!!!!
