### ISSUE TITLE
PGO installation in an Airgapped Environment

### ISSUE THREAD

**Issue by Shrivastava-Varsha** [CrunchyData/postgres-operator#2726]
Hi,

We are trying to install PGO in an airgapped (disconnected) environment. The setup expects to pull the images by digest and not by tag. However in the pgo.yaml configuration I see only tags values can be added (CCPImageTag PGOImageTag)
Is there a way to support airgapped installation in any existing version?

Below are the images for which we need to use digest and I dont find these names anywhere in the conf file.

- crunchy-postgres-ha
- pgo-apiserver
- pgo-backrest
- pgo-backrest-repo
- pgo-event
- pgo-scheduler
- postgres-operator

Env details:

- Platform: OpenShift
- Platform Version: 4.6/4.7
- PGO Image Tag: ubi8-4.6.2
- Postgres Version: 13
- Storage: ibmc-block-bronze
- Number of Postgres clusters: 1

Thanks in advance!

**Comment by jkatz** [comment]
If this is a new installation, I would suggest starting with [v5](https://access.crunchydata.com/documentation/postgres-operator/v5/). You can reference the image directly with v5.

Otherwise, if you want to use image digests, you can set the `RELATED_IMAGE` environmental variables in the `postgres-operator `container. The available variables are here: 

https://github.com/CrunchyData/postgres-operator/blob/REL_4_7/installers/olm/postgresoperator.csv.images.yaml
