### ISSUE TITLE
No funny characters in passwords

### ISSUE THREAD

**Issue by pietrobaricco** [CrunchyData/postgres-operator#2781]
## Overview

Provide a way to pick a password generation strategy which avoids special characters

## Use Case

The default generated passwords include characters like <, >, |, spaces and random punctuation.
I get that this is probably fine and secure, but causes me unnecessary pain when
- using them in bash scripts, requiring awkward escapes
- using them to provide a direct dbeaver connection, using the parameter "con" which requires values being separated by pipes and no way to escape the pipes

## Desired Behavior

Provide an option to generate passwords which do not contain funny characters, something like [a-z0-9_-]
Together with an option to specify the length of the generated passwords, I think this wouldn't have an impact on security.
Just make the password longer

**Comment by pietrobaricco** [comment]
Dbeaver connection strings (passed from the cmdline options) look like 

`driver=sqlite|database=C:\db\SQLite\Chinook.db|name=SQLiteChin|openConsole=true|folder=SQLite`

full docs here: [https://dbeaver.com/docs/wiki/Command-Line/](https://dbeaver.com/docs/wiki/Command-Line/)

in my case, the full command may be

`dbeaver -con "driver=postgresql|host=127.0.0.1|port=5432|user=pguser|password=pass_with_|_pipes|server=app_dev|showSystemObjects=true|showUtilityObjects=true|savePassword=true"`

There doesn't seem to be a way to escape pipes, so I have to resort to .pgpass to provide dynamically generated desktop shortcuts, which are handy on dev boxes (which manage ephemeral and/or local clusters).

For me this is more of a nuisance in these environments, as on production clusters passwords are injected via kubernetes manifests.

**Comment by Richard87** [comment]
Hi, I also have a lot of issues here, both in pgLoader and PHP/Symfony/PDO.  I would love to double the length of characthers, and stay withiin ALPHANUM instead of special chars...

**Comment by EugenMayer** [comment]
> Thanks for the feedback. We will look at what we can do about exceptions to the generation.
> 
> > optionally, being able to provide the password without having it generated by PGO itself
> 
> [This is already possible](https://access.crunchydata.com/documentation/postgres-operator/v5/architecture/user-management/#custom-passwords), though you would have to go through the initial generation.

While I understand this as a workaround, I think it does nobody a favour. Crunchy data offers a huge USP - user provisioning and even writing that information back into secrets an awesome way. What else to wish!.

But if the passwords created are so fragile in terms of being usable to different applications, things change - it is no longer an USP since you cannot rely on it. And if you cannot rely on it, you change the process to be all manual to get it reliable, which the above does.

Not sure it is really worth giving up so much just to have characters like `<>/:"'` inside a password. Honestly, the character space is so large, we can use 40, 50 character passwords without those ones, still being more then secure.

Just think about it. Really running into one issue after the other with this ;/ ( #2935 )
