### ISSUE TITLE
unable to access cluster through pgbouncer for users with options: "SUPERUSER"

### ISSUE THREAD

**Issue by jansmets** [CrunchyData/postgres-operator#2803]
Users with the option "SUPERUSER" can't connect to the cluster over pgbouncer.
Removing the SUPERUSER option doesn't make it work : the user is still unable to connect. The user effectively remains a superuser. I would have expected the operator to alter the user with nosuperuser.

connected applications may need superuser privileges to enable extensions as part of their set up.

**Comment by jkatz** [comment]
I think I described this in a previous issue but can't find it to reference.

The problem is that this then makes the `pgbouncer` system account, which is locked down, to be an implied superuser. If you allow one or more superuser to log in via pgBouncer, the `pgbouncer` account effectively becomes a superuser and anyone with access to that account can then become a superuser.

If you need for users to enable extensions, you can either:

a) Log in directly to the PostgreSQL database as a superuser to enable the extension.
b) Add the extension enablement as [part of the database bootstrap](https://access.crunchydata.com/documentation/postgres-operator/v5/tutorial/customize-cluster/#database-initialization-sql).
c) (PostgreSQL 13+) Set an extension as [trusted](https://www.postgresql.org/about/featurematrix/detail/347/) and allow regular privileged users to install them.

Separately, I would caution having applications do anything that directly involves superuser privileges, or if that's not possible, at least separating the things that handle DDL/administrative functions from the standard application functionality.
