### ISSUE TITLE
How do i connect to the postgres cluster from outside the k8s cluster?

### ISSUE THREAD

**Issue by Pratyush2703** [CrunchyData/postgres-operator#2835]
As it says in the title, 

following from https://access.crunchydata.com/documentation/postgres-operator/v5/tutorial/connect-cluster/

how do i access the postgres cluster via a service if all the credentials are hidden in secrets and the services are managed and cannot be patched.

**Comment by Pratyush2703** [comment]
Effectively, I want to use the postgres as a db for an external application not hosted on my k8s cluster

**Comment by jkatz** [comment]
> how do i access the postgres cluster via a service if all the credentials are hidden in secrets and the services are managed and cannot be patched.

The primary Service can be exposed using the `spec.service`:

https://access.crunchydata.com/documentation/postgres-operator/v5/references/crd/#postgresclusterspecservice

If you are using PgBouncer, that service can be exposed using `spec.proxy.pgBouncer.service`:

https://access.crunchydata.com/documentation/postgres-operator/v5/references/crd/#postgresclusterspecproxypgbouncerservice

You will have to decide how you best want to allow for external applications to access the credentials. I believe there are a variety of options that allow for that. You can also choose to [manually set the credentials](https://access.crunchydata.com/documentation/postgres-operator/v5/architecture/user-management/#custom-passwords). The process of manually setting the credentials will also be simpler in the upcoming v5.0.4 release as you will only have to modify `password` instead of creating your own SCRAM verifier.

**Comment by jashanbhullar** [comment]
Hey @jkatz I understand the primay instance can be exposed either via pgBouncer or by the service that you mentioned . Looking to your comment [here](https://github.com/CrunchyData/postgres-operator/issues/2896#issuecomment-986989636) read replicas service is also there but I still it confusing as to how to expose both read replicas and primary service via pgbouncer? 

I would ideally like 2 services (one read and one write) or just 1 service (both read and write) exposed via pgbouncer! How can that be achieved?
