### ISSUE TITLE
Bootstrap cluster with custom user password

### ISSUE THREAD

**Issue by lingwooc** [CrunchyData/postgres-operator#2861]
## Overview

We have our databases on a different cluster to our applications so auto generated passwords are unwieldy. I have a secret definition which has a username and verifier set (I do not set the password at all). This is created "simultaneously" with the CRD to create the cluster. If my understanding of the issue is correct, when the operator creates the cluster it overwrites the secret as I've deployed it with its own. This means that my credentials are not initially valid. If I reapply my secret the operator then reads it and applies it to the cluster, all is well.

Not all applications are well behaved if they cannot connect to a database with their credentials initially. Fusionauth's silent install is a good example of this. The application will check the database is up (but not check auth) then try exactly once to install.

## Use Case

For user defined passwords to be valid as soon as the database is available. Important for those who bootstrap _many_ clusters.

## Desired Behavior

Ideally the operator will read the existing verifier and apply it to the cluster as it creates the user rather than generating its own. If a password is not provided it should acknowledge this in the secret with a placeholder in the appropriate helper fields (these become wrong for custom passwords set only with verifiers anyway).

## Environment

Tell us about your environment:

Please provide the following details:

- Platform: GKE
- PGO Image Tag: 5.0.3
- Postgres Version: 13
- Storage: (e.g. `hostpath`, `nfs`, or the name of your storage class)
- Number of Postgres clusters: 1

**Comment by benjaminjb** [comment]
Hello @lingwooc, I'm going to close this ticket only because there is a duplicate ticket that has a few more responses and +1 from people in the community. That ticket is https://github.com/CrunchyData/postgres-operator/issues/3262. 

(I just want to consolidate this issue into a single ticket so that we can more easily gather the requirements/use-cases for it and also have a central place to announce when that feature is released.)

But you have identified a real need here and we have captured that in our backlog.
