### ISSUE TITLE
PGO service not available if installed by kustomize

### ISSUE THREAD

**Issue by sambeet99** [CrunchyData/postgres-operator#2869]
Bug

We can install PGO by 2 ways - (1) Postgres Operator Installer (https://access.crunchydata.com/documentation/postgres- 
                                                                                                                                                                           operator/latest/quickstart/)
                                                   (2) Kustomize yaml (kubectl apply -k kustomize/install)

So all the steps ( like Pgo client , pgo service) clearly explained in installer way , but in kustomize yaml we dont get to interact with Pgo .
If we apply kustomize to install PGO , I am not able to interact to Database cluster by PGO because I dont see pgo client  or any PGo service port-forward.
Hence with gitops workflow (using fluxcd) we can use kustomize but once DB cluster is up we can not use PGO commands to interact with cluster.

Platform: Kubernetes

Platform Version: Server Version: version.Info{Major:"1", Minor:"21"

PGO Image Tag: env:
- name: CRUNCHY_DEBUG
value: "true"
- name: RELATED_IMAGE_POSTGRES_13
value: "registry.developers.crunchydata.com/crunchydata/crunchy-postgres:centos8-13.4-1"
- name: RELATED_IMAGE_POSTGRES_13_GIS_3.1
value: "registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis:centos8-13.4-3.1-1"
- name: RELATED_IMAGE_PGBACKREST
value: "registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:centos8-2.35-0"
- name: RELATED_IMAGE_PGBOUNCER
value: "registry.developers.crunchydata.com/crunchydata/crunchy-pgbouncer:centos8-1.15-3"
- name: RELATED_IMAGE_PGEXPORTER
value: "registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter:ubi8-5.0.3-0"

Postgres Version: 13

Steps to Reproduce -
(1) Steps - https://access.crunchydata.com/documentation/postgres-operator/v5/quickstart/

I have used HA mode.
cluster name = demo

EXPECTED
(1) PGO service should be available so that we can use various pgo commands (pgo create cluster hippo ,  pgo test -n pgo hippo etc..)
(2) process to Connecting to pgAdmin should be available.

ACTUAL
PGO pod and database cluster is up and running  but pgo commands not available to interact with cluster. Seems Pgo is not usable in the cluster.

Additional Information

Both ways of installing pgo (installer and kustomize) are not providing same flexibilty to interact with Database cluster. 
kustomize yaml way is what we are using in gitOps (fluxcd) but we are not able to get all those flexibilities that we get in pgo installer.

**Comment by jkatz** [comment]
I think the issue is you're trying to install both PGO v4 and PGO v5. These have different interfaces. You should pick one (with a strong recommendation for [v5](https://access.crunchydata.com/documentation/postgres-operator/v5/) for new deployments).

I suggest going through the v5 [quickstart](https://access.crunchydata.com/documentation/postgres-operator/v5/quickstart/) and [tutorial](https://access.crunchydata.com/documentation/postgres-operator/v5/tutorial/),

**Comment by mdnfiras** [comment]
this problem is not solved even in `v5`:

this is the documentation for `v5` for installing with kustomize:
https://access.crunchydata.com/documentation/postgres-operator/v5/installation/kustomize/

it links to this github repo:
https://github.com/CrunchyData/postgres-operator-examples/

and says the yaml to apply is under `kustomize/install` so it's here:
https://github.com/CrunchyData/postgres-operator-examples/tree/main/kustomize/install

there is no pgo service in there, and no pgouser-admin secret and quite nothing that has to do with the pgo client.

It would be nice to know how to manually generate the required ca and user certificate and key, as well as the pgo client username and password. Thanks.

**Comment by mdnfiras** [comment]
this problem is not solved even in `v5`:

this is the documentation for `v5` for installing with kustomize:
https://access.crunchydata.com/documentation/postgres-operator/v5/installation/kustomize/

it links to this github repo:
https://github.com/CrunchyData/postgres-operator-examples/

and says the yaml to apply is under `kustomize/install` so it's here:
https://github.com/CrunchyData/postgres-operator-examples/tree/main/kustomize/install

there is no pgo service in there, and no pgouser-admin secret and quite nothing that has to do with the pgo client.

It would be nice to know how to manually generate the required ca and user certificate and key, as well as the pgo client username and password. Thanks.

**Comment by TauqeerAhmad104** [comment]
I have the same issue, No solution found at stage 2 I see error no file or directory even I have files in it.
