### ISSUE TITLE
restore specific db

### ISSUE THREAD

**Issue by AlfadilTabar** [CrunchyData/postgres-operator#2989]
Have an idea to improve PGO? We'd love to hear it! We're going to need some information from you to learn more about your feature requests.

Please be sure you've done the following:

- [ ] Provide a concise description of your feature request.
- [ ] Describe your use case. Detail the problem you are trying to solve.
- [ ] Describe how you envision that the feature would work.
- [ ] Provide general information about your current PGO environment.

## Overview

restore specific DB rather than all DBs in the cluster

## Use Case

I've many apps running on postgresql sometime one of the apps has a failed orm migration. So I need to go back to a the pervious version of only one app not all of them

## Desired Behavior

be able to restore specific DB rather than all DBs in the cluster
## Environment

- Platform: `OpenShift`
- Platform Version: `4.7.0`
- PGO Image Tag: `ubi8-5.0.3-0`
- Postgres Version:  `13`
- Storage: ceph
- Number of Postgres clusters: `1`

**Comment by AlfadilTabar** [comment]
Can you please help me with this @jkatz

**Comment by jkatz** [comment]
The v5 documentation provides information on this (see https://github.com/CrunchyData/postgres-operator/commit/a15544d6d3889cd11a3f5970869ca1c38fa1e858#diff-a8f70e868869f6f2e6b4bb002602e75cc2079b30359929a4bbeeb9b2ece61f79R205)

This describes the methodology, which can be applied to v4 as well, as well as the limitations.

However, in the event of failed migrations, I don't believe doing a PITR is the correct approach as this is a very destructive procedure. It would be better to first test the migrations against a copy of your production database, ensure they work, and then apply it to production. You should also run your migrations in a transaction so that if they do fail, it is simpler to roll back.

**Comment by AlfadilTabar** [comment]
Thanks for your time and effort @jkatz
