### ISSUE TITLE
Using PGO with wal_level set to replica according to TimescaleDB suggestion

### ISSUE THREAD

**Issue by nimrodWib** [CrunchyData/postgres-operator#3002]
So I use PGO with Timescaledb and use the backup feature.

I noticed that the default wal_level value is set to logical which [TimescaleDB docs](https://docs.timescale.com/timescaledb/latest/how-to-guides/replication-and-ha/replication/) recommend not to use. The docs recommend wal_level of replica.

I checked if pgBackRest support wal_level replica and indeed it does.

My question than is, how can I (or should I?) change the wal_level to replica? I guess that I can do it in patroni.dynamicConfiguration.postgresql.parameters but I want to be sure that it will work as expected b4hand :)

Thanks a lot for PGO, it's really an amazing project! :D

**Comment by andrewlecuyer** [comment]
Please note that while a `wal_level` of `logical` _enables_ logical replication, this does not mean logical replication is actually being utilized.  E.g. per the [PostgreSQL documentation describing `wal_level`](https://www.postgresql.org/docs/current/runtime-config-wal.html):

> The default value is `replica`, which writes enough data to support WAL archiving and replication, including running read-only queries on a standby server. `minimal` removes all logging except the information required to recover from a crash or immediate shutdown. Finally, `logical` adds information necessary to support logical decoding. Each level includes the information logged at all lower levels.

Therefore, while by default PGO _enables_ the use of logical replication by configuring PG to support it per the above, it does not use actually use it.

More specifically, the HA system (Patroni) uses _streaming replication_ (which is supported when `logical` is configured per the above PG docs), e.g. as described in the [Patroni documentation](https://patroni.readthedocs.io/en/latest/README.html?highlight=streaming%20replication#replication-choices):

> Patroni uses Postgres’ streaming replication, which is asynchronous by default.

Therefore, there should be no need to change the `wal_level`, since streaming replication (as recommend by Timescale) is already in use for replication.

However, if despite this you are seeing any unexpected behavior and/or issues, please let us know.

**Comment by nimrodWib** [comment]
@andrewlecuyer Perfect! thanks for ur clear answer :)
