### ISSUE TITLE
Labels are not propagated to secrets of type kubernetes.io/service-account-token

### ISSUE THREAD

**Issue by marco-devopsdojo** [CrunchyData/postgres-operator#3007]
## Overview

Adding labels in the postgres CRD propagates labels to all resources except the serects of type kubernetes.io/service-account-token:

- <name>-instance-token-<suffix>
- <name>-pgbackrest-token-<suffix>

## Environment

Please provide the following details:

- Platform: Kubernetes
- Platform Version: 1.17
- PGO Image Tag: ubi8-5.0.4-0

### REPRO

Provide steps to get to the error condition:

Create a cluster and provide labels to:
1. CRD
2. PostgresClusterSpec
3. PostgresInstanceSetSpec
4. PGBackRestArchive

### EXPECTED
Labels set in 
- <name>-instance-token-<suffix>
- <name>-pgbackrest-token-<suffix>

### ACTUAL
no labels set in 
- <name>-instance-token-<suffix>
- <name>-pgbackrest-token-<suffix>

## Additional Information

Not sure if this is a bug / limitation / something else.

**Comment by andrewlecuyer** [comment]
@marco-devopsdojo PGO only adds custom labels to the specific resources that it reconciles (and/or any templates within those resources that allow for the definition of labels, e.g. Pod templates within StatefulSet's).  Therefore, we add custom labels to the Service Account itself since it is actually reconciled by PGO - but since Kubernetes (and not PGO itself) creates the service account token, the labels are not added to it.

Is there a specific use case for requiring custom labels on the actual token?

Also, please also see our compatibility documentation for the versions of Kubernetes currently supported by PGO (I wanted to mention this since I see that you are running on Kubernetes 1.17):

https://access.crunchydata.com/documentation/postgres-operator/v5/references/components/

**Comment by marco-devopsdojo** [comment]
Hi @andrewlecuyer,

I was just curious whats done behind the scene, and why what is happening and those 2 are not labeled. 

Thank you for the answer!
Best
Marco
