### ISSUE TITLE
Restoring a database when the postgres image has been deleted

### ISSUE THREAD

**Issue by hstefan** [CrunchyData/postgres-operator#3113]
-  Platform: kubernetes/GKE
-  Platform Version: 1.22.8-gke.200
-  PGO Image Tag: postgres-operator:centos8-4.7.5
-  Postgres Version: 12.7
-  Storage: gce disk

I've been trying to recover my Postgres 12.1 database for weeks and haven't managed to make any progress, so I would really appreciate some help. This is a small database so if I just do a sql dump it's more than enough for me to just recreate things.

Here's a few things a tried:

- running `pgo upgrade` as explained in [the docs](https://access.crunchydata.com/documentation/postgres-operator/4.7.5/upgrade/automatedupgrade/)
  - this resulted in a message to the effect of "cannot upgrade from version 12.1 to 13.x" (I no longer have the exact message saved)
- recreating the clustere with a new `pgo create cluster ` command as explained in the [Manual Upgrade](https://access.crunchydata.com/documentation/postgres-operator/4.7.5/upgrade/manual/upgrade4/) guide
   - this "worked" but then the pgbackrest job failed to create the stanza, and I couldn't see why in the logs
- installing pgbackrest on virtual machine and attempting to manually recreate my cluster from the repository
   - results in `ERROR: [028]: backup and archive info files exist but do not match the database`

I'm running out of ideas, so if anyone has a suggestion on how I could proceed that would be greatly appreciated.

**Comment by benjaminjb** [comment]
Hi @hstefan, could you add some info about what platform, system, etc. you're using for this?

- Platform: (`Kubernetes`, `OpenShift`, `Rancher`, `GKE`, `EKS`, `AKS` etc.)
- Platform Version: (e.g. `1.20.3`, `4.7.0`)
- PGO Image Tag: (e.g. `ubi8-5.1.0-0`)
- Postgres Version (e.g. `14`)
- Storage: (e.g. `hostpath`, `nfs`, or the name of your storage class)

It might also help if you could say what happened to the original database that led to this. You say "when the postgres image has been deleted" and I'm not entirely sure what you mean by that.

**Comment by EugenMayer** [comment]
We have the very same issue - we run a PG 12 cluster and trying to either install a new one or making a DR since not restore image can be spawned.

For us, this is a huge issue, since this renders our entire current cluster unrecovable when it fails and i really do not understand why the images have been unpublished. I understand that you stopped supporting them (updates and so on) - surely fair and square.

But deleting the already released has massive consequences. 

We cannot even test and 13 properly since we could not restore a pg12 cluster from DR due to that reason.

That all said, is there any way to get grip of the old image so we can put it on our own registry

`registry.developers.crunchydata.com/crunchydata/crunchy-postgres:centos8-12.9-0`

Just a way to pull it once. Thank you!

**Comment by EugenMayer** [comment]
If anybody is in need, we published

`https://github.com/users/EugenMayer/packages/container/package/crunchy-postgres` so `ghcr.io/eugenmayer/crunchy-postgres:centos8-12.9-0`

I understand that there should be zero trust - but if you are in need, pick that one - it should be 100% the same as `registry.developers.crunchydata.com/crunchydata/crunchy-postgres:centos8-12.9-0`

If you want and should do it yourself:

- on your k8s cluster install ctr
- export the image using `image export`
- download the image via scp / whatever
- import in via `docker image load`
- push it into your registry of choice

That is what we did

**Comment by benjaminjb** [comment]
This is a persistent problem with our open-source community: we try to maintain up-to-date and secure images for the last 2-3 Postgres versions (usually, depending on stability), but like I said, this is a problem because people have an expectation that images will remain pull-able. I'm not going to be able to solve that problem for you here, today, but I'm going to escalate, because we need at least some clearer documentation around that.
