### ISSUE TITLE
Service Binding - tls.key populated with "group or world access" file permissions

### ISSUE THREAD

**Issue by pacostas** [CrunchyData/postgres-operator#3219]
I've been trying to establish a connection using odbc driver with credentials populated through the service binding operator under /binding directory, which unfortunately ends up with the below error: 

```
Connection error: [Error: [odbc] Error connecting to the database] {
  odbcErrors: [
    {
      state: '08001',
      code: 101,
      message: 'private key file "/bindings/odbc-example-worker-dc-hippo-pc/tls.key" has group or world access; permissions should be u=rw (0600) or less\n'
      }
  ]
}
```
I suppose that crunchy postgres-operator has defined the permissions of tls.key file, to something other than 0600, wherein that case does not pass the validation where odbc driver requires (probably with an external library).

Is there any configuration, provided by crunchy postres-operator, during or after deployment which can change the permissions of the tls.key file to 0600 ?

Otherwise, I consider this a bug as populated files under the /binding directory should be in a ready-to-use state, not conflicting with any validations operated by psql drivers.

**Comment by tjmoore4** [comment]
Hello @pacostas,

As a rule, we set the certificate [permissions to 0600](https://github.com/CrunchyData/postgres-operator/blob/master/internal/postgres/reconcile.go#L82-L85). However, due to a known [Kubernetes issue](https://github.com/kubernetes/kubernetes/issues/57923) this setting is not respected in all Kubernetes versions. We do handle this issue in the case of our replication client certificate files by [setting 0600 as required](https://github.com/CrunchyData/postgres-operator/blob/master/internal/postgres/config.go#L227-L238). Perhaps a similar approach could work in your case?

**Comment by andrewlecuyer** [comment]
Since @tjmoore4 has addressed the initial question with the response above, proceeding with closing this issue.

If you have any additional questions, or if there is anything else we can assist with, please either re-open or submit a new issue.
