### ISSUE TITLE
The attribute "RootSecretName" is duplicate in the documentation

### ISSUE THREAD

**Issue by johnlinp** [CrunchyData/postgres-operator#3278]
I'm reading the documentation for Custom Resource Definition of `Pgcluster`: https://access.crunchydata.com/documentation/postgres-operator/4.5.0/custom-resources/. I spotted that the attribute `RootSecretName` is duplicated:

<img width="867" alt="image" src="https://user-images.githubusercontent.com/1290376/176003743-e39d7066-9db6-442d-8120-a0f1168ff21a.png">

I believe that it's a documentation mistake, but I'm not sure how I can fix it. Any suggestion is appreciated.

**Comment by benjaminjb** [comment]
Hello, thanks for identifying this, but I'm going to close this issue since 4.5 is no longer being actively maintained. 

(Also, this field was removed in [4.6](https://access.crunchydata.com/documentation/postgres-operator/4.7.11/releases/4.6.0/#breaking-changes), so we don't have to fix the documentation for later versions of v4.)
