### ISSUE TITLE
Postgres Operator with hostpathstorage as Backend persistent layer

### ISSUE THREAD

**Issue by Bishnup1995** [CrunchyData/postgres-operator#3294]
The issue is similar to [this](https://github.com/CrunchyData/postgres-operator/issues/1807) issue.

I am trying to set up Postgres cluster using the Postgres operator. I am facing an issue where the pod backrest-shared-repo is always in a Pending state.
```
NAME                      STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   AGE

postgres-ha-1             Pending                                                     12m

postgres-ha-1-pgbr-repo   Pending                                                     12m

```
While debugging I found that the `PersistentVolumeClaim` is also in a pending state. Events of `PVC` is below:
`no persistent volumes available for this claim and no storage class is set`

**PVC.yaml**
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: "2022-07-08T10:28:48Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    pg-cluster: postgres-ha-1
    vendor: crunchydata
  name: postgres-ha-1-pgbr-repo
  namespace: pgo
  resourceVersion: "1786569"
  uid: 6f80d516-320c-490e-ad6a-83400ea998a4
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 3G
  volumeMode: Filesystem
status:
  phase: Pending

```
Below is the storage configuration in `postgres-operator.yml`:

```
backrest_storage: "hostpathstorage"
backup_storage: "hostpathstorage"
primary_storage: "hostpathstorage"
replica_storage: "hostpathstorage"
pgadmin_storage: "hostpathstorage"
wal_storage: ""
storage1_name: "default"
storage1_access_mode: "ReadWriteOnce"
storage1_size: "1G"
storage1_type: "dynamic"
storage2_name: "hostpathstorage"
storage2_access_mode: "ReadWriteMany"
storage2_size: "3G"
storage2_type: "create"
storage3_name: "nfsstorage"
storage3_access_mode: "ReadWriteMany"
storage3_size: "1G"
storage3_type: "create"
storage3_supplemental_groups: "65534"
storage4_name: "nfsstoragered"
storage4_access_mode: "ReadWriteMany"
storage4_size: "1G"
storage4_match_labels: "crunchyzone=red"
storage4_type: "create"
storage4_supplemental_groups: "65534"
storage5_name: "storageos"
storage5_access_mode: "ReadWriteOnce"
storage5_size: "5Gi"
storage5_type: "dynamic"
storage5_class: "fast"
storage6_name: "primarysite"
storage6_access_mode: "ReadWriteOnce"
storage6_size: "4G"
storage6_type: "dynamic"
storage6_class: "primarysite"
storage7_name: "alternatesite"
storage7_access_mode: "ReadWriteOnce"
storage7_size: "4G"
storage7_type: "dynamic"
storage7_class: "alternatesite"
storage8_name: "gce"
storage8_access_mode: "ReadWriteOnce"
storage8_size: "300M"
storage8_type: "dynamic"
storage8_class: "standard"
storage9_name: "rook"
storage9_access_mode: "ReadWriteOnce"
storage9_size: "1Gi"
storage9_type: "dynamic"
storage9_class: "rook-ceph-block"
```

How to solve this issue?
I am using `postgres-operator 4.7.4`.

**Comment by andrewlecuyer** [comment]
@Bishnup1995 it looks like the PVC being generated by PGO (specifically based on the storage config in the `pgo.yaml`) is unable to find a PV to bind to.  And because you do not have a storage class set (i.e. there is no `storage2_class` set in your `pgo.yaml`), there is no storage class for Kubernetes to use to generate the proper PV either.

Do you have a specific `StorageClass` that you're using to provision your `hostPath` volumes?  If so, ensure the proper `StorageClass` is set via `storage2_class` in the `pgo.yaml` file.

If not using a `StorageClass`, you will need to provision the PV's manually, and then configure your storage settings in the `pgo.yaml` accordingly (e.g. with a `size` that matches the PV's created, etc.).  In the following directory you will find an example script and spec for generating `hostPath` PV's:

https://github.com/CrunchyData/postgres-operator/blob/REL_4_7/pv/create-pv.sh
https://github.com/CrunchyData/postgres-operator/blob/REL_4_7/pv/crunchy-pv.json
