### ISSUE TITLE
why is spec.patroni.switchover.enabled not true by default?

### ISSUE THREAD

**Issue by mzwettler2** [CrunchyData/postgres-operator#3388]
Short question.

Why is spec.patroni.switchover.enabled not true by default?

Nothing could happen if it is true as an annotation is needed anyway.

**Comment by tjmoore4** [comment]
Hi @mzwettler2. We use `enabled` here (and certain other places, such as our restore functionality) to ensure the desired behavior only happens when the user really wants it to happen. In this case, we use the `status` on the PostgresCluster object to determine if a desired switchover has completed, but in cases where that `status` is lost or otherwise removed, that could result in a switchover at an unexpected time. So, we use `enabled` to ensure this only ever happens when it should.

This is why our [documentation](https://access.crunchydata.com/documentation/postgres-operator/latest/tutorial/administrative-tasks/) states, "After changing the primary, we recommend that you disable switchovers by setting spec.patroni.switchover.enabled to false or remove the field from your spec entirely."
