### ISSUE TITLE
LDAP with TLS - Unable to authenticate to LDAP when enabling TLS connections

### ISSUE THREAD

**Issue by bananabob93** [CrunchyData/postgres-operator#3393]
I am having issues connecting to LDAP using TLS. When I am not using TLS in my configuration (port 389 + ldap vs. port 636 + ldaps) I can authenticate without issues. As soon as I configure the connection with TLS it will not authenticate. I believe the issue is that my connection is not using the certificate that I have mounted to `etc/openldap/certs`. I also am not sure how and which environment variables to set to indicate which path to use for the correct certificate.  

## Questions

I would like to find out either:
- Where to mount the certificate so that it is used in TLS connections to LDAP
- How to configure an environment variable (or etc/openldap/ldap.conf?) to specify a certain path to a certificate. 

### Environment

Please provide the following details:

- Platform: Kubernetes
- Platform Version: 1.21
- PGO Image Tag: `ubi8-14.4-0`
- Postgres Version `14`
- Storage: -

**Comment by andrewlecuyer** [comment]
Hi @bananabob93!  Just wanted to reach out to see if you're still having trouble with your LDAP configuration.

If this issue is no longer relevant, I will proceed with closing.  Otherwise, would definitely be interested in hearing if you were able to get LDAP configured per your requirements/needs.

I'll also note that you can feel free to continue the conversation in the [PGO project community discord server](https://discord.gg/a7vWKG8Ec9).
