### ISSUE TITLE
How to deploy in kubernetes 1.25

### ISSUE THREAD

**Issue by maaft** [CrunchyData/postgres-operator#3411]
Although Kubernetes 1.25 should be supported now with this [MR](https://github.com/CrunchyData/postgres-operator/pull/3370), the official installation guides still fail with:

```
time="2022-08-29T15:33:28Z" level=error msg="if kind is a CRD, it should be installed before calling Start" error="no matches for kind \"CronJob\" in version \"batch/v1beta1\"" file="sigs.k8s.io/controller-runtime@v0.8.3/pkg/log/deleg.go:144" func="log.(*DelegatingLogger).Error" kind=CronJob.batch version=5.1.3-0
panic: no matches for kind "CronJob" in version "batch/v1beta1"

goroutine 1 [running]:
main.assertNoError(...)
        github.com/crunchydata/postgres-operator/cmd/postgres-operator/main.go:40
main.main()
        github.com/crunchydata/postgres-operator/cmd/postgres-operator/main.go:100 +0x550
```

Are there any clear instructions how to deploy PGO on kubernetes 1.25? Are there new image tags that I'm not aware of? Latest I could find is `5.2.0-0`

**Comment by m0sh1x2** [comment]
I have come to the same issue. Is are there any official tags that I can use for the operator or are there any instructions on how to build it and run from a custom registry?

**Comment by m0sh1x2** [comment]
I just checked the docs and the supported k8s version for the operator is 1.24. Not sure why I was focusing so hard on the 1.25 and trying to make it work.

**Comment by maaft** [comment]
Because there was a recent PR and therefore it **is** currently supported in `master`. But since `master` is not exactly stable, we'd need to wait for an official release.

**Comment by benjaminjb** [comment]
Yeah, you all got it: that PR is merged into `master` and is planned to be available in the next release. (`5.2.0-0` is the latest release, so there's no new images yet.)

As for building your own for testing/playing, we have a `make` target for building the image -- `make postgres-operator-img-build`, and I _think_ that we did some work so that anyone could do that, but I'm not 100% sure on that. 

(I'm not sure because A: I'm always signed in to vendors that we use at CrunchyData and B: I really rarely build an image from this repo since we have this `deploy-dev` target that lets you run the operator locally, but pointed at any kube env.)

I think all the questions have been answered, so I'll close this now, but if you all have other related questions or if I missed, please reopen.

**Comment by nward** [comment]
@benjaminjb is there a timeline for a release with this PR included?

**Comment by benjaminjb** [comment]
> @benjaminjb is there a timeline for a release with this PR included?

@nward there's no timeline that I can speak to at this moment.

**Comment by ksawerykarwacki** [comment]
@benjaminjb Any updates on that? We are over a month later and still don't even have any date when we will get the support of kube 1.25.
