### ISSUE TITLE
any hack to write log messages to the local logfile and elf stack at the same time?

### ISSUE THREAD

**Issue by mzwettler2** [CrunchyData/postgres-operator#3560]
Setting logging_collector=off will send the log messages to stderr and the ELF stack in following.

Setting the logging_collector=on will capture all log messages and not sending them to stderr and the ELF stack anymore.

Its troublesome to produce pgbadger reports that way because you always have to flip logging_collector around.

I just wondered if there is any hack which would allow to write to the local logfile on disk **_and_** stderr / elf stack at the same time?

Thanks, Markus

**Comment by tjmoore4** [comment]
Hello @mzwettler2. Thanks for reaching out. Could you provide more information on how you are deploying your ELF stack and pgbadger?

Also, for implementation questions please consider joining the [PostgreSQL Operator community mailing list](https://groups.google.com/a/crunchydata.com/forum/#!forum/postgres-operator/join) and posting questions there for a broader community.

**Comment by mzwettler2** [comment]
Hi @tjmoore4 

The ELF stack on our K8s plattform consists of Filebeat => Logstash => Opensearch.

When we want a pgbadger report:
- we set logging_collector=on
- download the generated logfile to an external Linux box with pgbadger installed
- generate the pgbadger report

Thanks, Markus

**Comment by tjmoore4** [comment]
Thank you for the additional information.

One resource that I'd like to mention is a recent blog post, [Log Export Examples Using Crunchy Postgres for Kubernetes](https://www.crunchydata.com/blog/log-export-examples-using-crunchy-postgres-for-kubernetes). This illustrates some strategies that may be helpful in meeting your specific use case. 

Otherwise, our [community mailing list](https://groups.google.com/a/crunchydata.com/forum/#!forum/postgres-operator/join) will likely be the best option for other potential solutions.
