### ISSUE TITLE
PGUpgrade does not remove wal files from old cluster

### ISSUE THREAD

**Issue by stemid** [CrunchyData/postgres-operator#3623]
## Overview

The pgupgrade process does not delete the old wal directory, meaning it "wastes" space on your volume unless you delete it yourself.

## Environment

Please provide the following details:

- Platform: Kubernetes
- Platform Version: 1.21.14
- PGO Image Tag: ubi8-5.3.0-0
- Postgres Version 14
- Storage: rook-ceph-block

### REPRO

Provide steps to get to the error condition:

1. Follow the docs for a postgres major version upgrade
2. run the commands and scripts at the end of the pg_upgrade output.

### EXPECTED

1. All old dirs should be deleted, pg13 and pg13_wal.

### ACTUAL

1. Only pg13 is deleted, pg13_wal is left.

**Comment by dsessler7** [comment]
Hello @stemid,

This is actually by design. Our major upgrade procedure will delete the `/pgdata/pg##` and `/pgdata/pg##_wal` directories for the old version from the replicas; however, we leave them in place on the primary. We don't want to automatically delete them in case something goes wrong with the upgrade.

The `delete_old_cluster.sh` script referenced in our documentation is actually created by `pg_upgrade` and yes, it only deletes the old `pg##` directory, not the wal directory. All this script is doing is running a `rm` command on the directory. If you want to delete the old `pg##_wal` directory as well, you can manually run the command on that directory.
