### ISSUE TITLE
timescaledb_toolkit installation  issue

### ISSUE THREAD

**Issue by Suneethaaw** [CrunchyData/postgres-operator#3625]
I am using crunchydata/postgres-operator ubi8-5.3.0-0 docker image in that i want to enable timescaledb_toolkit. when i tried to login as root user using the following command
` docker run -u root -it 63247d4e3da7 /bin/sh`
Then i tried installing yum, dnf, sudo, curl for downloading the timescaledb_toolkit but it did not worked.

Actually i wanted this timescaledb_toolkit inside my pod but there too ima facing the similar issue
i tried to download timescaledb_toolkit externally and copied inside the pod but immediately pod got restarted.

Please guide what is the correct way to install timescaledb_toolkit on crunchy postgres images or existing containers/pods

Why we have restriction on package managers like dnf or yum

**Comment by dsessler7** [comment]
Hello @Suneethaaw,

Using the TimescaleDB Toolkit involves installing a separate package, one that we don't currently install in the Crunchy Postgres image. Packages need to be installed when the image is built, otherwise they will disappear whenever the container is restarted.

I will add a feature request story to our dev backlog to support TimescaleDB Toolkit.
