### ISSUE TITLE
User creation with schema

### ISSUE THREAD

**Issue by douggutaby** [CrunchyData/postgres-operator#3653]
I'm about to migrate my v4 clusters to v5.3.1 operator.
First, I tried the new cluster creation way, and I tried to create my own user and database. In v4 I could do that with the -d databasename and -u username and in v5 with the users part of the values.yaml

But the v4 method created schema with the user but in v5 it didn't create schema.

Is there any parameter to create schema or should I use init.sql? Let me know if I'm wrong.

**Comment by douggutaby** [comment]
Can anyone help me with this? Is there any other method then init.sql to create schema for new user?

**Comment by andrewlecuyer** [comment]
Hi @douggutaby, just wanted to see if you are still having any trouble with your upgrade.

I will note that we do have a story in our backlog to consider schema creation for users, and welcome any additional feedback you might have.  And in the meantime, the init SQL is indeed likely your best option.

Feel free to reach out if you have any additional questions.  Otherwise, if this is no longer an issue, I will proceed with closing this out.

**Comment by douggutaby** [comment]
Sorry, I left the company where we used crunchy. I cannot answer.

**Comment by andrewlecuyer** [comment]
Thanks for the reply @douggutaby.  In that case, I will proceed with closing this issue.
