### ISSUE TITLE
PGO backup process flow description

### ISSUE THREAD

**Issue by mzwettler2** [CrunchyData/postgres-operator#3676]
My understanding of the PGO backup process flow has always been this. 

There is the instance pod and the repo pod. When a backup is scheduled, a K8s cronjob is created. This creates a K8s job at runtime which then starts a backup pod running pgbackrest. The backup pod mounts both the /pgdata volume of the instance pod and the /pgbackrest volume of the repo pod and executes the pgbackrest command (scp).

In the K8s resource monitoring of the pods, we saw now that during the backup, the instance pod used nearly 100% CPU, the repo pod used  about 30% CPU, while the backup pod only used about 0.6% CPU.

So my guess would be that the backup flow works differently. How exactly? Which pod executes the pgbackrest command (scp)?

**Comment by tjmoore4** [comment]
Hello @mzwettler2, thank you for your question. The resource utilization discrepancy you mention is related to a subtle difference in our architecture as you correctly inferred. The actual pgBackRest backup runs either on the repo host or the primary instance Pod, depending on the specifics of your configuration.

This is done by exec-ing into the appropriate Pod and does not require mounting volumes on the backup Pod itself. Backups do result in resource utilization on the primary as data moves from the primary to the repository, but this is due to the operation of pgBackRest, not a separate move utility such as scp. Hope this helps!

**Comment by mzwettler2** [comment]
@tjmoore4 

Thanks for the explanation. How can I see on which pod the backup will be running? This is important to set the resources accordingly so that the backup does not take too long.

**Comment by mzwettler2** [comment]
@tjmoore4 

I found that the backup seems to be done within the pgbackrest sidecar container at the instance pod.
Resources can be set using the spec.backups.pgbackrest.sidecars.pgbackrest keys.

Is a restore also executed within the pgbackrest sidecar container at the instance pod?

Thanks, Markus

**Comment by tjmoore4** [comment]
Hi @mzwettler2. You're very welcome. Just to clarify, as discussed in our [documentation](https://access.crunchydata.com/documentation/postgres-operator/5.3.2/tutorial/disaster-recovery/), there are several distinct options that we could be talking about when performing a restore. That said, assuming an in-place restore, the command would be executed in the restore Pod generated from the `<cluster-name>-pgbackrest-restore` Job. This only has one container, which should use the defined Postgres image.

Hope that helps!

**Comment by mzwettler2** [comment]
Found and tested. Thanks, Markus
