### ISSUE TITLE
Update pgAdmin

### ISSUE THREAD

**Issue by mausch** [CrunchyData/postgres-operator#3780]
According to https://www.crunchydata.com/developers/download-postgres/containers/pgadmin4 the latest version available of pgAdmin4 is 4.30 .

[This version is currently 3 years old](https://www.pgadmin.org/docs/pgadmin4/development/release_notes_4_30.html)...
Not only is it missing lots of improvements but also [this old version doesn't work with Postgres 15+](https://stackoverflow.com/questions/69378663/how-can-i-solve-servermanager-object-has-no-attribute-user-info-error-in-pos)

I tried passing an image from https://hub.docker.com/r/dpage/pgadmin4/ into `userInterface.pgAdmin.image` but it doesn't start at all.

Workaround: disable `userInterface` and install https://github.com/rowanruseler/helm-charts

**Comment by benjaminjb** [comment]
Hello @mausch, we've recently released a new version of the postgres-operator and the pgadmin4 image that I hope takes care of your very valid issues here. But there's one big change that I wanted to bring to your attention:

We have a new API and a new custom resource for pgAdmin4. That means, rather than launching a pgAdmin4 per cluster, you can now have a single pgAdmin4 manage multiple clusters.

(We still do have the `userInterface` section and you can still create a pgAdmin4 for a particular postgrescluster, but that method still uses the older image, which as you point out, isn't up to date.)

For more info on this new method of requesting a pgAdmin4, please see these [docs](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/namespace-scoped-pgadmin-4).

I'm going to close this ticket, but please let us know what you think of this new method for requesting a pgAdmin4 deployment! We have a [discord](https://discord.com/invite/a7vWKG8Ec9) now for chatting, or feel free to reopen this ticket.

**Comment by mausch** [comment]
Great thanks, so this means the `userInterface` section is now effectively deprecated?

**Comment by benjaminjb** [comment]
> Great thanks, so this means the `userInterface` section is now effectively deprecated?

Good question -- I suppose that depends on your definition of "deprecated." :) I don't think there's any official plan at the moment to remove the `userInterface` section, so I wouldn't warn people away from using it. But I would say that the new implementation is very flexible and fits in a lot of use cases.

We're open to feedback, of course, on what direction to take with cluster administration via pgAdmin4, but I think there's more we can do with the new API.
