### ISSUE TITLE
Which kubernetes service should I connect to?

### ISSUE THREAD

**Issue by gregory-j-baker** [CrunchyData/postgres-operator#3784]
I have deployed a cluster and now have the following services:

- cluster-ha
- cluster-pgbouncer
- cluster-primary
- cluster-replicas

Is isn't clear to me which of these services I should connect to when a) connecting from inside the cluster, and b) port-forwarding when connecting externally.

The documentation shows an example of connecting internally (ie: in-cluster) to the `cluster-primary` service, but when connecting via port-forwarding it forwards to the master pod (bypassing the service altogether).

When using pgbouncer, does it make sense to just use the the pgbouncer service for everything?

**Comment by jmckulk** [comment]
hi @gregory-j-baker, thanks for reaching out.

I see where we are port-forwarding to the primary pod instead of the service in our quickstart guide. In our [docs](https://access.crunchydata.com/documentation/postgres-operator/latest/tutorials/basic-setup/connect-cluster) there is a note saying that the `cluster-primary` service should be used for the purposes of connecting to the database. I created an issue to update the guide to use the service instead of the primary pod. Either way, you should end up with the same connection.

There have been a few questions where users were confused about the services that are created with a PostgresCluster. I created an issue in our backlog to improve the documentation around Services. Over in the [discord](https://discord.com/channels/1068276526740676708/1174568367139586078) I put together the following reply:

There is a note about these services in the [docs](https://access.crunchydata.com/documentation/postgres-operator/latest/tutorials/basic-setup/connect-cluster):

> You do not need to worry about most of these Services, as they are used to help manage the overall health of your Postgres cluster. For the purposes of connecting to your database, the Service of interest is called hippo-primary. Thanks to PGO, you do not need to even worry about that, as that information is captured within a Secret!

Here is a more detailed description of the services:
- hippo-ha: This service is managed directly by the High-Availability (HA) system, and routes traffic to the primary/leader.
- hippo-ha-config: This service is simply used to manage cluster-wide configuration settings, specifically via the associated Endpoints resource.
- hippo-pgbouncer:  As you mentioned, this service routes traffic to the connection pooler (PgBouncer).
- hippo-primary: As you mentioned, this service routes traffic to the current primary/leader.  Specifically, this Service provides a convenient DNS name with "primary" in it for connecting to the current primary/leader.
- hippo-replica: As you mentioned, this service routes traffic to PG replicas within your cluster (i.e., instances with the replica role).
- hippo-pods: service created for the StatefulSet (see [Headless Service limitation](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#limitations)).


Hopefully, this helps until we can get the documentation updated.

**Comment by davidglassborow** [comment]
Presumably we should then connect to the hippo-ha service ?  I'm guessing during failover hippo-primary will be updated, but until the DNS TTL is reached clients will be using the old IP
