### ISSUE TITLE
Citus integration guidance

### ISSUE THREAD

**Issue by jreuben11** [CrunchyData/postgres-operator#3815]
Can you provide guidance on integration with Citus ?

**Comment by dsessler7** [comment]
Hello @jreuben11,

Thanks for reaching out! We are currently exploring options for Citus support within CPK, and would definitely be interested in exploring your specific needs.  Due to the unique/specific requirements that often require the use of Citus, we typically find that it is best to connect directly. I therefore encourage you to reach out at [info@crunchydata.com](mailto:info@crunchydata.com) to discuss your specific use case further.
