### ISSUE TITLE
PGUpgrade images & version support

### ISSUE THREAD

**Issue by mzwettler2** [CrunchyData/postgres-operator#3849]
PGUpgrade enables in-place upgrades with pg_upgrade.
Both PG software versions old/new have to be installed in the image.

Question:
How can i find which PGUpgrade image supports with PG versions?
There are no references in the official PGO documentation.

**Comment by andrewlecuyer** [comment]
Hi @mzwettler2!

There is a note about this in the [Components & Compatibility docs](https://access.crunchydata.com/documentation/postgres-operator/latest/references/components#container-versions):

> The latest two major versions of Postgres are available through the [Crunchy Developer Program](https://www.crunchydata.com/developers/terms-of-use). The Postgres upgrade container includes one prior version of Postgres to facilitate major Postgres version upgrades.

Hope this helps!

**Comment by andrewlecuyer** [comment]
Hi @mzwettler2!

To clarify, the Postgres upgrade image contains one additional Postgres version, **_in addition_** to the two that are currently maintained via the Crunchy Developer Program (as specified on the [Supported Platforms page](https://access.crunchydata.com/documentation/postgres-operator/latest/overview/supported-platforms)).  For instance, the latest upgrade container for the CPK `v5.5.1` release (`crunchy-upgrade:ubi8-5.5.1-0`) includes Postgres 14, 15 and 16.

Considering you’re currently on Postgres 13, that means you should be able to simply leverage a recent version of CPK (specifically one that included support for Postgres 13) to upgrade to one of the two currently maintained versions of Postgres.  For instance, considering CPK `v5.4.1` was the last/latest Developer Program release of CPK with support for Postgres 13, you can use the included `crunchy-upgrade:ubi8-5.4.1-0` image to get to Postgres 15 (which is one of the two version of Postgres currently being maintained via the Developer Program).   And from there you can quickly/easily upgrade CPK to the latest version available (currently `v5.5.1`), which will then enable your to upgrade Postgres to version 16.

And moving forward, in addition to simply leveraging the [Supported Platforms page](https://access.crunchydata.com/documentation/postgres-operator/latest/overview/supported-platforms) to see the versions of Postgres currently supported via the Crunchy Developer Program, I also recommend signing up for the Developer Program mailing list via the link below.  This will ensure you receive the latest updates and announcements about to Postgres container availability, e.g. in order to keep your cluster’s images up-to-date:

https://www.crunchydata.com/developers/download-postgres/containers

**Comment by mzwettler2** [comment]
@andrewlecuyer 

Thanks for clarification. 

Wouldn't it make sense to always include the last 5 Postgres major versions in the current pgupgrade image, since every Postgres major version is supported for 5 years (also true for CPK if one is having a subscription).
