### ISSUE TITLE
Postgres Major Version Upgrade connection to server on socket "/pgdata/.s.PGSQL.50432" failed: FATAL:  could not access file "zombodb.so": No such file or directory

### ISSUE THREAD

**Issue by asd751167926** [CrunchyData/postgres-operator#3903]
Upgrade to a larger version of Postgres and encounter the following error. My environment is
PGO: 5.5 deploy/postgresql/crunchydata/postgres-operator:ubi8-5.5.0-0
Postgresql13.9: deploy/postgresql/crunchydata/crunchy-pgbackrest:ubi8-2.41-2
May I ask what the reason is

**Comment by asd751167926** [comment]
![111111111111111111111](https://github.com/CrunchyData/postgres-operator/assets/59405614/caff7e48-d147-4b84-90af-0cc881f6ba8f)

**Comment by asd751167926** [comment]
![111111111111111111111](https://github.com/CrunchyData/postgres-operator/assets/59405614/8e1267ee-5db5-4921-b1a5-a578159580d2)
![2222222222222222222222](https://github.com/CrunchyData/postgres-operator/assets/59405614/5ade9b8c-6551-46a1-9ffb-0fb4dfab23b2)

**Comment by ValClarkson** [comment]
Hi @asd751167926,  Sorry you are having issues.  Is zombodb.so and extension you installed?

**Comment by benjaminjb** [comment]
Hi @asd751167926, since we haven't heard from you in a while, I'm going to go ahead and close this ticket, but if you're still experiencing a problem around this, please reopen this ticket.

(I'll add: I looked briefly into zombodb's GH issues, and it seems that one way they advise handling upgrades is to remove the extension before and reinstall after the upgrade.)
