### ISSUE TITLE
Why does pgo decide on node placement?

### ISSUE THREAD

**Issue by tarasglek** [CrunchyData/postgres-operator#42]
I'm curious about the motivation for fixed placement of postgres instances. Feels like this would decrease robustness by preventing pod + pvc moving to a different node in event of node failure

**Comment by jmccormick2001** [comment]
actually you caught an error on my part which I forgot to change, in cluster-deployment-1.json, I should have specified preferredDuringSchedulingIgnoredDuringExecution instead of requiredDuringSchedulingIgnoredDuringExecution

I'll make that change and push it to master.  This will allow the scheduler to move the PG master in the event of a node failure as you would expect.

**Comment by jmccormick2001** [comment]
but to better answer your question, some people will want to place the master on a specific node over others in certain situations, if you don't specify --node-name on cluster creation, pgo should just pick a node at random for the master.  It will attempt to place the replicas on nodes that are not where the master is located.

**Comment by tarasglek** [comment]
There is another bug. Atm pgo picks first node by default. In my cluster first node is tainted. Feels like a better default behavior would be to not specify a node and let kubernetes scheduler decide.

**Comment by jmccormick2001** [comment]
thanks, I'll fix this, I agree, the default behavour should not be to specify a node.

**Comment by jmccormick2001** [comment]
merged  to master.

**Comment by jmccormick2001** [comment]
I plan on another release next week, around Thursday.

**Comment by jmccormick2001** [comment]
I decided not to wait, and went ahead and pushed version 1.5.2 which should fix this problem, thanks for reporting it.

**Comment by jmccormick2001** [comment]
should be fixed now.
