### ISSUE TITLE
postgresql.conf is missing 

### ISSUE THREAD

**Issue by wizurijyq** [CrunchyData/postgres-operator#507]
In the docs https://github.com/CrunchyData/postgres-operator/blob/8177160d1a77040654dceeb2a1d091dceb393396/hugo/content/how-it-works/_index.adoc#custom-postgres-configurations you mentioned there will be a postgresql.conf file, but it is not there..

**Comment by jmccormick2001** [comment]
I was referring to examples/custom-config but didn't specify that in the docs, noted and I'll update the docs to make it clearer.

**Comment by wizurijyq** [comment]
Is there a way to customise postgresql.conf file?

**Comment by jmccormick2001** [comment]
modify examples/custom-config/postgresql.conf, create the configmap from that example, the Operator looks for that ConfigMap, if found it will mount it inside the postgres containers it creates, the container looks for that mount and if it finds a postgresql.conf file, it will use that instead of its default postgresql.conf.

**Comment by wizurijyq** [comment]
Would that also work via the helm chart files, if I place the postgresql.conf in  https://github.com/CrunchyData/postgres-operator/tree/master/chart/postgres-operator/files/postgres-operator ?

**Comment by jmccormick2001** [comment]
possible I suppose to modify the Helm chart to create that config map for you, would be happy to accept a PR that creates that configmap via helm.
