### ISSUE TITLE
Direct CRD yaml edition issue

### ISSUE THREAD

**Issue by lkhomenk** [CrunchyData/postgres-operator#537]
** Which example are you working with? **
[Docs for 3.5](https://crunchydata.github.io/postgres-operator/stable/design/) tells: "Metadata about the Postgres cluster deployments are stored within these CRD resources which act as the source of truth for the Operator."
But direct edit on pgcluster CRD doesn't apply any changes. Is there any possible way to interact with postgres-operator w/o `pgo` tool? but same issue - updating cluster with `pgo scale` doesn't apply any changes to pgcluster yaml
**What is the current behavior?**
no update for CRD object after manual yaml edition
**What is the expected behavior?**
operator supposed to pick up updates and apply them. pgo tool should update crd yaml too
**Other information** (e.g. detailed explanation, related issues,  etc)
Operator log after yaml edition:
```level=debug msg="pgcluster test updated"```
and that's all
**Please tell us about your environment:**

* Operating System: Fedora 29 + minishift(openshift v3.11.0+1a90c5c-83)
* Where is this running ( Local , Cloud Provider) : local
* Storage being used (NFS, Hostpath, Gluster, etc): hostpath
* Container Image Tag: centos7-3.5.0-rc4
* PostgreSQL Version: centos7-11.1-2.3.0-rc3
* Platform (Docker, Kubernetes, OpenShift): Minishift
* Platform Version: v1.29.0+72fa7b2

**Comment by lkhomenk** [comment]
@jmccormick2001 Could you please suggest anything here?

**Comment by jmccormick2001** [comment]
I'll try this today.

**Comment by ron1** [comment]
Hi Jeff,

This is a significant ease-of-use improvement over the pgo client from my perspective. Thanks, Note that I will give it a try and provide feedback.

In the documentation, please be careful to distinguish between Custom Resources Definitions (CRDs) and Custom Resources as instances of CRDs. For example, the documentation https://github.com/CrunchyData/postgres-operator/blob/develop/examples/create-by-resource/NOTES.md#pgcluster-crd includes the following statement which I find confusing:

To cause the Operator to create a Postgres cluster, it is looking for a pgcluster CRD to be created...

It is my understanding that the actual pgcluster CRD is created here: https://github.com/CrunchyData/postgres-operator/blob/6807fbf110080078cecca74a037d7d6d126006b4/deploy/crd.yaml#L15 as part of the Operator installation. It is my understanding that the above action is creating a Pgcluster Custom Resource. Does that make sense?

Finally, I would recommend that the following example Pgcluster Custom Resource creation file use yaml instead of json: https://github.com/CrunchyData/postgres-operator/blob/develop/examples/create-by-resource/fromcrd.json. Most of the operator documentation I have seen uses yaml to create Custom Resources rather than json.

Thanks again,

Ron

**Comment by lkhomenk** [comment]
@jmccormick2001 that's a bit another case. I meant more something like:
1)create pgcluster `test_pg` - with pgo or from yamls with replica 1
2)go and edit pgcluster `test_pg` object - `oc edit pgclusters.cr.client-go.k8s.io test_pg` set replica=3
3.1)postgres_operator just notices that cluster `level=debug msg="pgcluster test_pg updated" ` , without making any changes
alternatively:
3.2)scale up +1 replica test_pg with pgo - verify changes  `oc get pgclusters.cr.client-go.k8s.io test_pg -o yaml` - replica count is still 3

Which means that [metadata](https://crunchydata.github.io/postgres-operator/stable/design/) of CRDs is not a golden source of truth. or maybe there's another metadata I could miss.

**Comment by ron1** [comment]
@lkhomenk, according to https://github.com/CrunchyData/postgres-operator/blob/develop/examples/create-by-resource/fromcrd.json, spec.replicas (with an 's') is the metadata field to control the number of replicas and not spec.replica which you mention in your comment. It might be that spec.replica is inherited but not used by the postgres-operator.

**Comment by lkhomenk** [comment]
@jmccormick2001 amount of replicas is just an example, which shows that pgcluster yaml is not a golden source of truth. It means that yamls just show initial state of the object and any further editions of the object do not apply any changes
