### ISSUE TITLE
Question about managed namespaces and number of pgo to deploy within an environment

### ISSUE THREAD

**Issue by ajoyej** [CrunchyData/postgres-operator#779]
Hello,

we are trying to find the best way to integrate pgo in our environment/requirements and come out with the following questions. Maybe someone could give us some answers to the one we have at the moment :-)

(1) We will have many postgres clusters deployed over time (say up to 60). Most likely, cluster will be deployed in different kubernetes namespaces (in the worst case, each cluster may be in a different ns). At the time of the initial pgo installation, these namespaces are not known and cannot be defined in advance. They will also be deleted in case a cluster in not needed anymore.

From what we understand, pgo cli does not provide, yet, a way to add namespaces that a managed by pgo. This must be currently done by calling "Ansible update".

What is the approach we should follow with the version 4.x in order to fulfill our requirement?

We would have thought that exposing a functionality to allow adding/removing managed namespace at the pgo cli level would be a good approach. Furthermore, it will also allow the OSB to use this functionality when creating a cluster.

(2) Say we plan to deploy up to 60 clusters, is it a good option to have only 1 operator to "manage" all these instances? or should we deploy several operator? Is 1 operator per cluster a viable solution?

(3) We will have also the requirements to add new db schemas within an existing cluster. Is this foreseen to add a db schema to an existing cluster using the cli (this functionality is available for a dB user)? If yes, what is the timeframe? If no, what is the way to go?

Thanks for any hints!
José

**Comment by jmccormick2001** [comment]
H,  you can use a single pgo namespace (operator) to manage a set of other namespaces, you can even add more namespaces to what the Operator watches if you want...you can add a new namespace to an existing pgo configuraiton as follows:  1) create the Kube namespace 2) add the rbac rules to that namespace so that it has the permissions required and 3) reconfigure the pgo operator to use that new namespace.  You might want to deploy the operator using the manual or develop installation method for now to test this out.  

as for object/database creation, today you need to do database creation via ether a policy which you can apply or manually using psql or some other postgres client.  Our goal long term is to have something like 'pgo create database --selector=env=prod' which would just create a database on the matching clusters...that command is not implemented yet.

hope that helps.

**Comment by ajoyej** [comment]
@jmccormick2001,
Thanks for the answer. Related to your point 3) reconfigure the pgo operator to use that new namespace,
What is the way to follow to achieve this goal?

Related to the second question, I will have a look to the policy feature

Regards,
José

**Comment by jmccormick2001** [comment]
doing a manual or developer install, you would:

kubectl create ns pgouser3

then:
export NAMESPACE=pgouser1,pgouser2,pgouser3

then run:

make installrbac

then:

make deployoperator

that sequence should work, they key here is to install the rbac into the new namespace essentially.

cheers.
