### ISSUE TITLE
Recommended way to use the default storageclass defined by K8s providers

### ISSUE THREAD

**Issue by ruairi-hayes** [CrunchyData/postgres-operator#963]
**What is the motivation or use case for the change?**
Our product has a requirement for users to be able to use the default storageclass defined in a 
any K8s provider offering.

**Describe the solution you'd like**
We'd like to know if there is a supported/documented way of deploying a crunchy postgres cluster without specifying a storageclass so that it will just pick up the "default" storageclass defined in a k8s provider offering.
I have played around with using `storage_type='create'` instead of the `dynmaic` option and then not specify a storageclass. This seems to work for our use case and the default storageclass get picks up but I'd like to know if this is the correct approach which should be documented or should the solution be implemented in an other way

**Comment by andrewlecuyer** [comment]
@ruairi-hayes, right now the PostgreSQL Operator does not select a default storage class based on the default storage class defined in the Kubernetes cluster.  Instead, a default is determined based on whether or not the following label is present:

```
pgo-default-sc=true
```

Otherwise if the above label isn't present on any storage class, the Operator will simply pick the first one it finds as a default.

This behavior is described in the following section of the PostgreSQL Operator documentation:

https://access.crunchydata.com/documentation/postgres-operator/4.2.0/configuration/configuration/

We will consider the use case for defaulting to the default storage defined in the Kubernetes cluster for a future release.
