### ISSUE TITLE
add the ability to pass the server certificates file location as parameters

### ISSUE THREAD

**Issue by raffaelespazzoli** [CrunchyData/postgres-operator#99]
right now the file location is fixed.

**Comment by jmccormick2001** [comment]
doppio-kube:[~/odev/src/github.com/crunchydata/postgres-operator] pgo version --pgo-ca-cert=/tmp/server.crt --pgo-client-cert=/tmp/server.crt --pgo-client-key=/tmp/server.key
pgo client version 3.4.0-rc1
apiserver version 3.4.0-rc1

with this change, you can enter the values as above instead of specifying env vars.
